### ISSUE TITLE
Could uploads be made to use https?

### ISSUE THREAD

**Issue by viric** [jjjake/internetarchive#100]
Hello,

if I understand correctly, all uploads work in cleartext. Could it be made to use https?

Thank you.

**Comment by jjjake** [comment]
All requests are currently HTTP by default, but can be switched to HTTPS by adding `secure=True` to your config. For example:

```
>>> from internetarchive import get_item
>>> item = get_item('my_identifier', config=dict(secure=True))
>>> item.protocol
'https:'
```

You can also add `secure: True` to your ia config file (i.e. `~/.config/internetarchive.yml`) to make all requests HTTPS by default.

**Comment by wumpus** [comment]
Jake, in the new world of "Encrypt all the things", I think what viric wanted was a changed default, not an option. Thanks for confirming that the encryption code is already present.
