### ISSUE TITLE
Document: Using spreadsheets to upload new files and modify metadata

### ISSUE THREAD

**Issue by catalandres** [jjjake/internetarchive#103]
Using a spreadsheet to upload new files or modify metadata appears as an option but it is not documented anywhere. Is there any chance we can get a minimum viable example?

**Comment by jjjake** [comment]
Thanks @catalandres, this should definitely be documented. Thanks for creating this issue.

Until I do that, you can use this as a template: https://github.com/kngenie/ias3upload/blob/master/metadata.csv

The only difference is that the `item` column should be `identifier` in `ia`. For more details on preparing the `metadata.csv` file, you can also refer to here: https://github.com/kngenie/ias3upload#prepare-your-metadata

Once your `metadata.csv` file is prepared, you can simply run `ia upload --spreadsheet=metadata.csv`.

I'll keep this open until it's properly documented. Thanks again.

**Comment by ckarpinski** [comment]
Hi, to clarify for myself - will ia upload --spreadsheet=metadata.csv  upload the files along with the spreadsheet or is this only uploading the metadata? 

I have instructions for putting a series of items into zip files with identifiers for names into a directory along side the spreadsheet, but that as far as I have gotten.

**Comment by jjjake** [comment]
`ia upload --spreadsheet=metadata.csv` will upload the files specified, as well as add the metadata from the spreadsheet to the item if it is the initial upload to the item. It will not upload the spreadsheet itself.

If the item has already been uploaded, you can use `ia metadata --spreadsheet=metadata.csv` to modify/update the metadata for that item.

Does that make sense @ckarpinski? Please let me know if you have any more questions or run into issues.

**Comment by ckarpinski** [comment]
Yes that does make sense, thank you so much. I will try it out and will let you know if I run into any issues.

**Comment by ckarpinski** [comment]
Hi again, 
I used ia configure and logged into our account and then I think got the upload to run (had to change "item" to "identifier" in the metadata.csv) but after looking like it was uploading the images from the first zip file of files listed on the csv it stopped with this "127/127 - 00:00:00
 error uploading suitedesreflexio00amal_images.zip to suitedesreflexio00amal, 400 Client Error: Bad Request
Any idea how I find out what this means?

**Comment by ckarpinski** [comment]
Hi again, 
I attempted to bulk upload by configuring to my account and then using ia upload --spreadsheet=metadata.csv (each line in the spreadsheet corresponds to a zip file of files)
and it looked like it was working, it said: 
uploading suitedesreflexio00amal_images.zip: [#############################   ]
for each of the 127 files inside the zip. but when it got to the last one it then shows this error: error uploading suitedesreflexio00amal_images.zip to suitedesreflexio00amal, 400 Client Error: Bad Request

Do you know what this means or how to go about finding out what went wrong?
thank you!

**Comment by jjjake** [comment]
http://internetarchive.readthedocs.org/en/latest/cli.html#modifying-metadata-in-bulk
http://internetarchive.readthedocs.org/en/latest/cli.html#bulk-uploading
