### ISSUE TITLE
six==1.4.1

### ISSUE THREAD

**Issue by bui** [jjjake/internetarchive#106]
this is an old version that prevents me from installing ia globally, why is it forced at this version?

**Comment by jjjake** [comment]
@bui thanks for the heads up. Others have reported the same issue to me recently. I will be reevaluating the current version requirements for the next release.

After looking at https://bitbucket.org/gutworth/six/src/1991f8b5b654f077e773f05695a08e0506b7367f/CHANGES, I think I can loosen up the version requirements for six (i.e. six>=1.4.1).

**Comment by jjjake** [comment]
This has been addressed here: https://github.com/jjjake/internetarchive/blob/master/setup.py#L24
