### ISSUE TITLE
item throws a non-obvious error from the cli, more obvious on the web

### ISSUE THREAD

**Issue by wumpus** [jjjake/internetarchive#110]
I'm trying to download a file that looks like this on the web:

> Item not available
> The item is not available due to issues with the item's content. 

So it's going to fail, right? Well, it does, but it's a bit odd:

> $ ia download WIDE-20120508085241-crawl411 WIDE-20120508091553-01390_parsed.json.gz
> WIDE-20120508085241-crawl411: e - errors
> $ echo $?
> 0

It'd be nice to have a somewhat better error message, and a non-zero exit?

**Comment by jjjake** [comment]
Thanks @wumpus. I will add a non-zero exit to the next release.

Note that the output of `ia download` was made less verbose in the last release. Use `ia download --verbose ...` or `ia download --log ...` to see more detailed information about errors.

In the new output, a character is printed for every file. A `d` is printed if a file was downloaded successfully, `e` if there were any errors, and `.` if a file is already downloaded locally and is being skipped over. ` - success` is appended to the line if all files downloaded successfully, and ` - errors` if any of the files failed to downloaded -- for easy grepping.

**Comment by jjjake** [comment]
`ia download` now exits with a non-zero status if there are any errors/failed downloads.
