### ISSUE TITLE
The help is confusing

### ISSUE THREAD

**Issue by GNUtoo** [jjjake/internetarchive#125]
The help states:
```
$ ia  help upload
Upload files to Archive.org via the Internet Archive's S3 like server API.

IA-S3 Documentation: https://archive.org/help/abouts3.txt

usage:
    ia upload [--quiet] [--debug]
              (<identifier> <file>... | <identifier> - --remote-name=<name> | <identifier> <file> --remote-name=<name> | --spreadsheet=<metadata.csv>)
              [--metadata=<key:value>...] [--header=<key:value>...] [--checksum]
              [--no-derive] [--ignore-bucket] [--size-hint=<size>]
              [--delete] [--retries=<i>] [--sleep=<i>] [--log] [--no-collection-check]
    ia upload <identifier> --status-check
    ia upload --help
```

So if I interpret it correctly, to upload a file I should do something like that:
```ia upload <identifier> <file>  [--metadata=<key:value>...]```
Expended that gives:
```
ia upload CC_1940_01_01_TheGreatDictator_IT Dictator.mkv --metadata='mediatype:"movies" title:"Charlie Chaplin: The Great Dictator" description:"The great dictator (https://en.wikipedia.org/wiki/The_Great_Dictator) in Italian" date:"1940"  year:"1940" subject:"Charlie Chaplin; Silents"  licenseurl:"http://creativecommons.org/licenses/publicdomain/"'
```
However once I run this command, when I check on archive.org, I've got only one field with the content of what is between the single quotes.

On IRC, I was pointed to the fact that I should instead use it like that:
```
ia upload CC_1940_01_01_TheGreatDictator_IT 	--metadata="mediatype:movies" \
	--metadata="title:Charlie Chaplin: The Great Dictator" \
	--metadata="description:The great dictator (https://en.wikipedia.org/wiki/The_Great_Dictator) in Italian" \
	--metadata="date:1940" \
	--metadata="year:1940" \
	--metadata="subject:Charlie Chaplin; Silents" \
	--metadata="licenseurl:http://creativecommons.org/licenses/publicdomain/" \
```
Which resulted in the correct metadata being uploaded.

As I understand it, the help should rather state something like that:
```ia upload <identifier> <file>  [--metadata=<key:value>] ...```

**Comment by jjjake** [comment]
@GNUtoo: What is the difference between the ellipses being enclosed in the brackets and outside the brackets? It looks like docopt supports either, but they both do the same thing (in docopt).

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html may be helpful... I'm unable to make complete sense of it myself, but it sounds like your assumption is correct? i.e. `utility_name [-o foo...]` allows `utility_name -o foo bar baz` and `utility_name [-o foo]... allows `utility_name -o foo -o bar -o baz`?

At any rate, I think the help menus should be updated with usage examples. This would make it clear how to provide the `--metadata` args in `ia upload`. `ia help metadata` should be updated as well.
