### ISSUE TITLE
Add support for Windows.

### ISSUE THREAD

**Issue by jjjake** [jjjake/internetarchive#126]

**Comment by arogl** [comment]
I have made 2 changes to session.py at lines 18 & 106:

18 -- Add

import platform

106 change
         uname = os.uname()
to
         uname = platform.uname()
         
Everything seems to be working.

Do you want a pull request for this?

**Comment by jjjake** [comment]
Yes, that would be great @arogl. Thanks for taking the time to look into this, I appreciate it!

**Comment by jjjake** [comment]
Fixed here: https://github.com/jjjake/internetarchive/commit/e8af7790a2ca8dd07bcc98d11db46e0b9a8272d6
