### ISSUE TITLE
Ia search always returns every file regardless of page and row param

### ISSUE THREAD

**Issue by jakeschievink** [jjjake/internetarchive#127]
I run   

   ` ia search --parameters="page:1;rows:20" "dogs"`

and the params do nothing to effect the extremely long output

this

  ` ia search --parameters="page:1;rows:20" "dogs" --num-found`

returns 

 ` 10221`

**Comment by jakeschievink** [comment]
In addition, if I use the version downloaded from pip it returns

` ia search --parameters="page:1;rows:20" "dogs"
Traceback (most recent call last):
  File "/usr/local/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/internetarchive/iacli/ia.py", line 99, in main
    ia_module.main(argv)
  File "/usr/local/lib/python2.7/site-packages/internetarchive/iacli/ia_search.py", line 37, in main
    params = dict(p.split(':') for p in args['--parameters'])
ValueError: dictionary update sequence element #0 has length 3; 2 is required `

**Comment by jjjake** [comment]
Hi @jakeschievink, the first bug was addressed in https://github.com/jjjake/internetarchive/commit/5777d504e0cb51bd0bcc457e8fbc80f04c14bf07, and parsing of `--parameters` values was made more flexible in https://github.com/jjjake/internetarchive/commit/b69720b7a67bcda8748891f6545d68c89ba6d8f0.

I'm guessing you're on v0.9.8 if you installed via pip. I'm waiting for a new feature to our search API, and then I'll release v1.0.0 (on pypi).

To get the latest version, you could simply use a binary:

```
» curl -LOs https://archive.org/download/ia-pex/ia
» chmod +x ia
» ./ia -v
1.0.0.dev12
» ./ia search --parameters="page:1;rows:1" "dogs"
{"week": "0", "description": "Slide show of our dogs. (Requires QuickTime 7) Music: http://www.opsound.org/opsound/pool/gettarr.html", "format": ["512Kb MPEG4", "Animated GIF", "Archive BitTorrent", "Metadata", "Ogg Video", "Thumbnail", "jpeg", "quicktime"], "downloads": "573", "title": "Dogs", "mediatype": "movies", "collection": ["ourmedia", "fav-msalwen", "fav-nizucchi"], "month": "7", "oai_updatedate": ["2005-05-16T02:59:58Z", "2014-03-30T21:46:43Z"], "identifier": "Dogs", "publicdate": "2005-05-16T02:59:58Z"}
» 
```


My apologies for the confusion, and thanks for taking the time to report the issue. : )
