### ISSUE TITLE
Clarify documentation of a couple things

### ISSUE THREAD

**Issue by ethus3h** [jjjake/internetarchive#128]
In `ia upload --help`, it says: 

```
    -R, --retries=<i>                 Number of times to retry request if S3
                                      retruns a 503 SlowDown error.
```

It appears in the code at https://github.com/jjjake/internetarchive/blob/e3c9540942768f6f78eaedbb28e0dce2359128ee/internetarchive/session.py#L115 that the following would be more helpful:
```
    -R, --retries=<i>                 Number of times to retry request if S3
                                      indicates a temporary error.
```

In `ia help`, it says:

```
See 'ia help <command>' for more information on a specific command.
```

The correct format is `ia <command> --help`. The documentation and the application behavior should match.

Thanks! :)

**Comment by jjjake** [comment]
I think the documentation is more clear and accurate as it is because it specifies exactly which error `--retries=<i>` will retry on.

Both `ia <command> --help` and `ia help <command>` are valid in the latest version of the code.

Thanks for your input @ethus3h, I appreciate it.

**Comment by ethus3h** [comment]
Hello again! Ah, I must be running an old version, good to know, thanks!
I thought --retries retried on other errors than 503, though?

**Comment by ethus3h** [comment]
Also, thanks for the awesome app!

**Comment by ethus3h** [comment]
(Also, anyway it might be nice to fix the typo at https://github.com/jjjake/internetarchive/blob/c13d99367698a54018613cc56e2ab90d52696455/internetarchive/cli/ia_upload.py#L26 ("retruns" for "returns")).

**Comment by jjjake** [comment]
@ethus3h See here: https://github.com/jjjake/internetarchive/blob/master/internetarchive/item.py#L551

As of right now, requests to S3 only retry on 503s. It might make more sense to retry on other status codes as well, I'll think about this.

Most other types of requests (to the Metadata API, /download/, etc.) use the `urllib3.Retry` class: https://github.com/jjjake/internetarchive/blob/c13d99367698a54018613cc56e2ab90d52696455/internetarchive/session.py#L112

And, thanks for the heads up on the typo! Fixed: https://github.com/jjjake/internetarchive/blob/c13d99367698a54018613cc56e2ab90d52696455/internetarchive/session.py#L112

Thanks again @ethus3h!

**Comment by ethus3h** [comment]
Aah, I see. I get a *lot* of 500s, which seem to be temporary, so I set the --retries parameter in my script thinking that would fix the issue. I guess I won't see the effect I was hoping for :P

(My incorrect assumption, based on searching for "retries" in the code, had been that this https://github.com/jjjake/internetarchive/blob/c13d99367698a54018613cc56e2ab90d52696455/internetarchive/session.py#L121 was the list of status codes that it applied to.)

I would be happy to see retries on 500s though, for what it's worth. :)

Thanks again!

**Comment by brandongalbraith** [comment]
Don't forget exponential backoff for requests to S3! http://docs.aws.amazon.com/general/latest/gr/api-retries.html
