### ISSUE TITLE
MemoryError on spreadsheet upload

### ISSUE THREAD

**Issue by stephenrparsons** [jjjake/internetarchive#129]
When uploading 31 files from a .csv, of at most 32K each (and mostly .jpgs), after 28 of them I always get:

```
Traceback (most recent call last):
  File "/usr/local/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==1.0.0', 'console_scripts', 'ia')()
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/cli/ia.py", line 131, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/cli/ia_upload.py", line 192, in main
    responses += r
MemoryError
```

I am perplexed by this as each file is quite small and there are not so many of them.

Python 2.7.6, internetarchive 1.0.0, Ubuntu 14.04 (64-bit)

**Comment by jjjake** [comment]
@stephenrparsons can you send me a copy of your spreadsheet (jake at archive.org)?

**Comment by stephenrparsons** [comment]
I believe I sent to you, let me know if you need anything else.

**Comment by jjjake** [comment]
I got it, thanks @stephenrparsons. I'll follow up here once I am able to take a closer look.

Thanks for reporting the issue! : )

**Comment by jjjake** [comment]
Alright @stephenrparsons, this issue should now be resolved. I had a few hiccups before resolving this, but as of https://github.com/jjjake/internetarchive/commit/eca4d0fd1c0e6b069029107d0b1420a38169c4e1 everything should be working correctly.

As a side note, `internetarchvie.cli.ia_upload` should be refactored. It's unnecessarily complicated as is.

**Comment by stephenrparsons** [comment]
Fixed for me - thanks so much, Jake!

**Comment by jjjake** [comment]
Awesome, great to hear!

FYI, v1.0.1 is now on pypi as well.
