### ISSUE TITLE
Metadata seems to be broken after updating

### ISSUE THREAD

**Issue by ethus3h** [jjjake/internetarchive#130]
Hi, I just updated from version 0.8.something to 1.0.0, and now commands generated by

```
ia upload "$CrystalID" --retries=10 --metadata="subject:Uploaded using Crystallise $crystalliseVersion; Crystallise log; log; logs; 1EA21BD8-DB7E-11E5-9733-728C37852114; $crystalTitle" --metadata="collection:$crystalCollection" --delete ./"$CrystalID".coal5-log
```
give an error:

```
--metadata must be formatted as --metadata="key:value"
usage:
    ia upload <identifier> <file>... [options]...
    ia upload <identifier> - --remote-name=<name> [options]...
    ia upload <identifier> <file> --remote-name=<name> [options]...
    ia upload --spreadsheet=<metadata.csv> [options]...
    ia upload <identifier> --status-check
    ia upload --help
```

I think the commands are correctly written? Thanks :)

**Comment by ethus3h** [comment]
The problem does not occur with ia 0.9.8 installed via pip.

**Comment by jjjake** [comment]
Thanks again for reporting @ethus3h.

I just fixed this in https://github.com/jjjake/internetarchive/commit/1d43dc088695af9486c5d8a11066ed1a7fd02026. The fix is available in v1.0.1, which I just shipped.

This was caused by changes in b69720b7a67bcda8748891f6545d68c89ba6d8f0.

Please let me know if you run into any issues.

**Comment by ethus3h** [comment]
Oh, awesome, thanks! :) I'll let you know if there are problems :)

**Comment by ethus3h** [comment]
Does it require a different syntax now? I'm still getting the error `--metadata must be formatted as --metadata="key:value"`....

**Comment by ethus3h** [comment]
I changed it to not use the semicolon-delimited syntax, but I'm still getting the error using this format:

```
ia upload "$CrystalID" --retries=10 --metadata="subject:Uploaded using Crystallise $crystalliseVersion" --metadata="subject:Crystallise log" --metadata="subject:log" --metadata="subject:logs" --metadata="subject:1EA21BD8-DB7E-11E5-9733-728C37852114" --metadata="subject:$crystalTitle" --metadata="collection:$crystalCollection" --delete ./"$CrystalID".coal5-log
```

**Comment by ethus3h** [comment]
FWIW, it's working fine now after removing the .s from my identifier and updating to 1.0.2. :) Thanks!
