### ISSUE TITLE
Search functionality broken. Documentation example no longer works.

### ISSUE THREAD

**Issue by kamal94** [jjjake/internetarchive#132]
After 56c8e14, the search.Search(query) method does not work. I suppose this is due to the addition of the session parameter. I am unsure how to use the search.Search method anymore, and perhaps the documentation for that file should be updated. 

The suggested following usage no longer works:

``` 
        >>> import internetarchive.search
        >>> search = internetarchive.search.Search('(uploader:jake@archive.org)')
        >>> for result in search:
        ...     print(result['identifier'])

**Comment by jjjake** [comment]
Thanks for reporting the issue, @kamal94.

I've updated the docstring in https://github.com/jjjake/internetarchive/commit/48f9ee0572140fe8aefdc403ef0ae3e04c24e172.

However, I would recommend using the API:

```
>>> from internetarchive import search_items
>>> for result in search_items('(uploader:jake@archive.org)'):
...     print(result['identifier'])
```

**Comment by kamal94** [comment]
Thank you! Yes I checked the documentation after I got the error but wasn't sure which implementation I should be following. Will take your advice on that one. Thank you for the quick handling!
