### ISSUE TITLE
Not Reuploading Duplicate Items

### ISSUE THREAD

**Issue by dkl3** [jjjake/internetarchive#133]
Hi, how exactly do I not reupload duplicate items from a directory if it's already on the Internet Archive? The reason I ask of is because what if, for instance, I want to upload new files to a collection, say an update of a YouTube channel?

If I learned what to do, this would save me time and not overload the server (giving me 503 errors).

It would mean a lot if I knew what to do.

**Comment by jjjake** [comment]
Hi @dkl3,

You'll want to use the checksum option. When the checksum option is turned on, an md5 checksum is generated of your local file and nothing is uploaded if a file with the same checksum already exists in the given item. Do note that this will not work if the item has pending tasks. This behavior is to avoid race conditions (i.e. if a file with a matching checksum existed in the item, but there was a task queued to delete that file, etc.).

In the CLI, this would like: 

```
$ ia upload <identifier> <file> --checksum
```

And, in Python:

```
>>> from internetarchive import upload
>>> r = upload('<identifier>', '<file>', checksum=True)
```

Another option is to use the delete option. When this option is turned on, your local files are deleted after they have been successful uploaded to archive.org. Of course, this only an option if you are in a position where deleting your local copies is an option. Anyways, using delete would look like:

```
$ ia upload <identifier> <file> --delete
```

And, in Python:

```
>>> from internetarchive import upload
>>> r = upload('<identifier>', '<file>', delete=True)
```

If you're running into a lot of 503 errors, you might find the retries parameter helpful (requests are retried for the specified amount of times when 5xx errors are encountered):

```
$ ia upload <identifier> <file> --retries 10
```

And, in Python:

```
>>> from internetarchive import upload
>>> r = upload('<identifier>', '<file>', retries=10)
```

Please email me at jake at archive.org if you have any more support questions, happy to help! : )
