### ISSUE TITLE
Search sorts functionality by downloads/views flipped?

### ISSUE THREAD

**Issue by kamal94** [jjjake/internetarchive#140]
This is something that has a 50% chance of being me understanding ia sorting incorrectly, but if I'm correct then there might be an opposite order to sorting returned by the internet archive python search utility.

When I implement 
```
for r in ia.search_items('"michigan water"', params=dict(size=1000), sorts=dict(downloads="desc")):
...     print(r['identifier'])
```

I get the abridged ID lists:

CSPAN2_20160316_000200_Hearing_on_Flint_Michigan_Water_Contamination
CSPAN2_20160316_061300_Hearing_on_Flint_Michigan_Water_Contamination
CSPAN3_20160317_130000_Hearing_on_Flint_Michigan_Water_Contamination
CSPAN_20160318_012900_Hearing_on_Flint_Michigan_Water_Contamination
CSPAN_20160320_190900_Hearing_on_Flint_Michigan_Water_Contamination
CAT93992744
CSPAN3_20160317_090500_Hearing_on_Flint_Michigan_Water_Contamination
.
.
.
4738083.0001.001.umich.edu
MediaMonarchyEpisode174
4738059.0001.001.umich.edu
projectedeffects00unit

according to [this search](https://archive.org/search.php?query=%22michigan+water%22&sort=-downloads) and [that search](https://archive.org/advancedsearch.php?q=%22michigan+water%22&fl%5B%5D=identifier&sort%5B%5D=downloads+desc&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json&callback=callback&save=yes), the last ID is actually the most downloaded/viewed one. So am i simply confusing what it means for a list of items to be sorted in descending order based on views? Does that not mean that the first item returned is the most viewed, and the last is the last viewed?

If so, then the list should begin with 

projectedeffects00unit
4738059.0001.001.umich.edu
MediaMonarchyEpisode174
.
.
.
CSPAN3_20160317_130000_Hearing_on_Flint_Michigan_Water_Contamination
CSPAN2_20160316_000200_Hearing_on_Flint_Michigan_Water_Contamination
CSPAN2_20160316_061300_Hearing_on_Flint_Michigan_Water_Contamination

**Comment by kamal94** [comment]
It turns out that even after i set sorts to 'asc', it gives me the same output. Perhaps I am not putting it in the correct format?

**Comment by willf** [comment]
Try: `for r in ia.search_items('"michigan water"', params=dict(size=1000), sorts=['downloads desc']):`

**Comment by willf** [comment]
Notice that it is a `list` of `string` where each string is `field asc|desc`

**Comment by kamal94** [comment]
Yes that worked! Thank you. Perhaps specify that it needs to be a list of strings in the documentation? I assumed it was a dictionary because #136 passed a dictionary to params. Though now that I look at [search.py](https://github.com/jjjake/internetarchive/blob/master/internetarchive/search.py) I can see that it is checked against a list type.
