### ISSUE TITLE
local variable 'insecure' referenced before assignment

### ISSUE THREAD

**Issue by uoslibraries** [jjjake/internetarchive#141]
Hi, 
line 347 of session.py can raise an UnboundLocalError: local variable 'insecure' referenced before assignment

This is because the variable "w" on line 340 can evaluate to True but not contain a match in the "insecure_warnings" list. The "insecure" variable never gets the value True but also never gets the value False since it's in an if...else.

A solution might be to set "insecure" to False then allow it to get the value True if the condition is met.

Matt

**Comment by jjjake** [comment]
Thanks for reporting Matt, this should be fixed now.
