### ISSUE TITLE
Support Archiving Live URL

### ISSUE THREAD

**Issue by brandongalbraith** [jjjake/internetarchive#143]
@jjjake 

Would you be up for merging a PR that supported performing an archive request for `<url>` via GET `https://web.archive.org/save/<url>`? Idea obtained via https://news.ycombinator.com/item?id=11626044

> Alas there's no formal save-page-now API, but if you experiment with using it from a browser, it's not hard to call from a program: fetch https://web.archive.org/save/<url>. The return is html, but if you examine the headers you get back, you'll see that Content-Location: tells you the permanent archived name of that particular capture.

If so, I'll provide a PR!

**Comment by wumpus** [comment]
I actually gave incomplete instructions, it would need to loop over the urls in the returned html page and call /save/ on them, too... so it's a bit more work, still not too bad. I'll see if I can get a yea or nay from the Wayback director...

**Comment by brandongalbraith** [comment]
@wumpus Much obliged! If not, no worries, I have an ArchiveBot instance I can use for long term cold storage until a future TBD date (for Wayback ingestion).

**Comment by wumpus** [comment]
I had a chat with Mark Graham (the manager of All Things Wayback), and he thinks it's a great idea to add to this tool, but not yet. (Kind of like St. Augustine!)

We're very comfortable with ArchiveTeam/ArchiveBot, you can ingest WARCs through their usual process early and often!

**Comment by brandongalbraith** [comment]
Awesome! I appreciate the consideration!

**Comment by jjjake** [comment]
Thanks a lot for suggesting the idea @brandongalbraith, I appreciate it. I'll ping you when we do decide to move forward with this.

Thanks for following up as well @wumpus.

**Comment by brandongalbraith** [comment]
Closing as https://github.com/pastpages/savepagenow is available for similar purpose.

**Comment by InnovativeInventor** [comment]
Just adding this for anybody else who sees this page. [archivenow](https://github.com/oduwsdl/archivenow) also provides a similar service, but allows you to push to other archiving sites.
