### ISSUE TITLE
Parameters and Sorts are not accepted together in search term

### ISSUE THREAD

**Issue by kamal94** [jjjake/internetarchive#144]
```
i = 0
for r in ia.search_items('publicdate:2016-05-03 AND mediatype:movies', sorts=["downloads desc"]):
    i+=1
 
i
    1186
j = 0
for r in ia.search_items('publicdate:2016-05-03 AND mediatype:movies', params=dict(size=1000)):
    j+=1

j
1186
k = 0
for r in ia.search_items('publicdate:2016-05-03 AND mediatype:movies', params=dict(size=1000), sorts=["downloads desc"]):
    k+=1

(this takes infinitely long)
```

It seems that sorts and params can't be used together.

**Comment by jjjake** [comment]
Thanks again for the report @kamal94, always appreciated.

What version are you using? I'm unable to replicate this issue with your code above using v1.0.2 (the most current released version) or using the current master branch on github. All three of those searches finish within a couple of seconds for me (I'm currently on a very slow network as well).

Perhaps it was a transient issue? Please let me know if you're still experiencing this issue, and send me any further details you can provide (particularly the version of `internetarchive` you are using, and what version of Python as well).

**Comment by kamal94** [comment]
Thank you @jjjake ! 

It seems to work just fine now. Not sure why it didn't work before.
