### ISSUE TITLE
Feature: Auth should use .netrc instead of a .cfg

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#154]
- There should be a module to handle this (there was with perl when I was using it to beef up a script I used for a while) that gives .netrc that can be pulled on install after the change is made.
- If no .netrc exists, create one and set perms to 600, insert auth.
- Don't use flags to do this, use the inbuilt prompts that don't leave traces in the bash history
- Might be an issue if someones using Cygwin, though I don't know because I run all Linux.

**Comment by jjjake** [comment]
@vxbinaca We're still going to want to want a config specifically for `ia`, but I added support for using a .netrc file to configure `ia`.

For example:

```ia configure --netrc```

That simply uses `netrc.netrc()`. It doesn't support pointing to specific files, but feel free to add that if you would find it useful. Also note that the Python `netrc` module does not support spaces in `password`. It's a known issue, but doesn't seem to have been resolved yet.

**Comment by vxbinaca** [comment]
I'll hold off using it until they fix that. I only brought it up because it's a unix standard way of insecure storage and parsing of credentials. Some of us use shell boxes and on a multi-user setup......eh it's the box admins fault for not setting 600 or 700 on each user directory.

Thanks. Also, I have questions about deriving. Who do I direct them to? If it's you I'll just email you.

**Comment by jjjake** [comment]
@vxbinaca you can email me. I'll direct it elsewhere if needed.

BTW, here's the issue if you'd like to follow (looks like it's awaiting review): https://github.com/python/cpython/pull/127
