### ISSUE TITLE
Unable to initialize internetarchive.Item when only identifier is provided

### ISSUE THREAD

**Issue by Hydriz** [jjjake/internetarchive#155]
Since version 1.0.0, `internetarchive.Item` required not only the identifier, but a new mandatory parameter `archive_session`, which causes problems as the user does not have easy access to the ArchiveSession class (at least from what I can see in the docs).

Following the [example given in the docs](http://internetarchive.readthedocs.io/en/latest/internetarchive.html#internetarchive.Item), I get:

<pre>
hydriz@dumps-3:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import internetarchive
>>> item = internetarchive.Item('wikimediadownloads')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes at least 3 arguments (2 given)
</pre>

The `archive_session` parameter should be made optional and the session should be declared from within the function, just like how it was done for 0.9.8. If not, I believe the documentation should be updated so that users know how to make use of this new parameter.

Note: This was tested on version 1.0.8, but it is likely that this issue occurred since version 1.0.0.

**Comment by jjjake** [comment]
Thanks for the report @Hydriz!

As of 1.0.0, the `Item` object should generally not be used directly. `internetarchive.get_item()` should be used instead.

If you do use the `Item` object directly, you'll need to call `Item` with the following parameters:

```
>>> Item(archive_session, identifier, item_metadata)
```

I've updated the docstring to recommend using `get_item()`.
