### ISSUE TITLE
How to specify a license when uploading items through a CSV?

### ISSUE THREAD

**Issue by Asparagirl** [jjjake/internetarchive#157]
When using ia to upload a lot of files (and their associated metadata) to the Internet Archive through a CSV, what are all the potentially-acceptable values we should be using for the field "licenseurl"?

For example, setting this field to the exact text "Public Domain Mark 1.0" (without the quotation marks) does not work.  While those words will display on the uploaded item, they do not hyperlink to http://creativecommons.org/publicdomain/mark/1.0/ and they don't display the proper Creative Commons or Public Domain iconography next to the words either.

**Comment by jjjake** [comment]
@Asparagirl You should use the URL to the license rather than the name of the license:

```
$ ia metadata <id> --modify='licenseurl:http://creativecommons.org/publicdomain/mark/1.0/'
```

I've marked this as a bug, as this should be documented in the documentation.

Thanks for opening the issue @Asparagirl!

**Comment by Asparagirl** [comment]
Happy to complain!...er, I mean, happy to help!  :-)

**Comment by Asparagirl** [comment]
This bug just became slightly more important, because the IA web interface's metadata editor screen no longer allows you to choose a public domain license for an item.  (The link to the Creative Commons web page currently linked by "dedicate to the public domain" is broken.)

**Comment by tim-moody** [comment]
ia metadata iiab-test-file-17-10-15-9a --modify='licenseurl:http%3A//creativecommons.org/licenses/by-sa/4.0/'

returns

error (400): Metadata field 'licenseurl' with value 'http%3A//creativecommons.org/licenses/by-sa/4.0/' doesn't match required pattern '=^http://creativecommons.org/(licenses|publicdomain)/='

what does this mean and what is the proper syntax?

**Comment by tim-moody** [comment]
sorry. I thought this failed, but now it works
ia metadata iiab-test-file-17-10-15-9a --modify='licenseurl:http://creativecommons.org/licenses/by-sa/4.0/'
