### ISSUE TITLE
Searches fail with ValueError: Invalid user or user secret.

### ISSUE THREAD

**Issue by reuben** [jjjake/internetarchive#158]
It seems like all operations, even read-only ones, fail if you don't run `ia configure`. I'm not sure if it's the tool or the documentation that is wrong…

    $ python3
    Python 3.5.2 (default, Jul 28 2016, 21:28:00)
    [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import internetarchive as ia
    >>> search = ia.search_items("collection:librivoxaudio")
    >>> import itertools
    >>> for result in itertools.islice(search, 10):
    ...     print(result)
    ...
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.5/site-packages/internetarchive/search.py", line 202, in __next__
        return self.iterator.__next__()
      File "/usr/local/lib/python3.5/site-packages/internetarchive/search.py", line 133, in _scrape
        self._handle_scrape_error(j)
      File "/usr/local/lib/python3.5/site-packages/internetarchive/search.py", line 167, in _handle_scrape_error
        "and retrying.".format(j['error']))
    ValueError: Invalid user or user secret. Try running 'ia configure' and retrying.
    >>>

**Comment by saper** [comment]
Yes, you need `ia configure` to be run before you can start using `ia`.

**Comment by reuben** [comment]
Ah, damn, somehow I missed the mention of "searching" in the list of operations that require authentication in https://internetarchive.readthedocs.io/en/latest/api.html

**Comment by jjjake** [comment]
Thanks @saper. : )

@reuben: Sorry if that error wasn't the most helpful. Please let me know if you have any feedback on improving it!

**Comment by reuben** [comment]
The problem was just me assuming that search operations wouldn't need authentication and then reading the docs too quickly, the error is okay IMO. Thanks for the help!
