### ISSUE TITLE
change / update item collection

### ISSUE THREAD

**Issue by ekansa** [jjjake/internetarchive#166]
Hi 

I'm hitting a brick wall trying to specify that my item belongs to "opensource_media". Here's the item:
https://archive.org/details/opencontext-97-burmese-001-a-03

Relevant bits of Python are:

```
item_id = 'opencontext-97-burmese-001-a-03'
item = get_item(item_id, archive_session=s)
r = item.modify_metadata(dict(collection='opensource_media', mediatype='image'))
```

But I always get a 400 error response. What am I doing wrong? I can edit other metadata and upload files just fine, but changing collections seems not to work. If I can't change the collection of an item after it is created, how do a create a new item into the collection of my choice?

Thanks!
-Eric

**Comment by ekansa** [comment]
Hi. I talked to someone else at the Internet Archive, so it seems I can't change the collection for an item. So how do I (using Python) specify that an item I create belongs to the 'opensource_media' collection?

THANKS!
-Eric

**Comment by jjjake** [comment]
@ekansa You will simply need to specify the collection at time of item creation (i.e. during upload of the first file):

    >>> from internetarchive import get_item
    >>> item = get_item('<identifier>')
    >>> r = item.upload('file.txt', metadata=dict(collection='opensource_media', mediatype='texts'))

Does that make sense? Please let me know if you run into any issues.

**Comment by ekansa** [comment]
Thanks! Makes sense and it works. I'm uploading images to the opensource_media now!
-Eric
