### ISSUE TITLE
Identifiers creation rules

### ISSUE THREAD

**Issue by annelhote** [jjjake/internetarchive#169]
Are there really no official restrictions or rules about the identifiers ? 
http://internetarchive.readthedocs.io/en/latest/metadata.html#archive-org-identifiers

When trying to create an item with identifier "aa", an error 400 is returned by the API but I can't find any "aa" item on archive.org :
https://archive.org/details/aa

Thanks

**Comment by jjjake** [comment]
@annelhote it really depends on what API or interface you're using to upload to.

This library uses the Internet Archive S3-like API which requires that identifiers be between 3 and 100 characters.

I would recommend sticking to the suggestion of keeping archive.org identifiers between 5 and 80 characters.

I think the documentation could be updated to be more clear, but you shouldn't run into any issues following the suggestions on that page:

```An identifier is composed of any unique combination of alphanumeric characters, underscore (_) and dash (-). While there are no official limits it is strongly suggested that identifiers be between 5 and 80 characters in length.```

**Comment by annelhote** [comment]
Thank you !
