### ISSUE TITLE
Improve error message for IA-S3 500 error's

### ISSUE THREAD

**Issue by jjjake** [jjjake/internetarchive#171]
Normally when IA-S3 fails, an XML formatted error message is returned in the response content. However, this is not the case for 500 errors (possibly others). Right now, `ia` simply fails with a xml.parsers.expat.ExpatError exception. This should be updated to be more clear about what's going on.

500 error's are usually either transient or require IA admin intervention to resolve. The error message should reflect this.

See #170 for an example of this issue.

**Comment by antonizoon** [comment]
Awesome, thanks. This error is particularly a problem since it just crashes ia and overrides `--retries`, preventing me from telling it to try again.

**Comment by dkl3** [comment]
I support a fix of this as well
