### ISSUE TITLE
ia upload from stdin accepts data faster than it uploads

### ISSUE THREAD

**Issue by ethus3h** [jjjake/internetarchive#173]
Consider a script like the following:
```
tar -cv 100MegabyteFolder | pv -ps "100M" | ia upload identifier - --remote-name="100MegabyteFolder.tar"
```
The progress bar shown by `pv` will be wrong (it will indicate completion prematurely) when uploading using a slow Internet connection, because ia upload accepts the input from stdin faster than it uploads.

**Comment by ethus3h** [comment]
It appears that this is because [it first writes the standard input to a file](https://github.com/jjjake/internetarchive/blob/master/internetarchive/cli/ia_upload.py#L195), thus entirely defeating the purpose of uploading via standard input…

**Comment by Vineet1003** [comment]
can you elaboratea little .. didnt got u

**Comment by ethus3h** [comment]
Uploading data through standard input requires enough disk space to store the entire stream while it is being uploaded, and the upload does not begin until the stream is stored in its entirety locally. This causes two issues:
- Data cannot be uploaded through standard input if there is not enough local disk space to hold it in its entirety
- Data cannot be uploaded and created in parallel, making the process take longer (e.g. downloading a file from the Web and uploading it using `ia upload` will wait for the download to complete before the upload will begin)
The solution to this, I think, is to use the [multipart upload API](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html) instead.
Does this answer your question?

**Comment by jjjake** [comment]
Thanks for taking the time to create this issue @ethus3h. Unfortunately at the moment IA-S3 requires a Content-Length header, and does not support chunked transfer encoding. So, even if the user was able to provide a Content-Length header, the content would still need to be downloaded locally first.

There has been talk about adding support for this to IA-S3, but no plans to do so. If we ever add support for this, I would love to improve the support for uploading from stdin. I agree that it might not be the most useful feature as it stands right now.

**Comment by ethus3h** [comment]
Aaaahhh, I guess that's why I was having such a hard time getting my own implementation of the multipart uploading to work. They should probably update [the API documentation](http://archive.org/help/abouts3.txt), because it claims to support multipart uploads.

**Comment by jjjake** [comment]
@ethus3h we do support multipart uploads, just not chunked transfer encoding. The parts have to be uploaded in individual requests.

Have you tried using boto? It's been a while, but I've had good experiences with using it with IA-S3 in the past for multipart uploads. I'm happy to help you troubleshoot this. Feel free to email me if that's easier.

Out of curiosity, why are you interested in using multipart uploads with IA-S3? In the archive.org IA-S3, the only real benefit of using multipart uploads is for resuming very large uploads. No doubt a very good reason, but it doesn't have all the same benefits that multipart uploads have with Amazon's S3 just to be clear. It can actually make for a slower ingest, depending on the scenario.

**Comment by ethus3h** [comment]
I have a script that tars up and compresses files, then uploads them... I'd like to upload in parallel to tarring (prevents knowing the content-length) to make the process faster and to prevent disk space being needed for a temp file.

I didn't realize multipart and chunked were different things...

Thanks for your info!
