### ISSUE TITLE
Using --spreadsheet=file.csv subject fields are not cleared per item

### ISSUE THREAD

**Issue by davmo** [jjjake/internetarchive#179]
I use `--spreadsheet` mode. My metadata files contain `subject[x]` fields populated from tags. The number of tags per item varies so some subject fields may be blank.

If an item with 8 tags is followed by one with 5, the second item is uploaded with the blanks filled in from the previous one.  Here's a representation of a subset of the data (it's really CSV):
```
identifier: hpr2198
subject[0]: guix
subject[1]: linux
subject[2]: sysadmin
subject[3]: os
subject[4]: package management
subject[5]: nix
subject[6]: scheme
subject[7]: guile

identifier: hpr2199
subject[0]: DIY
subject[1]: cars
subject[2]: car repair
subject[3]: automotive
subject[4]: 
subject[5]: 
subject[6]: 
subject[7]: 
```

If you look at https://archive.org/details/hpr2199 you'll see it has tags that 'bled through' from the previous item.

I used to use the same format CSV files successfully with `ias3upload.pl`, so I'm hoping it's not my data!

**Comment by davmo** [comment]
Hi @jjjake. Please let me know if you'd like me to clarify this problem, which is still causing me grief. Here's an updated definition of what's happening.

I just processed hpr2308-hpr3210. These three episodes contain subjects (topics):
```
hpr2308: guix, linux, nix, sysadmin, development
hpr2309: Accessibility, scripting, audio editing, speech-to-text
hpr2310: Kdenlive, opensource.com, workflow
```

After upload subjects have "bled" over:
```
hpr2309: Accessibility, scripting, audio editing, speech-to-text, development
hpr2310: Kdenlive, opensource.com, workflow, speech-to-text, development
```
It's as if the same internal structure is being used between spreadsheet rows and is not being cleared between iterations.

I have been cleaning these problems up by feeding a modified version of the same CSV file to `ias3upload.pl` which correctly interprets the subject fields.

I will leave these few uploads in their 'broken' state for a week to demonstrate the problem.

**Comment by jjjake** [comment]
Thanks again for the report @davmo. This looks like a bug, sounds like your data is fine!

I'll take a closer look this week, and follow up here.

**Comment by davmo** [comment]
Cool, thanks!

**Comment by jjjake** [comment]
https://github.com/jjjake/internetarchive/commit/1ed7a8fca452b07c0bfb46c4b4dd1423eaeb656e should fix this @davmo. The previous csv unicode bug fix, and this fix, are now in master. You should be able to try out these changes by installing `ia` from the master branch:

    pip install 'git+https://github.com/jjjake/internetarchive.git

`ia -v` should output `1.6.0.dev7`. Can you confirm this solves the issue for you when you have a chance?

I think I'll work on shipping v1.6.0 if this works for you. Thanks again davmo! : )

**Comment by davmo** [comment]
Got it, thanks @jjjake.

Should this change also affect `ia metadata`? My tests seem to show that it doesn't. I reapplied the data to the previously uploaded hpr2308-hpr2310 and the "leaked" subjects were not removed.

I don't have any items to upload at this moment, but I will prepare some shortly and will report back once I have tried them.

**Comment by jjjake** [comment]
It doesn't. I will work on that next (pulling in both of the recent bug fixes to `ia upload --spreadsheet` into `ia metadata --spreadsheet`).

**Comment by davmo** [comment]
Success (slightly qualified I'm afraid).

I uploaded four items with different numbers of subjects and there was no "leaking" between the first three.

Unfortunately the upload failed during the fourth, though I don't doubt this is another issue entirely.

```
$ ia upload --retries=3 --spreadsheet=metadata_0996-0999.csv
hpr0996:
 uploading hpr0996.mp3: [################################] 3/3 - 00:00:00
hpr0997:
 uploading hpr0997.mp3: [################################] 16/16 - 00:00:03
hpr0998:
 uploading hpr0998.mp3: [################################] 17/17 - 00:00:01
hpr0999:
Traceback (most recent call last):                       ] 0/13 - 00:00:00
  File "/usr/bin/ia", line 9, in <module>
    load_entry_point('internetarchive==1.6.0.dev7', 'console_scripts', 'ia')()
  File "/usr/lib/python2.7/site-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/lib/python2.7/site-packages/internetarchive/cli/ia_upload.py", line 241, in main
    session)
  File "/usr/lib/python2.7/site-packages/internetarchive/cli/ia_upload.py", line 80, in _upload_files
    response = item.upload(files, **upload_kwargs)
  File "/usr/lib/python2.7/site-packages/internetarchive/item.py", line 830, in upload
    request_kwargs=request_kwargs)
  File "/usr/lib/python2.7/site-packages/internetarchive/item.py", line 690, in upload_file
    **request_kwargs)
  File "/usr/lib/python2.7/site-packages/internetarchive/session.py", line 346, in send
    r = super(ArchiveSession, self).send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))
 uploading hpr0999.mp3: [################################] 0/13 - 00:00:00
```

**Comment by jjjake** [comment]
If that `Broken pipe` error isn't transient, I think it might be related to #179. Let's move the conversation to that issue if it's not transient.

**Comment by jjjake** [comment]
Alright @davmo, the unicode bug fix has been added to `ia metadata --spreadsheet`: https://github.com/jjjake/internetarchive/commit/94d516246ae6e6de7f01d9cbb33b66ce187584c7

However, `ia metadata` does not have the same issue as `ia upload` does with carrying over metadata values from previous fields (at least I'm not able to replicate it). If you rerun `ia metadata --spreadsheet`, using the same spreadsheet and having indexed fields (e.g. `subject[1]`), it will re-insert -- not clobber -- the values on the spreadsheet to the specified index. Does that make sense? I understand how this might be confusing, but I wouldn't consider it a bug. I would love to hear your feedback, if you think this should behavior should be different. Please open up a new issue, if you have feedback on this.

Thanks again @davmo!

**Comment by davmo** [comment]
OK. I successfully uploaded hpr0999 by using a single-item CSV file. So there's nothing inherently wrong with that row of the data.

I did this in the assumption that `ia` would fail if I retried the batch of 4. Now I think of it I may have made the wrong choice there since if the problem is to do with interactions within a multi-line spreadsheet, this was not a useful test. If that's so then apologies for not thinking it through!

Our community podcast generates 5 episodes per week and I upload the 5 each weekend. I will try that batch and report back, retrying the entire batch in case of a `broken pipe` error.

I'm also working backwards through the historical episodes, so can try more of them. However, they usually require more work to prepare. If I can get a batch together earlier than the weekend I'll use it for testing and report the outcome.

Thanks for your efforts @jjjake

**Comment by jjjake** [comment]
Look forward to the test on the new batch (though, I'm pretty sure the fix works, it will still be helpful).

FYI, if you were to rerun `ia upload --spreadsheet` after the items were already uploaded, nothing bad would happen. Your files would be clobbered with the same files. Metadata is also only meaningful in `ia upload` on item creation (i.e. on the first upload). After that it is ignored, and `ia metadata` must be used (this has a lot to do with the underlying APIs. In the future, it might make sense to work around this in the `ia` client and update the metadata in every `ia upload` request. That's not currently the case, though). So, yes, a proper test will need to be done with a fresh set of uploads. No rush or worries if you're not able to, feedback is nice though.

Thanks again.

**Comment by davmo** [comment]
Uploading this weekend's batch of episodes worked fine as far as the leaking through of `subject` fields is concerned.
Thanks for fixing this bug!
