### ISSUE TITLE
Format filter is ignored when downloading with --glob

### ISSUE THREAD

**Issue by matthazinski** [jjjake/internetarchive#180]
I have a bunch of items I'd like to download filtering by both extension and filename.  When I run "ia download" and specify both `--glob="*foo*"` and `--format='Flac'`, the format filter is ignored. 

This seems to be the issue: https://github.com/jjjake/internetarchive/blob/master/internetarchive/item.py#L339

It's easy to work around this limitation because the filenames all end in ".flac", but I can't find any mention in the docs that this is expected behavior.

**Comment by learning-more** [comment]
@matthazinski, if you add more parameters to your --format string, are both the glob and format parameters accepted? The example shown seems to list the specific details of the mp3 format:

> ia download TripDown1905 --format='512Kb MPEG4'

If you add additional detailed format information to --format, does it work?

**Comment by jjjake** [comment]
Thanks @matthazinski. I think this is a documentation issue. I'm having trouble imagining a scenario where it would be essential to filter by both format and glob pattern. Please give some examples of where this would be useful if you have any.

Thanks again.
