### ISSUE TITLE
ia `tasks` uses http, not https, regardless of the setting of `secure`

### ISSUE THREAD

**Issue by p8NG6L** [jjjake/internetarchive#181]
This code in catalog.py has hardcoded http URLs.

https://github.com/jjjake/internetarchive/blob/5129eefb7ae69bd2f917ee5d60763c05c9d28a3d/internetarchive/catalog.py#L139
```
        if identifier:
            self.url = 'http://archive.org/history/{id}'.format(id=identifier)
        elif task_ids:
            self.url = 'http://cat-tracey.archive.org/catalog.php'
        else:
            self.url = 'http://archive.org/catalog.php'
```

https://github.com/jjjake/internetarchive/blob/5129eefb7ae69bd2f917ee5d60763c05c9d28a3d/internetarchive/catalog.py#L217
```
        url = 'http://catalogd.archive.org/log/{0}'.format(self.task_id)
```

**Comment by jjjake** [comment]
Thank you @p8NG6L. I will make sure to resolve this in the next release. My apologies for this, and thanks again for bringing it to my attention!
