### ISSUE TITLE
Error message: unsupported operand type(s) for -=: 'Retry' and 'int'

### ISSUE THREAD

**Issue by ethus3h** [jjjake/internetarchive#183]
I've seen this a few times now, using internetarchive 1.4.0 in GNU/Linux with Python 2.7. The upload command is: `ia upload "$CrystalID" --verify --retries=100 --metadata="subject:Uploaded using Crystallize $crystallizeVersion" --metadata="subject:1EA21BD8-DB7E-11E5-9733-728C37852114" --metadata=subject:"$crystalTitle" --metadata=subject:"$CrystalID" --metadata="collection:$crystalCollection" --delete "$CrystalTmpUploadFile"`

Thanks!

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/ia", line 11, in <module>
    load_entry_point('internetarchive==1.4.0', 'console_scripts', 'ia')()
  File "/usr/lib64/python2.7/site-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/lib64/python2.7/site-packages/internetarchive/cli/ia_upload.py", line 174, in main
    item = session.get_item(args['<identifier>'])
  File "/usr/lib64/python2.7/site-packages/internetarchive/session.py", line 214, in get_item
    item_metadata = self.get_metadata(identifier, request_kwargs)
  File "/usr/lib64/python2.7/site-packages/internetarchive/session.py", line 242, in get_metadata
    raise type(exc)(error_msg)
TypeError: Error retrieving metadata from https://archive.org/metadata/C3-20170222024726346872492_2d303530300ad9a25bea19d24dd3a6dde5532b8b6bb7, unsupported operand type(s) for -=: 'Retry' and 'int'
kyan@elegiac /Ember Library/Ember/ember-library/ember-library-2 nohup compiz --replace openbox $ 
```

**Comment by nikhilkumarsingh** [comment]
The error has nothing to do with internetarchive library. The problem is due to mixing of ubuntu packages with pip packages as Ubuntu makes substantial modifications to pip and Requests library.

Please refer this issue: https://github.com/kennethreitz/requests/issues/3560

**Comment by ethus3h** [comment]
I appreciate the thought, but am not using Ubuntu.

**Comment by jjjake** [comment]
Thanks again for the report @ethus3h. What OS are you using, and how did you install ia?

**Comment by ethus3h** [comment]
I'm using Gentoo GNU/Linux, and installed it using [this trivial ebuild I made](https://github.com/ethus3h/wreathe-overlay/blob/master/dev-python/internetarchive/internetarchive-1.5.0.ebuild) (an ebuild is basically a set of instructions for installing a package in Gentoo — PyPI packages are handled automatically, so the ebuild doesn't really do anything).

**Comment by ethus3h** [comment]
For what it's worth, I've worked around this by using [a bash wrapper around `ia` to forcibly retry whenever something goes wrong](https://github.com/ethus3h/crystallize/blob/v3.1.2_pre2.5.3/scripts/ember_bash_setup#L94), so this isn't a huge priority for me now (it would be nice to understand what's causing it, but my immediate issue is now solved). Thanks!

**Comment by jjjake** [comment]
Thanks for the follow up @ethus3h. I'm glad you have a work around. I'll keep the issue open, so we can hopefully get to the bottom of this! Thanks again! : )

**Comment by ethus3h** [comment]
I'm coming to a suspicion that the issue is that Gentoo's package for Requests uses the system urllib3 rather than the one bundled with Requests, and Requests needs its bundled version of urllib3 to work.

This was supposedly fixed by https://github.com/requests/requests/pull/2485, but I'm using Requests 2.12.5 which seems to include that change, so I'm not sure why I'm still seeing it. If you're interested in this, there's a ridiculous amount of commentary on this or a similar issue at https://github.com/shazow/urllib3/issues/567 and the issues linked from it.

I haven't tested patching the Requests ebuild to revert Gentoo's unbundling of urllib3, but I'll try that, I think.

**Comment by jjjake** [comment]
Thanks for the update @ethus3h. Hopefully we can get to the bottom of this soon.

Have you tried using one of the binaries? I'm curious if you experience the same issues with one of the binaries, give this a try:

    curl -LOs https://archive.org/download/ia-pex/ia
    chmod +x ia

**Comment by ethus3h** [comment]
Ok, to test, I ran `ia upload` with `--retries=100` and turned off the wifi after it printed the item name, first with the system ia, and then with the one just above. The system ia gave the usual error, while the other one gave a temporary name resolution failure error. Both aborted immediately after that, and neither retried as expected.

[Here is a transcript of the terminal session.](https://gist.github.com/ethus3h/3bd6b5463e1b945582cc41e36d7c1277)

**Comment by jjjake** [comment]
@ethus3h `ia upload --retries ...` will only retry on 503 errors returned by IA-S3. Your test case will not work offline.

This should be a better test (you should be connected to the internet):

    ia upload <identifier> <file> -H 'x-archive-simulate-error:SlowDown' --retries 100

The `x-archive-simulate-error:SlowDown` header will force IA-S3 to simulate a SlowDown (503) error. Nothing will be uploaded. Note that you can also just upload to `test_collection` for testing purposes: `ia upload <id> <file> -m collection:test_collection`. Everything in that collection gets taken down after about 30 days.

**Comment by ethus3h** [comment]
I see.

The retrying works fine with both versions using the SlowDown error, so I'll close this and just stick with the bash wrapper.

I'd assumed the retry option would just retry until it succeeded for any transient error (DNS, whatever).

Thanks for your help! Sorry for the false alarm.

_P.S.: I don't mind (and prefer) my tests to be public, at least since they're getting stored anyway, so I'd not use the test collection..._

**Comment by hofmand** [comment]
I'm seeing the same problem in ia 1.9.4 under Debian 9.4.0.
