### ISSUE TITLE
Meaning of "formats" in documentation is unclear

### ISSUE THREAD

**Issue by joepie91** [jjjake/internetarchive#184]
The [documentation for downloading items](https://internetarchive.readthedocs.io/en/latest/api.html#downloading) states the following for the `formats` option:

> __formats__ – (optional) Only return files matching the given formats.

However, it doesn't actually explain what the possible formats *are* or how to discover them. After a bit of experimentation, it turned out that the values here should match the contents of the `<format>` tag in the file metadata (eg. [here](https://download.archive.org/15/items/philosophicaltra9167roya/philosophicaltra9167roya_files.xml)).

Perhaps an explanation about this should be added to the documentation?

**Comment by jjjake** [comment]
Thanks @joepie91. I'm glad you were able to figure out, but yes this should be clearer in the documentation. I'll try to get to this soon.

Note that you can also use `ia metadata nasa --formats` to see all the possible formats for a given item. `ia ls nasa --all` will give you a more detailed listing of the files and their associated metadata. The third column is format.
