### ISSUE TITLE
Change all functions and methods to have defaults in their signatures

### ISSUE THREAD

**Issue by mlissner** [jjjake/internetarchive#185]
There's a lot of code in this repo that's like this:

    def do_something(foo=None):
        foo = 'blah' if foo is None else foo
        # some stuff happens here.

These should be:

    def do_something(foo='blah'):
        # some stuff happens here.

Maybe this is a design pattern I don't know, but it muddies up the documentation and it makes reading the code take more effort. Perhaps something to include in a bigger release when it comes out?

**Comment by jjjake** [comment]
Thanks @mlissner. This is to avoid gotchas with Python's treatment of mutable default arguments in functions. This forces a new object to be created each time the function is called.

You can find more details on this behavior here: http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/

**Comment by mlissner** [comment]
I thought it might have something to do with this gotcha. But this gotcha only applies with mutable arguments like lists and dicts. Of course it's your prerogative, but why not use default arguments when you can instead of not using them at all?

**Comment by jjjake** [comment]
I agree that this might be worth refactoring at some point, but as it would touch so much of the code I would not want to rush it through. A change like this would require a very thorough code review, as I'm not 100% confident in the tests at the moment.

I would like to prioritize other issues at the moment. If you would like to take this change on, I would be open to that. But, I am not sure how quickly I will be able to do a review on the changes and merge. Would you like me to reopen the issue?

**Comment by mlissner** [comment]
Your call. I'm not in a position to fix it myself (got too much of my own junk), but I opened it originally so it could go into longer range planning.
