### ISSUE TITLE
Some items return multiple values unexpectedly

### ISSUE THREAD

**Issue by JesseWeinstein** [jjjake/internetarchive#187]
The search API (both advancedsearch and scrape) seem to be able to return multiple values in some cases, even where the field is not expected to be able to contain multiple values (like identifier, for example).

At least for the `--itemlist` mode, such multiple-valued items should probably be ignored, with a log message warning about the problem.

**Comment by JesseWeinstein** [comment]
One current example is https://archive.org/metadata/WashingtonInDomesticLife -- which when queried with `ia search WashingtonInDomesticLife` returns `{"identifier": ["WashingtonInDomesticLife", "WashingtonInDomesticLife"]}`

**Comment by bwnelson** [comment]
In case it helps: 
There were a bunch in December 2016 returning lists which were no longer doing so in January 2017.  The WashingtonInDomesticLife seems to be the only one returning a list from January-Present.

Here's a few of the identifiers which were returning lists:
[u'46today', u'46today']
[u'6sath10', u'6sath10']
[u'957thDay', u'957thDay', u'957thDay', u'957thDay']
[u'ALifeOfFrancisParkman', u'ALifeOfFrancisParkman']
[u'AcrossThePlainsWithOtherMemoriesAndEssays', u'AcrossThePlainsWithOtherMemoriesAndEssays']
[u'AdhyatmaRamayanamu', u'AdhyatmaRamayanamu', u'AdhyatmaRamayanamu']
[u'BombayAndWesternIndia', u'BombayAndWesternIndia']
[u'CatalogueOfTheCoinsInTheIndianMuseumCalcutta', u'CatalogueOfTheCoinsInTheIndianMuseumCalcutta']
[u'ElectroChemistryForOrganicCompounds', u'ElectroChemistryForOrganicCompounds']
[u'ExtensionOfPacketCommunicationTechnologyNtoAHandHeldPersonalTerminal', u'ExtensionOfPacketCommunicationTechnologyNtoAHandHeldPersonalTerminal']
[u'MaterialsForPermanentPainting', u'MaterialsForPermanentPainting']
[u'MyCountryAndMyPeople', u'MyCountryAndMyPeople']
[u'OldsMinu1948', u'OldsMinu1948', u'OldsMinu1948', u'OldsMinu1948', u'OldsMinu1948', u'OldsMinu1948']
[u'PerfumesAndCosmeticsThierPreparationAndManufacture', u'PerfumesAndCosmeticsThierPreparationAndManufacture']
[u'Raguvamsam', u'Raguvamsam']

**Comment by jjjake** [comment]
Thanks @JesseWeinstein and @bwnelson. This should never happen (i.e. there should always only be one identifier.).

I think the solution is to figure out why this happened (looking into this now), address that issue, find all the cases of this, and finally fix the affected items.

@bwnelson if you could provide a full list, that would be very helpful. Thank you.

**Comment by bwnelson** [comment]
I'm not seeing any multiple values in the latest dump, but here's the list from 2016.12 just in case:

[returning_lists-2016.12.txt](https://github.com/jjjake/internetarchive/files/1024545/returning_lists-2016.12.txt)

Sorry about the delay!

**Comment by jjjake** [comment]
No problem, thanks for passing it along @bwnelson!
