### ISSUE TITLE
Feature request for upload: Timeout, and retry afterwards

### ISSUE THREAD

**Issue by ethus3h** [jjjake/internetarchive#188]
Sometimes `ia upload` (maybe once every few hundred uploads) gets stuck, and indicates minimal network traffic or CPU usage for several hours until I get tired of waiting for it and kill it. When this happens, it would be nice if it could timeout automatically after a customizable time (e.g. after two hours with no network use). Thanks!

**Comment by jjjake** [comment]
@ethus3h Thanks once again! : )

I'm currently working on a big ingest myself, and noticed this as well. This is high on the list of priorities, will fix ASAP.

In the meantime, a change like this should do the trick:

```diff --git a/internetarchive/item.py b/internetarchive/item.py
index 19c1664..9656984 100644
--- a/internetarchive/item.py
+++ b/internetarchive/item.py
@@ -629,6 +629,7 @@ class Item(BaseItem):
                     request = _build_request()
                     prepared_request = request.prepare()
                     response = self.session.send(prepared_request,
+                                                 timeout=60,
                                                  stream=True,
                                                  **request_kwargs)
                     if (response.status_code == 503) and (retries > 0):```

If you could provide any identifiers (or even better, `identifier/filename`) where this happens, that would be helpful. A rough date/time would be helpful as well. While the timeout would prevent things from hanging, I am still trying to get to the bottom of why this is happening so often.

Thanks again!

**Comment by ethus3h** [comment]
I'm afraid I haven't been uploading a whole lot lately, so I don't have any specific examples on hand. I'll let you know next time I see one, though!
