### ISSUE TITLE
ImportError: cannot import name 'upload'

### ISSUE THREAD

**Issue by Placid7** [jjjake/internetarchive#191]
"from internetarchive import upload" receiving error "ImportError: cannot import name 'upload'"

**Comment by jjjake** [comment]
That's strange... can you provide any more details @Placid7? How did you install ia, and what version are you using? Can you do `from internetarchive import get_item`? What about just `import internetarchive`?

**Comment by jjjake** [comment]
I'm closing this for now, happy to reopen if more details are provided.
