### ISSUE TITLE
Collection download success - no files downloaded.

### ISSUE THREAD

**Issue by Schplee** [jjjake/internetarchive#192]
New user, but when I attempt to download a collection, it successfully finds and downloads all the files in the collection, however, it doesn't appear to actually download the files. I've searched everywhere on my harddrive. Likewise, when I choose to use the working directory with "--no-directories," the files still do not appear in the current directory. I have no idea what I'm doing wrong.

http://i.imgur.com/9KERjqn.png

**Comment by jjjake** [comment]
@Schplee nothing is being downloaded. You will see a `d` for every file that is downloaded successfully (between the colon and `- success`), an `e` if there was an error, and `.` if the file has already been downloaded.

I believe the reason nothing was being downloaded has to do with your `--glob=\*pdf` parameter. Escaping the `*` will depend on your shell, but does this work?:

    ia download --search collection:n64magazine --no-directories --glob='*pdf'

This output could be more clear. I will consider that.

**Comment by Schplee** [comment]
Ah, I see. Thank you, that clears things up. And I agree, more clarity is always good.

However, after changing the input, it still doesn't show that any files were downloaded (a 'd' after each colon). This is very strange, because the collection contains PDFs of every magazine.

**Comment by jjjake** [comment]
Hm. It looks like you're on Windows, correct? What shell are you using? What if you double quote `"*pdf"`? I really think this is an escaping issue... maybe even try something like `'\*pdf'`?

My apologies this isn't working for you, I hope we can figure it out. As a workaround though, you could use the `--format` option. For example:

    ia download --search collection:n64magazine --no-directories --format="Image Container PDF"

**Comment by Schplee** [comment]
You are correct, I'm using Windows, and simply the command prompt. But wow, I can't believe it was as simple as that. `"*pdf"` was the solution, and every file is successfully downloading.

Thank you very much for your assistance!

**Comment by jjjake** [comment]
Great to hear! I'll make a note to clarify this in the documentation.
