### ISSUE TITLE
A '–' (Unicode EN DASH) character in spreadsheet title causes a crash

### ISSUE THREAD

**Issue by davmo** [jjjake/internetarchive#196]
The column "title" in a spreadsheet file contains "hpr0989 :: Juiced Penguin 079 – Early Spring" with a Unicode character in it. This causes ia to fail with this error:
```
$ ia upload --retries=3 --spreadsheet=metadata_0989.csv
Traceback (most recent call last):
  File "/usr/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/internetarchive/cli/ia.py", line 155, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/lib/python2.7/site-packages/internetarchive/cli/ia_upload.py", line 218, in main
    md_args = ['{0}:{1}'.format(k.lower(), v) for (k, v) in row.items() if v]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)
```
The offending file can be supplied on request

**Comment by saper** [comment]
Does this help?

https://github.com/jjjake/internetarchive/compare/master...saper:utf8mod

**Comment by davmo** [comment]
Thanks.
Excuse my ignorance, but how would I go about testing this?

**Comment by jjjake** [comment]
@saper thanks for pointing to your solution. What do you think of this?:

https://github.com/jjjake/internetarchive/tree/csv-unicode-support

I think this is a better solution for supporting PY2 and PY3. Would you mind giving this branch a try if you have time? Please let me know if you have any other feedback as well.

@davmo How did you install `ia`? I can help you test out Saper or my branches that address this issue once I know how you installed `ia` (e.g. via `pip`, `easy_install`, or by downloading a binary?).

**Comment by davmo** [comment]
@jjjake I used pip to install `ia`

**Comment by jjjake** [comment]
I think this should do it, @davmo:

    pip install 'git+https://github.com/jjjake/internetarchive.git@csv-unicode-support'

`ia -v` should output `1.6.0.dev6`. Run that to confirm you're running with the `csv-unicode-support` changes.

**Comment by davmo** [comment]
Thanks for that @jjjake. I now see:

```
$ ia metadata --spreadsheet=metadata_0989_2.csv
/usr/lib/python2.7/site-packages/jsonpatch.py:221: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value == other:
hpr0989 - success: https://catalogd.archive.org/log/680944123
```

I interpret this as success. The item was already uploaded (I cheated and used `ias3upload.pl`) so it maybe wasn't a good test as it could have been, but I assume that since there was no overt failure it's successful.

**Comment by jjjake** [comment]
@davmo I didn't make any changes to `ia metadata`, only `ia upload`. I will take a closer look, but I think that warning can be ignored.

Can you test out `ia upload --spreadsheet`? This is where I applied the fix for your initial issue.

**Comment by davmo** [comment]
Oops! Sorry, I assumed it was common code. I have a batch to upload tomorrow and will test it then by inserting some Unicode as I upload. I'll report back what happens.

**Comment by jjjake** [comment]
Thanks. It should probably be common code, but isn't currently. I will add this fix to `ia metadata` as well, which should address that warning.

Thanks again!

**Comment by davmo** [comment]
@jjjake I just tested with an upload where I'd added an EN DASH in the title. It worked without trouble and the resulting upload shows the character as expected.
```
$ ia upload --retries=3 --spreadsheet=metadata_2307.csv
hpr2307:
 uploading hpr2307.wav: [################################] 91/91 - 00:00:07
```

Many thanks for your efforts (and those of @saper)

**Comment by saper** [comment]
@jjjake your solution is of course better. I just hacked mine quickly just to figure out if this was the place to put nails into.

**Comment by jjjake** [comment]
Thanks for testing @davmo. I'll make sure this gets in the 1.6.0 release.

@saper Thanks for taking a look, and helping out. I appreciate it!
