### ISSUE TITLE
error downloading non-public files

### ISSUE THREAD

**Issue by jeffgerhard** [jjjake/internetarchive#197]
I'm no longer able to download files that require my logged-in credentials. I work on a library project that includes IA materials that are not generally available for public download; however, until recently I could download these files through `internetarchive` using my account access. Now I'm receiving Forbidden errors like the following (in python):

> error downloading file awakeni_huf_2003_00_5605_orig_jp2.tar, exception raised: 403 Client Error: Forbidden for url: https://ia601508.us.archive.org/29/items/awakeni_huf_2003_00_5605/awakeni_huf_2003_00_5605_orig_jp2.tar

The command line tool `ia download` also returns "e - errors".

I still have permission to download all files in these items via a logged-in browser. And I can download public files from the same item via python or the CLI,, like `ia download awakeni_huf_2003_00_5605 awakeni_huf_2003_00_5605_dc.xml`.

Thanks for any insights! (Probably not relevant but I'm using Python 3.5.2 in Windows 7 and internetarchive 1.5.0)

**Comment by jjjake** [comment]
@jeffgerhard When is the last time you ran `ia configure`? The `logged-in-` cookies it adds to that file are good for about a year. After that you will need to rerun `ia configure` to refresh your cookies.

I appreciate the details on OS, platform, and version -- these are always helpful!

Please let me know if the above doesn't help, and I'll take a closer look. Thanks for the report!

**Comment by jeffgerhard** [comment]
Thanks @jjjake ! That was the issue. Rerunning `configure` also cleared up my problem with `tasks` on [167](https://github.com/jjjake/internetarchive/issues/167#issuecomment-305782887). I didn't suspect that I had any problem with my local configuration since I have been able to upload and modify items normally. Thanks for the easy fix!

**Comment by jjjake** [comment]
No problem. I will also look into adding a more descriptive error that suggest running `ia configure` again when this happens.

**Comment by saper** [comment]
Didn't know one can upload non-public data. Why do so and how?

**Comment by ethus3h** [comment]
@saper: The Internet Archive's Open Library project, for instance, allows borrowing scans of in-copyright books. The original files aren't publicly available, because there wouldn't be any way to make sure the scans got returned by the due date (the files borrowed from Open Library are encrypted, so they can't be used outside of the period they were lent for). That makes sure that only one person can be reading the corresponding physical copy of a book at any time (the physical books are stored by the Internet Archive), so that the authors and publishers get the royalties owed them for the purchase of the book.

I hope this helps!

**Comment by jjjake** [comment]
@saper There are various reasons we have data that is non-public. Our lending library is an example, as ethus3h points out.

Uploading non-public data requires uploading to an access-restricted collection. You'll need to contact info@archive.org to get this setup if you need it for some reason. For obvious reasons, we only do this when necessary (e.g. if something can only be archived if it's not made public at the moment). It's not something we encourage, but an access control tool we use when necessary.

info@archive.org can also answer any other questions you have about this.

**Comment by saper** [comment]
Thank you guys for the pointers! I wasn't aware of that feature. I was considering IA to store dumps for some public wiki, but redacting all private data would be too difficult, so a closed collection could have been a quick solution for that (but not satisfactory). I will continue working on weeding the private data out and make it public :)
