### ISSUE TITLE
ia metadata --spreadsheet= should clear metadata fields which have become empty

### ISSUE THREAD

**Issue by davmo** [jjjake/internetarchive#198]
This is a follow-on from #179 and is a response to the last comment regarding `ia metadata`

As I understand it `ia metadata --spreadsheet=` will not currently clear individual components of previously uploaded multi-part metadata. At least, this is my interpretation of what happened when I tried to use it to correct a problem caused by issue #179.

The scenario I face is this:
- an item is uploaded with e.g. three `subject` fields (which come from `tags` in our episode database)
- for some reason one of those fields is erroneous and we wish to remove it
- we regenerate the metadata which now has two `subject` fields, while the uploaded version has three
- applying the updated metadata should modify the list of subjects to omit the one deleted in the CSV data
- this does not happen

This behaviour has been particularly relevant recently given that issue #179 was allowing fields to "leak" from one row in the CSV file to another.

Applying these subjects to these items using `ia metadata`:
```
hpr2308: guix,linux,nix,sysadmin,development
hpr2309: Accessibility, scripting, audio editing, speech-to-text
hpr2310: Kdenlive,opensource.com,workflow
```
Still leaves them with the extra "leakage":
```
hpr2309: Accessibility, scripting, audio editing, speech-to-text, development
hpr2310: Kdenlive,opensource.com,workflow, speech-to-text, development
```

Having used `ias3upload.pl` for several years prior to the (welcome!) arrival of `ia` I know that when presented with the same changes as described above, this script will remove the "leaked" subjects.

I hope this helps to clarify why such behaviour is desirable in `ia`.

**Comment by jjjake** [comment]
Thanks for the great report, @davmo.

I forgot to mention this previously, but you can remove fields by setting the value to `REMOVE_TAG`. For example:

    » ia md jj-test-2017-06-07 -m subject:foo -m subject:bar
    jj-test-2017-06-07 - success: https://catalogd.archive.org/log/682456408
    » ia md jj-test-2017-06-07 | jq -c .metadata.subject
    ["foo","bar"]
    » ia md jj-test-2017-06-07 | jq -c .metadata.subject
    null
    » ia md jj-test-2017-06-07 -m subject:foobar -m subject:barbaz
    jj-test-2017-06-07 - success: https://catalogd.archive.org/log/682456595
    » ia md jj-test-2017-06-07 | jq -c .metadata.subject
    ["foobar","barbaz"]

This still doesn't address your issue, and the desired behavior you'd like to see. You can use `REMOVE_TAG` to address these items one by one, or with two spreadsheets (one that removes all subjet tags, and one that adds all new ones) -- but, I still think the current behavior could be improved.

I guess the question is how do we support indexes for multi-fields (e.g. subject) and also support clobbering when desired in spreadsheet mode. I do know that there are some users who depend on the current behavior (inserting when an index is present rather than clobbering).

Hopefully others chime in with their thoughts on this issue as well.

I hope the double spreadsheet solution is an acceptable workaround for you in the mean time. Let me know if you don't understand what I mean, and I can provide more details.

**Comment by davmo** [comment]
Thanks for the `REMOVE_TAG` hint @jjjake. I had seen that in the documentation but had never used it. I can see how I could build something around it to fix stuff - if there was no other way.

What I don't understand is what model you are using to represent multi-element fields. My mental model has always been that something like `subject` is basically a list. I had assumed that if such a list contained `a,b,c` and you wished it to contain `d,e,f` the spreadsheet need only be regenerated containing the latter rather than the former.

Similarly if `a,b,c` is to be appended to, then simply presenting it as `a,b,c,x,y,z` would be sufficient. In other words, the spreadsheet representation contains the entirety of the list, and the intention is that the list is to be replaced by it completely.

I'm not clear about the context in which you are using `clobber` here. I would interpret it as the same as Bash does with its `noclobber` option: "don't overwrite this file". In that interpretation my list wipe-and-rebuild picture could be called clobbering.

I may be influenced in my interpretation of the update mechanism used by `ia metadata` by two things:
- I have worked a lot with LDAP which is a data store containing 'tag:value' items, where it's often easiest to remove all instances of a given 'tag' and replace them with a new set in the way outlined above.
- The author of `ias3upload.pl` seemed to have the same idea, if I interpret the rather tangled Perl code correctly!

You seem to be approaching the field update problem in a different way than I expected. I'd appreciate more insight into this approach.

Thanks
