### ISSUE TITLE
Apparently repeatable 'Broken Pipe' error on --spreadsheet= upload

### ISSUE THREAD

**Issue by davmo** [jjjake/internetarchive#199]
This might be the same issue as #176. If so I'll happily delete this one and attach this text to that issue.

Each weekend I prepare a CSV file of 5 rows (6 with the header) relating to the previous week's podcast episodes (Hacker Public Radio, one episode every weekday - sorry for the plug!). Today's batch was for episodes 2311-2315.

Running `ia upload --spreadsheet=` resulted in a 'Broken Pipe' failure after the first row was processed. I have a copy of the error, but it looks pretty much identical to the example in #176 so I'll omit it here. It's available on request.

I retried the upload between 5 and 6 times throughout the day, all with the same result.

I decided to try dividing the CSV file, making two: 2311-2312 and 2313-2315. Trying 2311-2312 failed on 2311. File 2313-2315 was completely successful.

I retried 2311-2312 twice, then edited the file to reverse the order of the rows. Uploading this I saw 2312 uploaded successfully but the upload failed on 2311 with a 'Broken Pipe' error.

Testing the hypothesis that 2311 was somehow faulty I generated a new CSV file containing only that episode and tried to upload it. It succeeded.

I have seen a similar scenario before. If my 5-row upload fails, it invariably fails on the first row. Generating two files containing 1 row and 4 rows then results in success in both cases. I have kept a brief log of these events since 2017-01-07.

It's possible my CSV-generating script is doing something odd, but it's difficult to see what! You're welcome to have copies of these particular files if it'll help.

I hope this adds something useful to the discussion.

**Comment by jjjake** [comment]
@davmo Yes, it would be helpful if you could send along the spreadsheet and some example files. My email is on my profile.

What's the output of `ia -v` (I'm wondering if you're still using the github master branch), and I believe you're on Python 2 as well, correct?

**Comment by davmo** [comment]
Thanks @jjjake 
Here's the `ia -v` output: 1.6.0.dev7
I'm on a VPS which I don't manage, but as far as I can see both Python 2 and 3 are installed here.

I'll send on some files shortly.

**Comment by jjjake** [comment]
@davmo Sorry for the delayed follow up.

a6d2f97b4b4ae86d31c93200dc56aefa007b83e2 should fix this issue. The issue was in how I was dealing with indexed metadata keys (e.g. `subject[0]`). I was failing to strip the index if it was the only key with an index (i.e. if the item metadata for the given request had `subject[0]`, but not `subject[1]`, `subject[2]`, etc.).

This should now be resolved. Please let me know if you continue to have issues. This will be available in v1.7.0 (and is currently available on master).
