### ISSUE TITLE
Check for valid identifier before uploading?

### ISSUE THREAD

**Issue by TheCoinCollector** [jjjake/internetarchive#203]
I'm still relatively new to using this module, so I wonder if this is this way for a reason.

When attempting an upload with -spreadsheet with what turns out to be an invalid identifier, it waits until the full file gets uploaded and _then_ fails with an error message.  This just happened on a pretty large video file.  Is there any reason it can't check the identifier before beginning the upload?

Thanks!

**Comment by jjjake** [comment]
How is the upload failing exactly @TheCoinCollector? What is the error message? Can you also send me the output of `ia --version`?

The Python library that `internetarchive` uses to make HTTP requests, Requests, does not have 100-continue support and our S3 API depends on that for raising certain errors without waiting for all of the data to be sent.

We might be able to work around this client-side, depending on the error.

**Comment by TheCoinCollector** [comment]
I'm on 1.5.0 - downgraded for now to get around the separate broken pipe error.

The identifier error I mentioned here was no big deal - it was longer than 100 characters.  I just thought it was strange ia did the full upload before giving me the error, but if it's because of a technical hurdle that's fine.
