### ISSUE TITLE
Mismatched reporting on version numbers

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#207]
Pip tells me it's `1.7.1` but on [testing](https://archive.org/details/youtube-FThwxz079Vc) the "Scanner" tag is reported as `1.7.0`

I know it's super nit-picky but I wanted to point it out before anyone else did. It's not a problem, and you can close this if you just snort at the issue and I won't be offended, but it's a case of consistency in versioning.

**Comment by jjjake** [comment]
I released version 1.7.1 shortly after releasing 1.7.0 to address a bug:

https://github.com/jjjake/internetarchive/releases

**Comment by jjjake** [comment]
Also, not nit-picky at all, thanks for reporting.

Please let me know if I missed something, and we will address it.

**Comment by vxbinaca** [comment]
I just missed the change. I was upgrading my 5 machines when you were pushing a fix. You were right to close.
