### ISSUE TITLE
Archive.org search engine not being updated with new items.

### ISSUE THREAD

**Issue by jjjake** [jjjake/internetarchive#208]
As of right now, new items uploaded to archive.org are not being indexed by the search engine or appearing on their collection pages.

This is a known issue, and will hopefully be resolved over the next 48 hours.

Our apologies for the delay, and thanks for your patience!

**Comment by saper** [comment]
Is this a bug in `ia` or a bug in the IA infrastructure?

**Comment by vxbinaca** [comment]
@saper Infrastructure. And I'm curious as to the details of what's going on. If it's related to the power outages, fiber breaks, or new code.

**Comment by saper** [comment]
Wow, our little bugtracker should be honored to see bags of a big sister tracked over here;)

**Comment by jjjake** [comment]
@saper We had a few power outages last week and had some issues bringing our search indexing back up.

Everything should be back to normal now.
