### ISSUE TITLE
Two quick questions...

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#210]
- what's the flag to set licences for items? [Like this licence](https://archive.org/details/youtube-CTsDG6KIMss). Currently I have to hand process her subtitles (this is due to a bug in youtube-dl where the library calls won't convert subtitles to SRT), however I'm having to hand-set her licence too [and I did get her permission first.](https://twitter.com/vxbinaca/status/894439682796388352). The licencing part is the laborious part because I've reduced the subtitle part to a one-liner.

- Is there a way to create a obscured collection my user can write to, that's un-indexed from the search or search engines, that can be 'un-obscured' with all it's items in a few clicks? Is that even possible with your architecture?

Thanks, and please close on answering.

**Comment by jjjake** [comment]
You simply need to add the URL to the license to the `licenseurl` metadata field. For example:

    ia upload jj-test-2017-08-28 foo.txt -m 'licenseurl:https://creativecommons.org/licenses/by-sa/4.0/'

If you bake this into `tubeup` (that'd be cool! : )), please use HTTPS rather than HTTP.

You can upload your items with `noindex:true`, and remove the `noindex` tag when you wanted them to be indexed. This will keep them out of the search engine (until you remove `noindex`. Generally we don't recommend this, though. What is the goal here?

**Comment by vxbinaca** [comment]
**Baking CC-BY-SA-4 into Tubeup:** We left licencing out so as to not mis-licence things, and we' go back by hand and do one or a few videos, but doing her collection is labor intensive.

Just to clarify though, you mean this as a flag (using complete command):

`tubeup --metadata=collection:naomiwuarchive licenseurl:https://creativecommons.org/licenses/by-sa/4.0/ https://www.youtube.com/channel/UCh_ugKacslKhsGGdXP0cRRA/videos`

Is that placement correct? If yes I'll push it to my servers.

**Obscuring goals:** I want to archive many videos from a subject into a collection in secret so no one notices, and then is the subject get terminated off youtube, re-index them all quickly/easily so they show up again. I know the idea of a 'dark archive' is corrosive to the idea of open access, but sometimes people only understand the value of something once it's gone and this includes the creators who will be less finicky once someone else has the only copy else where.

But if this breaks the spirit of the site, I'll just not attempt it and manage without it. Options are nice though.

By the way, I've synced my servers now to be a crude Warrior bot. Github will now be used to manage the scripts and share progress of rips without my input. I just started it last night. So it's a crude archival botnet of VPSs, where Github is the C&C. This will allow me to touch the servers less, eliminate drifts in progress, and have it survive even if I should stroke out in my sleep or something. The work will continue without me if need be.

**Comment by jjjake** [comment]
Yes, that command above looks correct.

With regards to the obscuring goals. It sounds like you get the idea of why we would discourage noindexing items uploaded to archive.org. Please do whatever you think is best. I still would strongly suggest against it as a default in any code used by many people.

**Comment by vxbinaca** [comment]
I'll push that command to my servers and simply avoid non-indexing. Thanks!

**Comment by vxbinaca** [comment]
We had to do a moderate code addition to Tubeup yesterday, and one of the things I changed was bumping the CC-BY-SA to 4.0. Chaining the flags worked instead of cramming them onto one long flag. Thanks!

Please update your `tubeup` and `youtube-dl` packages, and pass the word on. Youtube won't work until you do.

Semi-related: The layout change on Youtube halted all archival activity because the change corrupted metadata values with `null` and broke links or set wrong dates among other things.

**Comment by jjjake** [comment]
Thanks for the heads up, I'll pass along the info @vxbinaca! : )
