### ISSUE TITLE
item.upload throws error when file object submitted

### ISSUE THREAD

**Issue by palewire** [jjjake/internetarchive#211]
The documentation suggests the upload API accepts file-like objects but I'm getting an error when I try to submit a file reference from a Django ImageField. Here is a simplified version of method on my model object that's failing. 

```python
    def upload_to_ia(self)
        metadata = dict(
            collection="my_collection",
            title='My title',
            mediatype='image',
        )
        files = []
        if self.has_image:
            files.append(self.image.file.file)
        if self.has_crop:
            files.append(self.crop.file.file)
        internetarchive.upload(
            self.ia_id,
            files,
            metadata=metadata,
            access_key=settings.IA_ACCESS_KEY_ID,
            secret_key=settings.IA_SECRET_ACCESS_KEY
        )
```

The error comes in ``recursive_file_count`` when the code attempts to open the object as if it were a string with a  file path. 

```python
File "/home/palewire/.virtualenvs/pastpages.org/local/lib/python2.7/site-packages/internetarchive/utils.py", line 243, in recursive_file_count
    lmd5 = get_md5(open(f, 'rb'))
TypeError: coercing to Unicode: need string or buffer, Object found
```

I don't think that will work with even basic StringIO file objects like:

```python
>>> open(StringIO('foobar'), 'rb')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: coercing to Unicode: need string or buffer, cStringIO.StringI found
```

So either I'm screwing up something basic (Sorry in advance if that's the case) or I'm misunderstanding the docs.

**Comment by jjjake** [comment]
Thanks for the report @palewire.

It looks like what you're doing should work. I have never tested it out on Django ImageField objects, though. I think this is something we definitely would like to support. I will take a closer look and follow up here.

**Comment by palewire** [comment]
Is there an example out there I can refer to?

**Comment by jjjake** [comment]
@palewire Looks like there was a bug in `recursive_file_count()` in deed. https://github.com/jjjake/internetarchive/commit/a3fa4710ae45499c9241a2857cde693986688c10 should fix it.

Here's an example that should work with the most recent commit posted above (v1.7.2.dev5):

    from StringIO import StringIO

    import internetarchive as ia


    if __name__ == '__main__':
        fobj = StringIO('foobar')
        r = ia.upload('jj-test-2017-09-08', {'foobar.txt': fobj}, metadata=dict(collection='test_collection'))
        print(r[0], r[0].content)

I'm not sure this will work with `ImageField`, though. Are you sure `ImageField` is a file-like object? Let me know how it goes, or if you run into any other issues.

Thanks again for the report!
