### ISSUE TITLE
Bring code copyright to current year

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#212]
This can be done easily in a one-liner (this should work): 

`git grep -l '2016' | xargs sed -i 's/2016/2017/g'`

~~Not to adopt a Stallman beard to compete with yours, but please also consider [alternatives to copyright](http://questioncopyright.org/) for your code.~~ Nevermind that.

Thanks!

**Comment by ethus3h** [comment]
As far as I can see, it's AGPL3, which is a great free/libre/open-source license!
