### ISSUE TITLE
Allows uploading files with disallowed characters.

### ISSUE THREAD

**Issue by vext01** [jjjake/internetarchive#218]
Hi,

I recently uploaded a file using your Python script. It worked fine, but when I came to move it using the web interface. an error occurred:

![error](https://user-images.githubusercontent.com/604955/31541707-794cdcf8-b007-11e7-80aa-1d055a675a93.png)

Should you check the filenames *before* the upload?

**Comment by vxbinaca** [comment]
Yes this is especially cruel because it's killed massive 6 gigabyte Twitch uploads for me.

**Comment by jjjake** [comment]
Is this a bug report for the HTML uploader on archive.org, or the Python library/command-line tool? What is the character that's causing the issues?

**Comment by vxbinaca** [comment]
For me it was :

**Comment by vxbinaca** [comment]
No this is for item identifiers. Please see [issue #47](https://github.com/bibanon/tubeup/issues/47) I'm waiting for Antonizoon to fix this.

**Comment by ethus3h** [comment]
The screenshot in the initial issue report here is in a filename rather than an identifier, it looks like... (perhaps the "+"?)

**Comment by jjjake** [comment]
@vext01 I misunderstood your issue yesterday. It looks like this isn't an issue with this library or the command-line tool, but an issue with archive.org (specifically, moving/renaming files with edit.php). These types of issues are better sent to info@archive.org, but I'll pass it along. Thanks for the report, we appreciate it!

In the meantime, you can get around this by re-uploading your file with the new name and deleting the old file with edit.php.

@vxbinaca Ah, yes, `:` is not allowed in item identifiers. That is an archive.org limitation, not one of this library. I don't see that changing. See http://internetarchive.readthedocs.io/en/latest/metadata.html#archive-org-identifiers for more details on identifiers.

@ethus3h Thanks for taking a look! I think you're correct. It seems to be an issue with the `+`.

**Comment by vxbinaca** [comment]
We know. That's why we want to take the output youtube-dl gives us, and just adapt it on our end, instead of asking you all to change.

By the way, the command line output for this illegal item character error has a typo. "Somting" is missing the H.

Thanks again.
