### ISSUE TITLE
undocumented features need to be documented

### ISSUE THREAD

**Issue by mjb2010** [jjjake/internetarchive#222]
`ia --log`
Logs uploads and errors to the file internetarchive.log, appending to it if it already exists.

`ia metadata --append=foo:bar`
Appends bar to foo's existing value, e.g. if foo's value is "abc", it becomes "abcbar".

"If you would like to specify multiple values for certain fields, an index can be provided: subject[0], subject[1]" ... this is mentioned only under "Modifying Metadata in Bulk" in reference to spreadsheets, but it applies anywhere field names are given, such as:
`ia metadata --modify=foo[0]:bar --modify=foo[1]:baz`

Uploads will overwrite existing remote files. If a spreadsheet-based upload is interrupted, you probably will want to remove already-processed rows from the spreadsheet before trying again.

If you upload a folder and later want to change a file in that folder, you need to delete and re-upload the whole folder, which will re-upload all its contents. If you just do `ia upload <identifier> <folder>/<file>` you will find `<file>` gets uploaded to the root folder. (Maybe this is a bug? or feature?)

**Comment by jjjake** [comment]
Thanks for the beedback, @mjb2010.

I'll get to this as soon as I can, but pull requests are always welcome as well.

**Comment by JustAnotherArchivist** [comment]
To add three more:

* The `sorts` parameter of `search_items` is undocumented, and its format isn't obvious (cf. #140).
* The possible parameters for the `params` argument of `search_items` are also not documented as far as I could see. (They can be found in the source code of https://archive.org/advancedsearch.php.)
* I didn't find it mentioned anywhere in the docs or `ia help` that `--log` and `--debug` write to a file `internetarchive.log` in the current directory. I expected it to write to stderr (like curl or wget).

And while we're discussing the documentation, I found it a bit confusing that the "Quick Start" chapter only shows the library usage. I'd think that the CLI is used much more frequently especially by new users who are looking for a tool to upload files to IA.

**Comment by aborruso** [comment]
> The possible parameters for the params argument of search_items are also not documented as far as I could see. (They can be found in the source code of https://archive.org/advancedsearch.php.)

@JustAnotherArchivist than is it possible to make this kind of query?

    ia search --parameters="description:beatles"  "Lennon"

Thank you

**Comment by jjjake** [comment]
@aborruso I think this is what you're after:

    ia search 'description:beatles AND Lennon'
