### ISSUE TITLE
Invalid Character Error does not tell you what/where the character is

### ISSUE THREAD

**Issue by mjb2010** [jjjake/internetarchive#223]
Perhaps a server-side feature request, but I kept getting "error (400): Invalid Character Error" when trying to upload from a spreadsheet, and had no idea where the problem was. It would help if this message would tell you what character is invalid or where it is. In my case, it was a space character in a metadata field name.

Or maybe just add something to the FAQ.

**Comment by jjjake** [comment]
Thanks again @mjb2010. I updated the docs: 60570b18446488d053450868377cc4875474f1fe
