### ISSUE TITLE
Downloading non-existent files reports success

### ISSUE THREAD

**Issue by ethus3h** [jjjake/internetarchive#224]
Running `ia download skoda-december 'skoda-december.thumbs/298_248_superb_avro_roku_black_1px%281%29_000014.jpg'` prints:

```
skoda-december:  - success
```
and exits with 0 (no error), even though no file was downloaded (because the file specified does not exist — running it with the actual name of the file, `/usr/bin/ia download skoda-december 'skoda-december.thumbs/298_248_superb_avro_roku_black_1px(1)_000014.jpg'`, works fine).

Downloading a nonexistent file should produce an error message and exit with a non-zero status.

Thanks!

**Comment by jjjake** [comment]
Thanks for the feedback, @ethus3h.

Yes, this needs some work.

I think it could make sense for this specific case to be treated like an error, but there's also the `ia download <id> -g 'foo*'` case (and similar cases). I think in this particular case, it might not make sense to be treated like an error. For example, maybe you don't know what files are in the item and you want to download them if they exist and do nothing if they don't.

Personally, I use the following workflow quite a bit:

    ia search 'collection:foo' --itemlist > itemlist.txt
    parallel --joblog 'ia download {}' < itemlist.txt
    parallel --retry-failed --joblog 'ia download {}' # Retry any command that did not exit with 0.

In that case, I would not want `ia` to exit with 0 if no matching files were found (as it would keep retrying and failing forever).

Perhaps the answer is to provide a parameter(s) to make this more flexible (e.g. --ignore-errors, and have `ia` exit with something other than 0 by default when there are no matching files).

I'm going to think on this a bit. Hopefully we can get more feedback from others as well.

Thanks again for the feedback, this has been something that has bothered me for a while. It needs some work.
