### ISSUE TITLE
ArchiveSession.search_items is unable to sort by oai_updatedate

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#226]
As far as I understand the documentation, the following code should list all items in the ArchiveBot collection that were modified yesterday, with more recently modified items listed first:

```
import internetarchive
for i in internetarchive.search_items('collection:archivebot oai_updatedate:[2017-11-07 TO 2017-11-07]', sorts = ['oai_updatedate desc']):
    print(i)
```

Instead, this produces the following error:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    for i in internetarchive.search_items('collection:archivebot oai_updatedate:[2017-11-07 TO 2017-11-07]', sorts = ['oai_updatedate desc']):
  File ".../lib/python3.4/site-packages/internetarchive/search.py", line 202, in __next__
    return self.iterator.__next__()
  File ".../lib/python3.4/site-packages/internetarchive/search.py", line 133, in _scrape
    self._handle_scrape_error(j)
  File ".../lib/python3.4/site-packages/internetarchive/search.py", line 168, in _handle_scrape_error
    raise ValueError(j.get('error'))
ValueError: sort field 'oai_updatedate' is not a valid search field
```

The same thing happens when you use the CLI:

    > ia search 'collection:archivebot oai_updatedate:[2017-11-07 TO 2017-11-07]' --itemlist --sort='oai_updatedate desc'
    error: sort field 'oai_updatedate' is not a valid search field

Interestingly, adding a `page` parameter prevents the error, e.g. with the CLI:

    > ia search 'collection:archivebot oai_updatedate:[2017-11-07 TO 2017-11-07]' --sort='oai_updatedate desc' --parameters='page=1' --field=identifier,oai_updatedate
    {"identifier": "archiveteam_archivebot_go_20171107230001", "oai_updatedate": ["2017-11-07T23:31:46Z", "2017-11-07T23:31:46Z", "2017-11-08T13:34:44Z"]}
    ...

This might be a bug in the backend rather than this package, but I'm not sure.

Software versions: internetarchive 1.7.1, Python 3.4.2, Debian Jessie.

**Comment by jjjake** [comment]
Thanks for the report @JustAnotherArchivist.

The error message should actually read `... is not a valid sort field` (i.e. sort not search).

By default, search uses the Scraping API (http://archive.org/help/aboutsearch.htm). However, when you specify page and rows params, it uses the Advanced Search API (https://archive.org/advancedsearch.php). It looks like Advanced Search allows sorting by `oai_updatedate` while the Scraping API does not.

The reason both APIs are used is that the Scraping API doesn't allow paging, but Advanced Search does. Advanced Search does not allow exporting more than 10k results, but the Scraping API does.

It looks like this could be addressed with documentation updates and fixing the error message.

As a work around, I recommend dumping all of the results and sorting by `oai_updatedate` locally.

Thanks again for the report, and sorry for the confusion.

**Comment by JustAnotherArchivist** [comment]
Ah, thanks for the explanation.

Yes, fixing the error message and improving the documentation would definitely help. Wouldn't the Scraping API not supporting sorting by `oai_updatedate` still be a (backend) bug though?

**Comment by jjjake** [comment]
I just got some more info, and it looks like it's not sortable because it's a multi-value field. I would consider this a feature request, and not a bug (info@archive.org is a good place to send those, but I'll pass it along as well.).

If you only care about the first value, you could do something like the following using `jq` (https://stedolan.github.io/jq/):

    ia search 'collection:archivebot AND oai_updatedate:[2017-11-07 TO 2017-11-07]' -f oai_updatedate \
        | jq --slurp  'map(.oai_updatedate = .oai_updatedate[0]) | sort_by(.oai_updatedate)'

**Comment by JustAnotherArchivist** [comment]
I see. Yeah, that makes sense. I'll send an email to info@, thanks!
