### ISSUE TITLE
Improve error message when user needs to login

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [jjjake/internetarchive#234]
I was trying to download the following:

```
user@server:~$ ia download stackexchange
stackexchange: eedeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee - errors
```

The error message `errors` comes from the fact that one has to login to be able to download the Stack Exchange dump. It would be nice if the error message was more explicit.

**Comment by jjjake** [comment]
You can use the `--verbose` parameter if you'd like the output to be more explicit:

```ia download --verbose stackexchange```

Or, the `--log` global option:

```ia --log download stackexchange```

Which will log error's like so:

    2018-02-05 09:47:24,157 - internetarchive.files - ERROR - error downloading file stackexchange/3dprinting.meta.stackexchange.com.7z, exception raised: 403 Client Error: Forbidden for url: https://ia800801.us.archive.org/23/items/stackexchange/3dprinting.meta.stackexchange.com.7z
    ...

It looks like that item was uploaded to our `loggedin` collection for whatever reason, so I imagine you were getting 403s. When an item is a part of the `loggedin` collection, it simply requires that you are logged into archive.org to download the files.

If you run `ia configure`, I bet you'll be able to download the files. Please let me know if you're still not able to, or if you run into any other issues.

Thanks for taking the time to report your issue, @Franck-Dernoncourt. I appreciate it!
