### ISSUE TITLE
ImportError: cannot import name printable_usage

### ISSUE THREAD

**Issue by yurivict** [jjjake/internetarchive#236]
setup.py says ```docopt>=0.6.0,<0.7.0```, I have py27-docopt-0.6.2_1, but it fails:
```
$ ia
Traceback (most recent call last):
  File "/usr/local/bin/ia", line 11, in <module>
    load_entry_point('internetarchive==1.7.7', 'console_scripts', 'ia')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/internetarchive/cli/__init__.py", line 27, in <module>
    from internetarchive.cli import ia, ia_configure, ia_delete, ia_download, ia_list, \
  File "/usr/local/lib/python2.7/site-packages/internetarchive/cli/ia.py", line 62, in <module>
    from docopt import docopt, printable_usage
ImportError: cannot import name printable_usage
```

**Comment by yurivict** [comment]
This bug is a deal-breaker. It can't run with unknown symbols like this.

**Comment by jjjake** [comment]
What did you use to install `internetarchive`? I'm not able to replicate this issue with python 2.7.12 and docopt 0.6.2 on mac or linux. I'm assuming this on FreeBSD as well?

What minor version of Python is this? Are you able to run `python -c 'from docopt import printable_usage'` successfully?

Thanks again for reporting the issue.

**Comment by jjjake** [comment]
Does the binary work for you?:

http://internetarchive.readthedocs.io/en/latest/installation.html#binaries

**Comment by yurivict** [comment]
OS is FreeBSD. ```python2.7 -c 'from docopt import printable_usage'``` works fine for both python-2.7 and python-3.6.

---
> Does the binary work for you?

Yes, it works.

**Comment by jjjake** [comment]
I'm not sure what the issue is here. I'll have to try and get access to a freebsd machine, and poke around.

Please let me know if you have any recommendations for making this work on freebsd, and please feel free to send a PR.

FWIW, I have reports that `internetarchive` installs fine on freebsd with `pip`.

**Comment by yurivict** [comment]
This line works from a standalone file: ```from docopt import docopt, printable_usage```.
But it fails when run as part of ```internetarchive``` for unknown reason.
It's weird that it only fails when installed into /usr/local/bin/. When the file is coped elsewhere it works fine.

**Comment by yurivict** [comment]
Ok, I found the reason. One other package (pcmsolver) installed /usr/local/bin/docopt.py and internetarchive picks this file as a source to import the module.

This is really a bug in that other package. I have too many weird packages installed - totally my fault. -)

Thank you for your help!

**Comment by cclauss** [comment]
`mypy` agrees that this is a problem because the current version of docopt does not have this function but instead puts this debug output into the SystemExit handler.
> internetarchive/cli/ia.py:65: error: Module "docopt" has no attribute "printable_usage"

https://github.com/docopt/docopt/blob/master/examples/interactive_example.py#L23
