### ISSUE TITLE
Replace docopt with argparse

### ISSUE THREAD

**Issue by jjjake** [jjjake/internetarchive#245]
In working towards the goal of shedding dependencies, replace docopt with argparse.

Feedback welcome.

**Comment by jjjake** [comment]
@vxbinaca I don't believe so, but it's been a while since I've looked at the tubeup code.

I don't see any reason it would require you to replace docopt, but I might be missing something. You're only using the Python interface, correct? If so, this should be irrelevant.

Please correct me if I'm wrong, and thanks for checking on this!

**Comment by maxz** [comment]
I tried to implement the usage patterns of `ia_download.py` with `argparse` and while `argparse` generally is a lot easier and more deterministically to work with, it is a major pain to replicate the exact behaviour we currently have.

When you want to have mutually exclusive arguments like in the 4 usage patterns, those have to be optional (starting with `-` or `--`).
Subparsers do not help the slightest bit either.
I could not find a decent way to get the required 1 or 2 positional arguments with the "optional arguments" as mandatory alternative to those.

**Comment by vxbinaca** [comment]
something between 2.0.3 and 2.1.0 broke Tubeup. So if we get more fixes, we make lock deps for 2.0.3 until a we fix it on our end or we find out what happened at least.
