### ISSUE TITLE
Download a folder of an item

### ISSUE THREAD

**Issue by vic60400** [jjjake/internetarchive#251]
Hi
Is it possible to just download a specific folder of an item ?

**Comment by jjjake** [comment]
Hi @vic60400, this should do it:

    ia download <id> --glob 'my_folder/*'

**Comment by vic60400** [comment]
Thx

**Comment by vic60400** [comment]
but this don't works 
`ia download <id> --glob 'my_folder/my_subfolder/*'`

**Comment by jjjake** [comment]
How doesn't it work? That should work just fine (I just tested myself).

Please provide the exact command your running into issues with if possible. Thanks!

**Comment by polyh3dron** [comment]
This should be added to the download --help flag, I came here also trying to find out the same thing.
