### ISSUE TITLE
Can't execute the binary due to encoding issue

### ISSUE THREAD

**Issue by B5045438** [jjjake/internetarchive#259]
When I try to execute the ia binary from the [website](http://internetarchive.readthedocs.io/en/latest/cli.html) using python 3, I get this error: 
`  File "ia", line 2
SyntaxError: Non-UTF-8 code starting with '\x83' in file ia on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details` 

I'm using Ubuntu 18.04 bionic.

**Comment by jjjake** [comment]
Thanks for the report @B5045438.

I'm unable to replicate on a fresh install of Ubuntu 18.04, with Python 2.7.15rc1.

What version of Python do you have installed? Can you confirm which binary you're using (i.e. did you use `https://archive.org/download/ia-pex/ia`)?

Would you mind re-downloading https://archive.org/download/ia-pex/ia, and giving it a try again?

Thanks again for the report!

**Comment by B5045438** [comment]
I tried to redownload it and it seems to have fixed the issue right away. Must have been caused by a corrupted download.
