### ISSUE TITLE
End of uploading produces error

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#260]
`ia upload Ninja_Tune_ZenTV_DVD VIDEO_TS --delete`

```
Traceback (most recent call last):
  File "/usr/local/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/cli/ia.py", line 159, in main
    sys.exit(ia_module.main(argv, session))
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/cli/ia_upload.py", line 225, in main
    for _r in _upload_files(item, files, upload_kwargs):
  File "/usr/local/lib/python3.5/dist-packages/internetarchive/cli/ia_upload.py", line 105, in _upload_files
    if responses and responses[-1] and responses[-1].status_code != 200:
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 675, in __bool__
    return self.ok
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 701, in ok
    self.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 932, in raise_for_status
    if 400 <= self.status_code < 500:
TypeError: unorderable types: int() <= NoneType()
```

I've managed to reproduce this twice including on a fresh item I squirted files into. This instance was just checking to see if anything was missing.

Edit: This could be related to the `--delete` flag.

**Comment by jjjake** [comment]
@vxbinaca I just got this error in `ia upload` without `--delete`... I'm not sure what's causing it yet, but I have a hunch it's a connection error of sorts (e.g. the connection closes before a status_code is set?).

I'll keep you posted. Please let me know if you continue to run into this issue. If you're able to send along a timestamp (even if it's an estimate) along with the identifier, that would be helpful.

**Comment by jjjake** [comment]
I found the issue @vxbinaca.

You were right that this was an issue with `--delete`, and also with `--checksum` (`--delete` sets `--checksum` to True).

The issue was that when a file already exists in the item (based on checksum), no request is sent and an empty `requests.Response()` object is returned. For some reason calling `r.ok` on an empty Response object works just fine in PY2, but not PY3.

Are you able to install from the master branch, and give this patch a try?

**Comment by vxbinaca** [comment]
I got the issue only with `--delete` so I edited the issue. I'll give it a try in a bit and comment back here.

Glad I could help you find a bug.

**Comment by vxbinaca** [comment]
It's good push it to pypi. Thanks for stomping that bug, Jake.
