### ISSUE TITLE
Is it possible to upoload MARCXML files (or data)

### ISSUE THREAD

**Issue by GrazingScientist** [jjjake/internetarchive#263]
Hi,

I want to upload books automatically for BHL (Biodiversity Heritage Library) and they demand a MARCXML file in the metadata of the Internet Archive. Is it possible to upload this with the script?

Thanks!

**Comment by jjjake** [comment]
@GrazingScientist Yup, just upload it like you would any other file.

We will derive metadata from the MARC record, if it's named in a specific format. From our FAQ:

> A MARC record will populate an item as soon as the item derives if the MARC file is named correctly. If it's a binary (ISO 2709) MARC, it should be called {itemID}_meta.mrc, If it's MARCXML, it should be called {itemID}_marc.xml.

Keep in mind that any metadata you add during upload may be overwritten with metadata from the MARC record after the item is derived.

Please feel free to email me if you need further help with this (my email is on my profile). Thanks!
