### ISSUE TITLE
ia move crashes with a NameError when x-archive-keep-old-version header is not specified

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#265]
`ia move` is broken because the `headers` variable is undefined. If the `x-archive-keep-old-version` header is specified on the command line, the relevant code is not called, and so that can be used as a workaround. The problematic commit is f02f06c8 (#248).

    Traceback (most recent call last):
      File ".../bin/ia", line 11, in <module>
        sys.exit(main())
      File ".../lib/python3.4/site-packages/internetarchive/cli/ia.py", line 159, in main
        sys.exit(ia_module.main(argv, session))
      File ".../lib/python3.4/site-packages/internetarchive/cli/ia_move.py", line 66, in main
        headers['x-archive-keep-old-version'] = '1'
    NameError: name 'headers' is not defined

Python 3.4 on Debian Jessie

**Comment by jjjake** [comment]
Fixed in f087789e391cae41279e937064d8b2456d306c5d, will ship in the next release. Thanks for the heads up!

**Comment by AGSPhoenix** [comment]
@jjjake When will the next release be? This bug has been fixed for 6 months, and is still present in the most recent release.
