### ISSUE TITLE
Option to preserve directory structure when uploading individual files

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#266]
As I learnt today, the directory structure is flattened when uploading individual files using `ia upload`. For example, when you `ia upload some_identifier dir1/file dir2/file`, the item ends up with `dir2/file` as `file` in the main directory and `dir1/file` in `history/files/file.~1~` due to the clobbering.

I'm aware that `ia upload some_identifier dir1 dir2` should upload the entire directories (though I didn't try this), but as far as I can see in the documentation, it's currently not possible to get the same effect uploading only select files from the directories. It would be nice to have a `--preserve-directory-structure`-like option to `ia upload`.

**Comment by jjjake** [comment]
I would recommend using `ia upload some_identifier dir1`, or `ia upload some_identifier file.txt --remote-name original/path/file.txt`.

**Comment by JustAnotherArchivist** [comment]
I'm aware of those options, but neither are what I'm trying to achieve. My goal is to upload multiple files in – but **not** all files from – subdirectories preserving the directories. Your first command will upload the entire directory, and the second only works for single files I think.

**Comment by sjackman** [comment]
@JustAnotherArchivist Did you find a workaround for this issue? I've tried both `ia upload --file-metadata=…` and `ia upload --spreadsheet=…`, and neither preserve directory structure.

**Comment by JustAnotherArchivist** [comment]
@sjackman Not really, apart from creating the desired directory structure with hardlinks, but that's very annoying.

**Comment by JustAnotherArchivist** [comment]
@jjjake Can this be reopened please? As explained above, there is no way to achieve the desired behaviour currently.

**Comment by sjackman** [comment]
```bash
curl -H "Authorization: AWS $access:$secret" --upload-file "$file" "http://$item.s3.us.archive.org/$directory/$file"
```
Uploading a single file to the Internet Archive S3 API using `curl` preserves directory structure!

**Comment by jjjake** [comment]
@sjackman Yes, this is equivalent to:

```ia upload $item $file --remote-name $directory/$file```

**Comment by jywarren** [comment]
Just noting - i found `--keep-directories` is now an option!

https://github.com/jjjake/internetarchive/blob/6e2321652ab2bd13c517dabf5a6e01f420bca380/internetarchive/cli/ia_upload.py#L61
