### ISSUE TITLE
Debian packaging in progress

### ISSUE THREAD

**Issue by anarcat** [jjjake/internetarchive#270]
Hi!

This is a friendly notice to let you know that [Debian](https://debian.org/) is working on packaging your software for Debian. You can follow the progress of that work in [bug #909550](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909550) in the Debian Bug Tracking System (BTS).

The source code for the Debian package is in [this git repository](https://salsa.debian.org/python-team/modules/python-internetarchive/). It will be uploaded into Debian shortly, at which point it will end up in the [NEW queue](https://ftp-master.debian.org/new.html) for legal review. Once the NEW process is completed, it takes about 10 days for the package to trickle down into "testing", which will become the next Debian release. This means your software will eventually be shipped in a "long term support" release, which last from three to five years, according to the [current statistics](https://wiki.debian.org/DebianReleases#Production_Releases).

If you are interested in maintaining the package yourself upstream, that is definitely possible. You can either upload the package yourself if you are a Debian member or I can act as a sponsor when a new release is published.

This is just a notification, but can also act as a coordination point for upstream packaging if you wish to followup on this. otherwise, feel free to close this issue whenever you like.

Have a nice day!

**Comment by anarcat** [comment]
package has been shipped with Debian buster, congrats! I will just close this now as there's nothing else to do...

**Comment by jjjake** [comment]
Thank you @anarcat!
