### ISSUE TITLE
Resume Upload?

### ISSUE THREAD

**Issue by edsu** [jjjake/internetarchive#276]
I was uploading a directory of 300GB of data, and things worked fine for a day and a half, but then it stopped with an exception:

```
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))
```

I was wondering if there is an easy way to resume the upload without reuploading all the content that already landed safely? I suppose a checksum of the data could be calculated locally and then checked against what is stored in the IA item?

If this seems of interest I could try adding it and send you a pull request.

**Comment by jjjake** [comment]
@edsu You can use the `--checksum` or `checksum=True` options. You must wait until all tasks in the item have finished running though. This is to avoid race conditions.

**Comment by edsu** [comment]
Oh, nice! I totally missed the fact that `--checksum` and `checksum=True` would work for uploading as well as downloading. This is a really super module, thanks for creating it!
