### ISSUE TITLE
item.modify_metadata not working

### ISSUE THREAD

**Issue by emijrp** [jjjake/internetarchive#283]
I am running a script which uploads several files into the same item.

It includes a line calling to item.modify_metadata(md) to refresh metadata. I have launched the script several times, but the metadata is never updated, it keeps the same info added in the first run.

No metadata is refreshed (description, tags, etc).

**Comment by jjjake** [comment]
Can you provide an example of an item you tried this on? What does the response body look like? Is a 200 status code returned? Thanks for reporting!

**Comment by emijrp** [comment]
@jjjake OK, I was getting a Response 400 because my metadata included "mediatype". It can't be changed.
