### ISSUE TITLE
No `brew install pip`

### ISSUE THREAD

**Issue by daylightbrightledlight** [jjjake/internetarchive#285]
The line in https://github.com/jjjake/internetarchive/blame/c28ff59894b635c87db754f10e487388af9f4ca1/docs/source/installation.rst#L39 should be modified/updated.

The formula "pip" is not available on Homebrew.
`brew install pip` will not work.

**Comment by DrTexxOfficial** [comment]
@daylightbrightledlight What command should be used instead?

**Comment by jakewilliami** [comment]
@DrTexx `brew install python` installs `pip` with it.
