### ISSUE TITLE
README documentation link is dead

### ISSUE THREAD

**Issue by markwkidd** [jjjake/internetarchive#286]
The README includes this text: 
> Documentation is available at https://archive.org/services/docs/api/internetarchive

This link is dead. I'll be looking for documentation, but at the moment I don't know where any is so I can't submit a PR to fix this.

**Comment by thiDucTran** [comment]
running `ia help` gives you the link `https://internetarchive.readthedocs.io/en/latest/cli.html`

**Comment by markwkidd** [comment]
Thanks @thiDucTran . I have submitted a PR to correct the link: https://github.com/jjjake/internetarchive/pull/287

**Comment by markwkidd** [comment]
Thanks @thiDucTran . I have submitted a PR to correct the link: https://github.com/jjjake/internetarchive/pull/287

**Comment by jjjake** [comment]
The original link is working again. Thanks for the heads up.
