### ISSUE TITLE
Impossible to download "search text contents" results

### ISSUE THREAD

**Issue by nihelmasell** [jjjake/internetarchive#291]
Hi, I tried to download the results of search done by "search text contents" option on the webpage and pass the &sin=TXT option into the parameters arguments, without successful results. How can you grab all the archive´s material containing a word via this script? Is it possible? TIA

**Comment by jjjake** [comment]
This is not currently supported in the command-line tool/Python lib, and there is not currently a public API for it. Hopefully we can support this in the future, though!

The best you could do at the moment is download the full-text from a selection of items that you'd like to search. Here's a simple example for a single item:

    » ia download goodytwoshoes00newyiala goodytwoshoes00newyiala_djvu.txt --stdout | grep -i apple-pie
    " Apple-pie," said Polly ; upon which she laid down the

A more thorough example:

    # Download the full-text for all items matching a given search query.
    » ia download --search 'collection:yrlsc AND format:DjVuTXT' --format 'DjVuTXT'
    # Grep the downloaded files.
    » grep -i farm */*

Hope this helps.
