### ISSUE TITLE
Add indication for 503 Slow Down Spam error.

### ISSUE THREAD

**Issue by Basillica85** [jjjake/internetarchive#298]
Some items fail to upload because they have been marked as spam, but the script treats this situation as a simple server overload, so it retries indefinitely. Maybe it would be possible to detect this by verifying whether the request queue is full, or through whatever means allows the browser uploader to give a unique message when an upload has been marked as spam.

**Comment by jjjake** [comment]
@Basillica85 do you have an example item, so I can take a closer look and try to replicate this issue?

**Comment by jjjake** [comment]
I was able to replicate this, and it's an issue with the archive.org S3-like API. I've passed along the issue to our developers who work on this API.

We hope to get it fixed soon, thanks for reporting.

**Comment by Basillica85** [comment]
Sorry I didn't respond, I had trouble fabricating an item that would trigger the spam filter (as I had already contacted support for the item I had this problem with). I really appreciate the effort you and the rest of the team put into the archive. Thank you.

**Comment by XXLuigiMario** [comment]
This is still an issue and should be reopened. See https://github.com/bibanon/tubeup/issues/135

**Comment by vxbinaca** [comment]
I don't want to make a dupicate issue, so I'll report I'm having a problem with the item:

youtube-jtG1niwwV9A

S3 errors and it appears duplicatable for days.

**Comment by nemobis** [comment]
I have the opposite issue (in version 2.3.0): since the error 503 is temporary, I'd like the upload to be retried. Instead, I get an exception, where it would be enough to retry one time with a generous wait time, possibly multiple minutes. 

Just giving up and throwing an exception makes it more complicated to make sure all my files were uploaded correctly, because I have to implement all the completion checks and retrying myself.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/internetarchive/item.py", line 1091, in upload_file
    response.raise_for_status()  
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status       
    raise HTTPError(http_error_msg, response=self)                                                                    
requests.exceptions.HTTPError: 503 Server Error: Slow Down for url: https://s3.us.archive.org/ ...                                                                                                                                                                                                                                                         
During handling of the above exception, another exception occurred:
                                                                                                                      
Traceback (most recent call last):
...                        
  File "/usr/local/lib/python3.10/site-packages/internetarchive/api.py", line 289, in upload
    return item.upload(files,                                                                                         
  File "/usr/local/lib/python3.10/site-packages/internetarchive/item.py", line 1260, in upload
    resp = self.upload_file(body,
  File "/usr/local/lib/python3.10/site-packages/internetarchive/item.py", line 1117, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading , Please reduce your request rate. - Your upload of ... appears to be spam. If you believe this is a mistake, contact info@archive.org and include this entire message in your email.

During handling of the above exception, another exception occurred:
```
