### ISSUE TITLE
How to download by uploader???

### ISSUE THREAD

**Issue by gabriellluz** [jjjake/internetarchive#301]
Hi.

I'm trying to download items by a specific uploader and I can't. Can you inform the command in order to do that?

I've tried:
`ia download --search 'uploader:nameofuploader''`

It doesn't work.

**Comment by jjjake** [comment]
@gabriellluz You need to use the email address associated with the account, for example:

    ia download --search 'uploader:foo@example.com'

**Comment by gabriellluz** [comment]
Thanks, my friend.
