### ISSUE TITLE
ia upload --metadata="topic: ..." ignores links

### ISSUE THREAD

**Issue by tenleftfingers** [jjjake/internetarchive#305]
When I use the web client, I can paste in links (like` <a href="somewhere.com">click here</a>`). But with the ia upload command, that html is ignored. I also tried a straight string: http://somewhere.com but it is not 'clickable'.

The 'description' metadata option is described[1] as "String, can contain links, formatting and images in html/css". 

Is the former type possible (`<a href...`)? It's the format I've been using for previous manual uploads. Many thanks.

1: https://archive.org/services/docs/api/metadata-schema/

Full command was like this:
`$ ia upload S00_Ea_Test_Upload Deasc/rob.ogg Deasc/pic.jpeg --metadata="mediatype:audio" --metadata="collection:opensource_audio" --metadata="date:2019-08-06" --metadata="title:S00 Ea Test Upload" --metadata="language:english" --metadata="licenseurl:https://creativecommons.org/licenses/by/4.0/" --metadata="subject:Technology" --metadata="subject:Retro Games" --metadata="subject:Vintage Computing" --metadata="subject:Music" --metadata="subject:Events" --metadata="subject:Commodore" --metadata="subject:Amiga" --metadata="topic:In this episode ...<br><br>Something with a <a href="http://amigausers.ie">link in it</a> just to test."`

**Comment by jjjake** [comment]
It looks to me like you might have quoting issues.

I'm unable to replicate this, for example:

    » ia upload jj-test-2019-08-06 foo.txt -m 'description:In this episode ...<br><br>Something with a <a href="http://amigausers.ie">link in it</a> just to test.'

That command created this item: https://archive.org/details/jj-test-2019-08-06

It doesn't look like `S00_Ea_Test_Upload` was ever created either, so I'm guessing this is an issue with your quoting. You should wrap your values in single quotes, or escape your double quotes.

**Comment by tenleftfingers** [comment]
Thank you so much for taking the time to trouble shoot this. I'll work on my syntax.
