### ISSUE TITLE
./ia help (URL in help file points to old readthedocs address)

### ISSUE THREAD

**Issue by hobbsy** [jjjake/internetarchive#306]
if you run:

$ curl -LO https://archive.org/download/ia-pex/ia
$ chmod +x ia
$ ./ia help

at the end of the help file it points to an old 404 URL

> Documentation for 'ia' is available at:
> 
>     https://internetarchive.readthedocs.io/en/latest/cli.html
> 
> See 'ia help <command>' for help on a specific command.

I think this should be either:
https://archive.org/services/docs/api/internetarchive/
or
https://archive.org/services/docs/api/internetarchive/cli.html

**Comment by jjjake** [comment]
Thanks for reporting! This was fixed here, and will be in the next release:

https://github.com/jjjake/internetarchive/commit/be68728c
