### ISSUE TITLE
Cannot move directories.

### ISSUE THREAD

**Issue by vext01** [jjjake/internetarchive#308]
Hi,

I don't seem to be able to move *directories* using `ia`.

```
$ ia list softdev_renaissance_analysis
...
v0.1/linux1_1240v5/renaissance_linux1_1240v5-0.1.envlogs.tar.bz2
v0.1/linux1_1240v5/renaissance_linux1_1240v5-0.1.json.bz2
v0.1/linux1_1240v5/renaissance_linux1_1240v5-0.1.krun
...
```

I want to move that `0.1` dir into a new dir called `runs`. I'm unable to do this using the web interface (https://archive.org/post/1103068/cant-move-a-directory-in-an-item), so let's try with `ia`:

```
$ ~/.local/bin/ia move softdev_renaissance_analysis/v0.1 softdev_renaissance_analysis/runs/v0.1
https://archive.org/download/softdev_renaissance_analysis/v0.1 does not exist. Please check the identifier and filepath and retry.
usage:
    ia move <src-identifier>/<src-file> <dest-identifier>/<dest-file> [options]...
    ia move --help
```

The error is incorrect. The URL does exist. I suspect it's actually upset that `runs` doesn't exist. I don't see any way to make a new directory...

**Comment by JustAnotherArchivist** [comment]
As far as I know, directories don't really exist in that sense on IA. You can't interact with them at all. For example, you can't delete a directory either; instead, you delete all files in a directory, and then the dir automatically vanishes as well.

So try this instead for each file in v0.1:

    ia move softdev_renaissance_analysis/v0.1/linux1_1240v5/renaissance_linux1_1240v5-0.1.krun softdev_renaissance_analysis/runs/v0.1/linux1_1240v5/renaissance_linux1_1240v5-0.1.krun

**Comment by vext01** [comment]
So, this works:
```
$ for i in `~/.local/bin/ia list softdev_renaissance_analysis | grep -e '^v0.1'`; do ~/.local/bin/ia move softdev_renaissance_analysis/$i softdev_renaissance_analysis/runs/$i; done
```

But it'd be nice if `ia` had some way to make that simpler.

**Comment by jjjake** [comment]
The for-loop is the recommended resolution to this. This could be handy, but it doesn't really make anything more efficient. No plans to support this at the moment.
