### ISSUE TITLE
500 Internal Server Error when using copy or move commands on files with a space in name

### ISSUE THREAD

**Issue by 84L7H13R** [jjjake/internetarchive#311]
Just as the title of this issue says, I get a 500 error if I run a command such as:

ia copy "internet.archive.bug.testing.page/test doc2.txt" "internet.archive.bug.testing.page/testdoc3.txt"

But for this:

ia copy "internet.archive.bug.testing.page/testdoc.txt" "internet.archive.bug.testing.page/test doc2.txt"

It works fine.  It seems I can copy to a new file with spaces in the name, but not from one.  Attempting to move a file with spaces results in a 500 error too, and looks like this (sorry for the bad paste from the cmd window):

error: failed to copy "internet.archive.bug.testing.page/test doc2.txt" to "inte
rnet.archive.bug.testing.page/testdoc3.txt" - <!DOCTYPE HTML PUBLIC "-//IETF//DT
D HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 info@archive.org to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at s3.us.archive.org Port 80</address>
</body></html>

I didn't bother reporting this to info@archive because nothing is ever done when I do.  In the meantime I am going to test other filenames containing characters such as !,[,],(,),etc, to see if they are affected as well, and will edit this issue if I find anything.  Also worth noting I managed to copy a gif file from a buddy's archive to my testing page that doesn't have spaces or special characters and that worked.

EDIT-

After more testing, I found some other bugs.  Results with percent symbol:

C:\Windows\system32>ia copy "internet.archive.bug.testing.page/test%.txt" "internet.archive.bug.testing.page/test2/testb1.txt"
error: failed to copy "internet.archive.bug.testing.page/test%.txt" to "internet.archive.bug.testing.page/test2/testb1.txt" - We encountered an internal error.
Please try again.

But the opposite works:

ia copy "internet.archive.bug.testing.page/testb1.txt" "internet.archive.bug.testing.page/test2/test%.txt"

And the semicolon is buggy in a different way:

C:\Windows\system32>ia copy "internet.archive.bug.testing.page/test;s.txt" "internet.archive.bug.testing.page/test2/test;s.txt"
error: failed to copy "internet.archive.bug.testing.page/test;s.txt" to "internet.archive.bug.testing.page/test2/test;s.txt" - Invalid Argument - x-(amz|archive)amz-copy-source refers to missing object: '/internet.archive.bug.testing.page/test;s.txt'

But this works, sort of:

C:\Windows\system32>ia copy "internet.archive.bug.testing.page/test.txt" "internet.archive.bug.testing.page/test2/zzzz;s.txt"

I say "sort of" because it says "success" but when I check the file it appears as just "zzzz".  The semicolon and everything after get dropped from the name.  I even tried escaping the character in various ways and no luck.

The browser version of the file manager does not have these problems, except for an error with the ampersand character which I reported many times on the forum and to info@archive in the past 2 months causing an error message "filename seems to no longer exist" and has never been addressed or fixed.

**Comment by jjjake** [comment]
This should now be fixed in v1.9.1, which I hope to release soon. Thanks for the report!

**Comment by 84L7H13R** [comment]
No problem.  Glad you took care of it. :D
