### ISSUE TITLE
What is the Rate Limit?

### ISSUE THREAD

**Issue by lethargilistic** [jjjake/internetarchive#312]
### Issue
Recently, I used the Python library to upload a bunch of podcasts to the Archive and I hit the rate limit. I expected this might happen, but the details of rate limiting were not mentioned in the documentation, so I figured I'd find out. This would have been fine, except that the automatic upload API ban for exceeding the rate limit lasted *two weeks*. Archive staff tried to help, but 1) neither of us was expecting the ban's length to be two weeks, and 2) they expected the python upload API and the website upload API to run on the same rate limiting system, which they do not.

### Request
Can you please add a section to the documentation that details exactly what the rate limit policy is? If the ban is that disruptive, users have to be aware of what the rules are upfront.

Building the policy into the code would be a more advanced option, but it would still be better to make the rules explicit.

(P.S: There is a portion of the IA-S3 documentation that mentions the HTTP headers that provide rate limiting status updates, but those are not accessible while using the upload API in Python.)

**Comment by saper** [comment]
That's weird, archive.org staff does not know...?

**Comment by lethargilistic** [comment]
Everybody has gaps. It happens. ^^

**Comment by jjjake** [comment]
The Python lib does not have any rate-limiting. All rate-limiting is coming from our S3-like API. The rate-limiting from our S3-like API is dynamic and changes often, but if you're getting a 503 the solution is to simply retry until you don't (In the Python API, use the `retries` param).

We do not ban anyone from using the S3-like API based on them exceeding our rate-limits. I'm not sure what happened to your account, but you were not banned for exceeding the rate-limits -- that is not something that we do.

Please reach out to info@archive.org, or email me directly (my email is on my profile), to see what's up with your account.

Our S3-like API usage limits are documented at https://archive.org/services/docs/api/ias3.html#use-limits. If you'd like changes to this documentation, please email info@archive.org.

**Comment by lethargilistic** [comment]
I don't mean to be glib, but `retries` is not the solution to a problem that takes two weeks to fix itself.

And, by "banned," I meant the rate limiting prevented me from uploading anything else through the Python API.

Which has happened again, even with the rudimentary delaying I wrote into my code because the actual rules are not documented anywhere.

So I guess I'll wait two more weeks. This is a serious usability issue.

**Comment by bejucoo** [comment]
I recently had the the same issue. After some uploads, I reached the rate limit and coudn't upload more items.
