### ISSUE TITLE
Partially OT: is it possible via API to or CLI to save a page and force also outlinks?

### ISSUE THREAD

**Issue by aborruso** [jjjake/internetarchive#314]
Hi,
in the new great "Save Page Now" webpage https://web.archive.org/save/, it's possible to check "save outlink"s option.

Is there a way to ask it via API to or CLI?

Thank you

![image](https://user-images.githubusercontent.com/30607/69358759-a9f8e200-0c87-11ea-94f3-238955651fa3.png)

**Comment by vbanos** [comment]
Thank you for your interest in Save Page Now. We will contact you via email about this. Its not public yet.

In our relevant blog post : http://blog.archive.org/2019/10/23/the-wayback-machines-save-page-now-is-new-and-improved/ we mentioned that:

_And, yes, of course SPN has a brand new API that you can use to automate a range of Web archiving projects. Please write to us at info@archive.org if you would like to learn more about the API._

**Comment by jjjake** [comment]
Thanks @vbanos! I'm closing this, but feel free to reach out to us if you need @aborruso. My email is on my profile, if you have trouble getting connected to the right person.

**Comment by aborruso** [comment]
Thank you to all

**Comment by mhucka** [comment]
I would be very interested in finding out more about this as well.
