### ISSUE TITLE
Skipping already-downloaded files doesn't work on FAT32

### ISSUE THREAD

**Issue by wfrantz** [jjjake/internetarchive#321]
I'm on Windows 10 with Python 3.7.3 and version 1.9.0 of the internetarchive package.

To reproduce the issue, run `ia download <Internet Archive identifier>` from a FAT32 volume and wait for at least one file to finish downloading before cancelling. Now run the same command again and observe that the client clobbers the already-downloaded file(s) (as if the `--ignore-existing` flag had been passed) and starts from scratch.

Maybe this is an issue with FAT32 not having enough timestamp precision to exactly match the archive.org timestamps?

**Comment by jjjake** [comment]
I would recommend using the `--checksum` option in this case.
