### ISSUE TITLE
Support streaming uploads

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#326]
It would be great if `ia upload` supported streaming uploads, e.g. reading from stdin or a FIFO, without using temporary files:

    some-process-generating-lots-of-data | ia upload identifier -

See #77 and #173 for example use cases. A further idea is directly piping [megawarc](https://github.com/alard/megawarc) output to IA instead of writing it to disk and then re-reading it (multiple times), massively reducing disk I/O.

An implementation would, as far as I can tell, require server-side support on IA S3 for chunked transfer encoding and trailers. The former is needed to avoid having to know the size in advance, the latter for `--verify` and `--delete` by computing the MD5 hash during the upload and sending the `Content-MD5` header at the end.

**Comment by TheSneakySniper** [comment]
Yeah, this would be a very useful feature.

**Comment by jjjake** [comment]
IA-S3 does not currently support streaming uploads, and there aren't any plans to as far as I know. I'm going to close the issue, but happy to revisit it if server-side support ever comes. If you have more questions about server-side support, please email info@archive.org. Thanks!

**Comment by mariomadproductions** [comment]
> IA-S3 does not currently support streaming uploads, and there aren't any plans to as far as I know. I'm going to close the issue, but happy to revisit it if server-side support ever comes. If you have more questions about server-side support, please email [info@archive.org](mailto:info@archive.org). Thanks!

I may be missing something, but couldn't this be done without server-side support by allowing the user to provide the size and md5sum as arguments? While I can think of some use cases where that may be an issue for the user, I can think of others where it wouldn't be.
