### ISSUE TITLE
Document permissions for modify_metadata

### ISSUE THREAD

**Issue by nemobis** [jjjake/internetarchive#327]
Since the IA library has existed, I've never once managed to use modify_metadata or metadata patches to update the metadata of any of my IA items. Perhaps I managed once in 2013 for some one-off project but the success was so rare that I forgot everything about it. In all other cases, I invariably get an error 400.

The highest priority bug/feature request is the ability for our tools to update a single field in the https://archive.org/details/wikiteam items, namely changing the "last-updated-date" field to a more recent date. We'd often also like to fix other fields such as "originalurl", but that invariably fails as well. We usually use https://github.com/WikiTeam/wikiteam/blob/master/uploader.py (which once used curl), but other methods have failed as well.

I have read https://archive.org/services/docs/api/metadata.html once again but I can't understand what changes one is supposed to be permitted. Trying smaller changes (one field at a time) or direct usage of the patch API doesn't seem to help.

**Comment by jjjake** [comment]
If you're referring to `item_last_updated`, that field is a system field and is not modifiable by anyone including admins.

If you needed a field like this for your own use, you could just add something like `last-updated-date` to meta.xml (e.g. `ia metadata <id> -m last-updated-date:2019`).

I'm curious why you haven't been able to modify metadata for any of your items, though. That seems odd. Please email me an example that is not working for you.

**Comment by nemobis** [comment]
jjjake, 10/02/20 20:04:
> If you needed a field like this for your own use, you could just add 
> something like |last-updated-date| to meta.xml (e.g. |ia metadata <id> 
> -m last-updated-date:2019|).

Yes, this is what we've been doing since forever, because the field then 
can be updated when we want (i.e. only when certain kind of updates are 
made on it). It works on the web interface but not on the API.

**Comment by jjjake** [comment]
@nemobis I'm not sure I understand the issue you're having. Please email me with more details, thanks!
