### ISSUE TITLE
Feature request: check upload permissions before uploading

### ISSUE THREAD

**Issue by voltagex** [jjjake/internetarchive#329]
```
PCPowerPlayDVD174:
 uploading PCPP 174 Side A.iso: [################################] 4444/4444 - 00:36:08
 error uploading PCPP 174 Side A.iso: Access Denied - You lack sufficient privileges to write to those collections
```

This was a 4GB upload... now wasted.

**Comment by jjjake** [comment]
S3 uses 100-continue (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) to handle this issue (i.e. it checks privs before consuming the request data). Unfortunately Python does not have 100-continue support, and archive.org doesn't have another way of checking if a user has privs required to upload to a given item.
