### ISSUE TITLE
Failed 'ia configure'

### ISSUE THREAD

**Issue by ElementO2512** [jjjake/internetarchive#332]
Hey,
Basically when i try to use the ia configure command it results in the following:
"Enter your Archive.org credentials below to configure 'ia'.
Email address: "
When I then try to enter my email address of username and hit enter it does nothing and doesn't ask me to input a password.
Any solution for this?

**Comment by jjjake** [comment]
@ElementO2512 Can you paste the entire output from your terminal? What do you mean when you say it does nothing, does your prompt return? I'm unable to replicate this, so any other information you're able to provide will be helpful. Thank you!
