### ISSUE TITLE
[docs] bulk upload example file "uploading.csv" incorrect

### ISSUE THREAD

**Issue by seritools** [jjjake/internetarchive#339]
I've encountered a problem with the example bulk upload csv file (linked [here](https://archive.org/services/docs/api/internetarchive/cli.html#bulk-uploading))
The file suggests that for adding multiple files to a single identifier/entry, you keep all other fields empty:

```csv
<identifier>,foo.txt,my description,first subject,second,,,foo bar,1999,test_collection
,foo2.txt,,,,,,,,
,foo3.txt,,,,,,,,
```

However, trying that you get this error on the second file:
```plain
error: no identifier column on spreadsheet!
```

It seems that the identifier field still has to be set, so either the example is incorrect or `ia` itself :P

**Comment by jjjake** [comment]
Good catch, thanks for the report @seritools! This is a bug, but in the meantime you can just add the identifier to each row.
