### ISSUE TITLE
automated generation of Torrent files?

### ISSUE THREAD

**Issue by Geremia** [jjjake/internetarchive#343]
I know that one can rederive with `ia tasks NAME -c derive.php`, but is there a way to automatedly generate Torrent files for items that lack one?

https://help.archive.org/hc/en-us/articles/360004715251-Archive-BitTorrents says:
>**My item does not have a torrent. How can I add one?**
>You would need to send a request to have a torrent generated to info@archive.org. Please include the URL of the item page.

**Comment by jjjake** [comment]
Please email info@archive.org for adding torrents to your items. Thanks!

**Comment by Geremia** [comment]
@jjjake Ok, thanks. I guess that's the only way.
