### ISSUE TITLE
ia search returns full datetime for date field instead of the actual value

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#345]
`ia search` always produces a full datetime in the date field:

```bash
> ia search archiveteam_archivebot_go_20200513020001 --field date
{"date": "2019-01-01T00:00:00Z", "identifier": "archiveteam_archivebot_go_20200513020001"}
```

The correct value for this particular item is `"2019"`, as returned by `ia metadata archiveteam_archivebot_go_20200513020001` for example.

**Comment by jjjake** [comment]
This is the value returned directly from the archive.org search engine. I think it's important to keep the results returned from the search engine unfiltered.

If you think this format should be changed, I would recommend contacting info@archive.org.

Thanks for the feedback, it's appreciated!
