### ISSUE TITLE
Do NOT calculate MD5 Hash?

### ISSUE THREAD

**Issue by TheSneakySniper** [jjjake/internetarchive#352]
Is it possible to not calculate the MD5 hash of a file before uploading?

This can be extremely taxing on hardware that needs to calculate hashes, such as a raspberry pi.

**Comment by TheSneakySniper** [comment]
Issues #77 and #173 seem to discuss this but a formal resolution was never reached.

**Comment by JustAnotherArchivist** [comment]
See #253. I believe that since commit 5ba8acb2/version 1.9.2, the hash should only be calculated if you have one of the checksum options (see that issue) active.

**Comment by TheSneakySniper** [comment]
Alright, thanks @JustAnotherArchivist
