### ISSUE TITLE
Derive queueing not working correctly

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#356]
I recently uploaded [139 items of WARCs](https://archive.org/details/@justanotherarchivist?and%5B%5D=collection%3Aarchivebot+addeddate%3A%5B2020-05-30+TO+2020-05-31%5D) using version 1.9.3. This was scripted, but the command was the same for all of them (without title and description for brevity):

`ia upload "${itemname}" * --sleep=120 --retries=100 --size-hint=${size} --metadata="mediatype:web" --metadata="description:<stripped>" --metadata="title:<stripped>" --metadata="collection:archiveteam_inbox" --metadata="creator:Archive Team" --metadata="noarchivetorrent:true"`

Note the absence of `--no-derive`, i.e. these should all have gotten a derive task queued automatically after the upload of the last file. However, this did not happen – not a single one of the items had a derive task.

(I can easily script queueing the derive tasks, but I'm leaving the items alone for now in case it's helpful for debugging.)

**Comment by siznax** [comment]
@jjjake looks like these tasks are NOT getting `next_cmd => derive` from the archive tasks

**Comment by jjjake** [comment]
Thanks for the report. This fix has already been addressed, and will ship in v1.9.4.

**Comment by JustAnotherArchivist** [comment]
Ah yes, saw commit a3e5c24c now. Thanks!
