### ISSUE TITLE
High CPU load when downloading

### ISSUE THREAD

**Issue by MerlijnWajer** [jjjake/internetarchive#362]
I'm seeing a high CPU load when downloading files.

I suspect the `chunk_size` here may cause some problems:

https://github.com/jjjake/internetarchive/blob/ff997fce87278ebd4b66a641de9c4f1ac09e61c1/internetarchive/files.py#L270

Any reason for picking `2048`? It's quite small - less than the typical page size.

And why `flush()` after every write? I would suggest to only do that once all writing is done: https://github.com/jjjake/internetarchive/blob/ff997fce87278ebd4b66a641de9c4f1ac09e61c1/internetarchive/files.py#L278

**Comment by jjjake** [comment]
How does this look, @MerlijnWajer: 473104c41aaa8ae2564f9389a9e1838cd5de9906

I used 1mb chunk size based on feedback from @samuel-archive. I also added a param for specifying your own `chunk_size`.

**Comment by MerlijnWajer** [comment]
Looks good. With the flush gone too, that's seems great to me, thanks!
