### ISSUE TITLE
Glob accepts multiple patterns

### ISSUE THREAD

**Issue by gleporeNARA** [jjjake/internetarchive#363]
Possibly just a question, rather than an issue, but I was not able to get the glob switch to accept multiple patterns for ia download. Does it only accept a single pattern?

One example of where this would be useful is in filtering by a format which uses multiple extensions (i.e. WAVE format could have a .wav, wave, .bwf, etc. extension.)

If it does accept multiple patterns, I can't figure it out.

**Comment by jjjake** [comment]
`*.wav|*.wave|*.bwf` should work. You could also use the format parameter (`ia download <id> --format=WAVE` or `>>> item.download(formats=['WAVE'])`).
