### ISSUE TITLE
Uploading does not work when uploading from stdin

### ISSUE THREAD

**Issue by TheSneakySniper** [jjjake/internetarchive#364]
IA Version: 1.9.4

This is a bug that occurs when I attempt to upload a file from stdin.

Here is the code.

`streamlink twitch.tv/xqcow best -v -O | ia --config-file iaconfigfile.ini upload testxqcowstreamfile1234 - --remote-name=testxqcowstreamfile1234 --metadata="title:Uploaded from stdin." -d`

Expected behavior: the program should upload the livestream from STDIN
Actual behavior: the program does not show any output, so we are unable to confirm whether or not the script is working. 
The program does not actually upload the file, either.

This is where it hangs.

![image](https://user-images.githubusercontent.com/20378538/86424678-0ac5af80-bc98-11ea-8434-ddb0fa8d6d68.png)

**Comment by TheSneakySniper** [comment]
When the program is let run until the end of the stream, it runs into a memory error.
[cli][info] Stream ended
[cli][info] Closing currently open stream...
Traceback (most recent call last):
  File "/home/sneakysniper/.local/bin/ia", line 11, in <module>
    sys.exit(main())
  File "/home/sneakysniper/.local/lib/python3.6/site-packages/internetarchive/cli/ia.py", line 168, in main
    sys.exit(ia_module.main(argv, session))
  File "/home/sneakysniper/.local/lib/python3.6/site-packages/internetarchive/cli/ia_upload.py", line 233, in main
    local_file.write(sys.stdin.read())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
MemoryError

**Comment by JustAnotherArchivist** [comment]
Duplicate of #326

**Comment by TheSneakySniper** [comment]
@JustAnotherArchivist Oh, alright.
