### ISSUE TITLE
Metadata in different language (arabic) is not updated properly. It shows in ????????? this format. 

### ISSUE THREAD

**Issue by khurram063** [jjjake/internetarchive#367]
Hi, 
I am trying to upload this document and the metadata is not correctly updated 

ia upload Qadiydsdsdwrfdfsfsdf22 "D:\tt.pdf"	--metadata="description:Qadi شاہد حمید (Author) رشید" --metadata="publishers:La irajia جیہ"

The text in the different language is not updated properly in archive.org. I shows as ??????? in this format. Any help where can I run the above command to make sure the metadata is properly updated. 

![image](https://user-images.githubusercontent.com/102712/90209441-ae7ea100-dda8-11ea-9d9b-9a36778acf64.png)

**Comment by jjjake** [comment]
This should work just fine, if everything is utf-8. For example:

```» ia upload jj-test-2020-08-14-3 ~/foo.txt --metadata collection:test_collection --metadata="description:Qadi شاہد حمید (Author) رشید" --metadata="publishers:La irajia جیہ"
jj-test-2020-08-14-3:
 uploading foo.txt: 100%|███████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.33MiB/s]```

https://archive.org/details/jj-test-2020-08-14-3

Based on your screenshot, it looks like there are some encoding issues of some sort. Make sure your input and environment is utf-8, and try again.

**Comment by khurram063** [comment]
Hi @jjjake, 
Thanks for responding. I see that you made it working. I am using command prompt and powershell in windows and it is still not working on that. I have tried the UTF-8 in both command prompt and powershell (you can see in the images attached). 

Which environment you were using that I can use in Windows environment?
Thanks


![image](https://user-images.githubusercontent.com/102712/90299784-aaa85880-de54-11ea-8ecc-e25c7043607e.png)

![image](https://user-images.githubusercontent.com/102712/90299745-89476c80-de54-11ea-9571-05271a6d2bae.png)

**Comment by jjjake** [comment]
Sorry you're still having issues with this @khurram063! I am using bash on a linux-like machine. Are you familiar with cygwin (https://www.cygwin.com/)? I would recommend giving cygwin a try if possible. Let me know how it goes!
