### ISSUE TITLE
Command line tool: how to add an array field?

### ISSUE THREAD

**Issue by aborruso** [jjjake/internetarchive#370]
Hi,
I would like an array field like this one

```
{
  "myField": [
    "value1",
    "value2"
  ]
}
```

How to add it via `ia`?

It's not `ia metadata myId --modify="myField:[value1,value2]"`

Thank you

**Comment by JustAnotherArchivist** [comment]
There's the `--append-list` option for array fields. However, I'm not sure if it's possible to have custom array fields.

**Comment by aborruso** [comment]
> There's the `--append-list` option for array fields. However, I'm not sure if it's possible to have custom array fields.

Yes it's possible, and I have set via bulk upload. I have in example

```
"numero": [
      "34",
      "34 bis"
    ]
```

for id `covid-19-cts-verbale-034-034bis-20200321_ia`.

And now I have tried with `--append-list` and it works too. Thank you very much

**Comment by jjjake** [comment]
@aborruso Note that you can also use something like `ia metadata myId --modify="myField:value1" --modify="myField2:value2"`. This is different than `--append-list` in that it will clobber instead of append.
