### ISSUE TITLE
Support for downloading large files (>2.0GB) from web archive?

### ISSUE THREAD

**Issue by nicolaipre** [jjjake/internetarchive#379]
Hi.

Does this project support downloading files indexed at web.archive.org, or does it only support "items" on archive.org? 

I have experienced that web.archive.org caps the download request once 2GB of data has been transferred. This means that when a user attempts to download an indexed file of 3GB in size, you would only get 2/3 of the file before you get capped. 

I have also contacted archive.org about this issue over email, but my question has apparently been ignored as I have not received an answer.

The same issue has been discussed years ago in https://archive.org/post/398124/the-2-gb-limit, but was then related to FTP. The same thing however seems to apply to HTTP requests. A user stated here that the browser had this limitation, but the same thing happens when attempting to download the file from a dedicated server with `wget` or `curl`. This indicates that a WAF or similar might be dropping connections that have transferred a certain amount of data.

I was hoping I could use this library to come around this "restriction" if possible.

**Comment by jjjake** [comment]
This tool does not currently support downloading files from the Wayback Machine, and there are not any plans to support this at the moment.

I'm not very familiar with the Wayback Machine, and am unable to help troubleshoot this issue, unfortunately. info@archive.org is your best bet.
