### ISSUE TITLE
Question about IA login without using this project

### ISSUE THREAD

**Issue by sgmihai** [jjjake/internetarchive#389]
Can the author or someone more knowledgeable with python post how you would get the login/session cookies of archive .org, providing the email/password for account. Using only simple wget/curl commands. (If possible at all?). I tried to look at the code but pythong is way too concise for me to understand what's going on : P
Thank you.

**Comment by jjjake** [comment]
Below is an example using `curl`. Note that this is considered a “new login” though, and is not merely fetching existing cookie signatures. I think for most purposes that shouldn't matter, but I just wanted to make note of it.

```
» curl --data access=chY7jL431N0Ub6aH --data secret=<redacted> --data email=jake@archive.org --data 'password=<redacted>' -XPOST 'https://archive.org/services/xauthn/?op=login'
{"success":true,"values":{"cookies":{"logged-in-sig":"<redacted>","logged-in-user":"jake%40archive.org; expires=Fri, 04-Feb-2022 18:33:22 GMT; Max-Age=31536000; path=/; domain=.archive.org"},"email":"jake@archive.org","itemname":"@jakej","s3":{"access":"chY7jL431N0Ub6aH","secret":"<redacted>"},"screenname":"jakej"},"version":1}
```
