### ISSUE TITLE
Upload files preserving directory structure and mtime timestamp

### ISSUE THREAD

**Issue by sjackman** [jjjake/internetarchive#390]
Hi! I'd like to upload a number of files, preserving directory structure and timestamp. Here's my test:
```bash
mkdir -p hello
echo 'Hello, world!' >hello/hello.txt
touch -d @1609502400 hello/hello.txt
echo '{ "name": "hello/hello.txt", "mtime": 1609502400 }' >hello.json
ia upload sjackman-hello --metadata="collection:test_collection" --file-metadata=hello.json
ia metadata sjackman-hello | jq '.files[0] | {name,mtime}'
```

### Observed
```json
{
  "name": "hello.txt",
  "mtime": "1613685532"
}
```

### Expected
```json
{
  "name": "hello/hello.txt",
  "mtime": "1609502400"
}
```

- I'd like `hello.txt` to be in the `hello/` directory.
- I'd like the `Last Modified` column of https://archive.org/download/sjackman-hello to show the desired time stamp of `2021-01-01T12:00UTC`, when this item was created.

Thanks for your help!

**Comment by sjackman** [comment]
```bash
echo '{ "name": "hello/hello.txt", "mtime": 1609502400, "date": "2021-01-01T12:00Z" }' >hello.json
ia metadata sjackman-hello-123 | jq '.files[0] | {name,mtime,date}'
```
```json
{
  "name": "hello.txt",
  "mtime": "1613687037",
  "date": "2021-01-01T12:00Z"
}
```
Setting the file metadata `date` works! The `date` metadata is not displayed in the web interface though at https://archive.org/download/sjackman-hello-123

Not preserving directory structure is unfortunately a known issue. https://github.com/jjjake/internetarchive/issues/266

**Comment by sjackman** [comment]
I successfully used `ia metadata hello-1234 -t files/hello/hello.txt -m date:2021-01-01T12:00Z` to set the metadata of a single file. Can `ia metadata --spreadsheet=…` be used to modify file metadata in bulk, perhaps using either a `file` or `target` column?

**Comment by jjjake** [comment]
Hi, @sjackman. Setting file-level metadata is not currently supported in spreadsheet mode, unfortunately. I don't believe `mtime` can be modified, but date is a good place for this type of metadata. For UI issues/feedback, please email info@archive.org.

Directory structure can be preserved like so:

```» ia upload jj-test-2021-02-22 foo.txt --remote-name foo/bar/baz/foo.txt -m collection:test_collection
jj-test-2021-02-22:
 uploading foo/bar/baz/foo.txt: 100%|███████████████████████████████████████████| 1/1 [00:00<00:00,  3.72MiB/s]
 » ia ls jj-test-2021-02-22
foo/bar/baz/foo.txt
jj-test-2021-02-22_archive.torrent
jj-test-2021-02-22_files.xml
jj-test-2021-02-22_meta.sqlite
jj-test-2021-02-22_meta.xml```
