### ISSUE TITLE
bug: cannot archive United Nations pdf files - cookie problem?

### ISSUE THREAD

**Issue by broukema** [jjjake/internetarchive#391]
I tried to archive both
* https://documents-dds-ny.un.org/doc/UNDOC/GEN/G18/336/28/PDF/G1833628.pdf and
* https://documents-dds-ny.un.org/doc/UNDOC/GEN/G18/336/28/PDF/G1833628.pdf?OpenElement

and what I got were:
* https://web.archive.org/web/20210227162052/https://documents-dds-ny.un.org/doc/UNDOC/GEN/G18/336/28/PDF/G1833628.pdf
* https://web.archive.org/web/20210227155850/https://documents-dds-ny.un.org/doc/UNDOC/GEN/G18/336/28/PDF/G1833628.pdf?OpenElement

Both of these web.archive URLs fail to give me an archived copy of the pdf. Instead there's a warning in red, "There is an end-user problem. If you have reached this site from a web link, - Through your internet options, adjust your privacy settings to allow cookies or - Check your security settings and make sure this site has not been blocked or ..."

This is the United Nations documents people's fault for not providing ordinary URLs, but the question is whether the Wayback Machine can handle this. It's a ridiculous situation where United Nations public documents cannot be archived...

My naive guess for a solution is to accept a cookie and send it back to the UN server to make it happy.

**Comment by jjjake** [comment]
Thanks for the report, @broukema! This repository is for the Internet Archive command-line tool, I suggest emailing info@archive.org with this issue. Thanks again, and I hope we can get this issue sorted for you soon.
