### ISSUE TITLE
ia upload error: no identifier column on spreadsheet!

### ISSUE THREAD

**Issue by jamiepb** [jjjake/internetarchive#395]
Hello,

I am new to using ia so apologize if this is a user error. I am using a csv spreadsheet to upload multiple files, based on the documentation and the spreadsheet template. I've attached the sheet I'm using, saved as txt. I keep getting the result "error: no identifier column on spreadsheet!" and I'm stumped because I do have an identifier column. I wanted to see if I could use the library on Windows 10 which is what my institution uses, and I don't know if that could have anything to do with it but I've been able to install ia and create the configuration file so I was hopeful it could work. Thank you.

Jamie Patrick-Burns
[uploading.txt](https://github.com/jjjake/internetarchive/files/6159322/uploading.txt)

**Comment by jjjake** [comment]
@jamiepb It looks like your spreadsheet is tab-separated? It needs to be a UTF-8 encoded CSV. I would also suggest using Cygwin or a similar unix-like terminal emulator for Windows.

Please email me with any other support questions (email is on my profile). Thanks!
