### ISSUE TITLE
Config file location defaults to `~/.ia` instead of `~/.config/ia.ini`

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#399]
I discovered today that my PR #324 inadvertently introduced a bug and changed the default config file path from `~/.config/ia.ini` to `~/.ia`. I didn't realise at the time that `write_config_file` uses `parse_config_file` to get the path to write to. If neither file exists, `parse_config_file` should return `~/.config/ia.ini`.

Possibly, this should only be the case if `~/.config` exists. Personally though, I think that the directory should just be created with `os.makedirs` if it doesn't exist as it has been the standard location for config files of any software for oh-so-many years now and home dir pollution is horrible. As that would be a deliberate functional change though, I'd like to hear @jjjake's thoughts on that first. (Will create a PR afterwards.)

**Comment by jjjake** [comment]
Thanks for catching, I'm rolling #324 back.
