### ISSUE TITLE
What is this "identifier"?

### ISSUE THREAD

**Issue by OrionRandD** [jjjake/internetarchive#404]
What is this identifier in ia --help?

examples:
    ia upload <id> <file> -H x-archive-keep-old-version:0  # Turn off backups

Is it my email? (password?), or other item...

**Comment by maxz** [comment]
The identifier is the name of the item or collection which you try to operate on.

**Comment by OrionRandD** [comment]
> The identifier is the unique name of the item or collection which you try to operate on.
> 
> It's listed among the metadata and on an item's details page and is distinct from the item's title.
> The identifier is among other things used to link to the item e. g. https://archive.org/details/isd2021-04-30 has the identifier `isd2021-04-30`.
> 
> See [Internet Archive Metadata: Archive.org Identifiers](https://archive.org/services/docs/api/metadata-schema/index.html#archive-org-identifiers) and [How Archive.org items are structured](http://blog.archive.org/2011/03/31/how-archive-org-items-are-structured/).

Thx :)
