### ISSUE TITLE
Can not search items uploaded by a user

### ISSUE THREAD

**Issue by lalitaalaalitah** [jjjake/internetarchive#409]
I was trying to search a user : devahindi. The search returns the identifier related to this user.
I don't have any clue how to search all PDF uploaded by this specific user. I tried to read the doc, but could not find any help there.
I tried to search on archive.org website. It also returns only user-page and doesn't show items uploaded by this user. Once I click the profile-page, then I'm able to see uploads by this specific user.
Please, clarify if it is possible to extract data for uploads by a specific user through this python tool or not?
If yes, please guide how to implement the solution.

**Comment by jjjake** [comment]
You can search for all of a users uploads using email address. For example:

```ia search 'uploader:(jake@archive.org)'```
