### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by moom0o** [jjjake/internetarchive#415]
Would it be possible to speed up uploading to the internet archive with multiple connections? I'm currently getting 6-8MiB/s on a gigabit server in Virginia, and can get speeds in the KiBs on gigabit servers in Germany. However I've had one provider (BuyVM) with pretty decent speeds to the internet archive (~40MiB's) and that server was in New York City.

**Comment by jjjake** [comment]
You can upload multiple files at the same time, see [the documentation](https://archive.org/services/docs/api/internetarchive/parallel.html) to get an idea of how you might do this. Please feel free to email me if you need more help with this.

To upload a single file with multiple connections, we'd need to add support for multi-part upload (which is something that I'm not sure we want to do right now, but it could be used in a separate script as it is supported by IA-S3).
