### ISSUE TITLE
Skipping an user's contribution when bulk-downloading a collection.

### ISSUE THREAD

**Issue by nihelmasell** [jjjake/internetarchive#421]
Hi, I'm facing the following issue when using this tool. I decided to mirror locally an IA collection. The collection has like 700 items, but one user created an item with thousands of files, some of them totally off-topic. I want to have the collection locally, in case it gets deleted from the Archive, but I don't want the other files. Is there any easy way to solve this? Best Regards.

**Comment by maxz** [comment]
This is not the right place for such enquiries.

And there is no direct functionality for this, but you should reach the same outcome by using a search download:
`ia download --search 'collection:your_collection AND NOT identifier:your_unwanted_identifier'`

**Comment by nihelmasell** [comment]
Thanks, and sorry!

**Comment by maxz** [comment]
Thank you. This is the right place for feature requests regarding the command line tool, but it seemed like a support request to me.

My proposed workaround also works with multiple identifiers.
You can extend it within the confines of the [supported search syntax](https://archive.org/advancedsearch.php).
It depends entirely on the details which you want to filter for.

Exclude multiple identifiers:
`ia download --search 'collection:your_collection AND NOT identifier:your_unwanted_identifier_1 AND NOT identifier:your_unwanted_identifier_2`

Exclude everything from user **Mr X**:
`ia download --search 'collection:your_collection AND NOT uploader:mr_xs_email_address`
The required address can retrieved from the metadata of one of his items.
E. g. if the item is `flash_badger` by going to [https://archive.org/metadata/flash_badger](https://archive.org/metadata/flash_badger) and getting the value of the `uploader` key.

**Comment by nihelmasell** [comment]
Thank you very much! I forgot the identifier field was open to any kind of metadata. Your reply was of inconmensurable help!
