### ISSUE TITLE
Download nested content from zip files

### ISSUE THREAD

**Issue by mittler-works** [jjjake/internetarchive#424]
Using a browser, you can click on the `(View Contents)` link for zip files in the Internet Archive. You will then get a list of files inside the zip archive and you can download individual files from the zip archive.
It would be great if this could also be done with the command line interface.

For example, in accordance to the usage synopsis: `ia download <identifier> [<file>]... [options]...`
it would be nice if `<file>` could be something in form of `big-archive.zip/individual-file.zip`
where `big-archive.zip` is a file of the `identifier` item and `indiviual-file.zip` is an individual file inside the `big-archive.zip`.

IIRC this is exactly the way, the links for browsers do work too:
`https://archive.org/download/<identifier>/<file>[/<nested-file>]...`

(Or does this already work and I just haven't found it?).

**Comment by jjjake** [comment]
`view-archive.php` was designed to be used in the browser for downloading a file or two, and is not really designed to be used programmatically. I could see the argument for an API that supported this being useful, but I think for most use cases using the browser to download a few files or downloading the whole ZIP is sufficient.

I'd be happy to support this, if there was an API. I'm closing this for now, as an API is not on the roadmap. I'd suggest emailing info@archive.org, if this is something you're interested in. Thanks for the feedback!
