### ISSUE TITLE
Unable to auth with Google Account

### ISSUE THREAD

**Issue by twig123** [jjjake/internetarchive#425]
I created my account on archive.org using the "Sign in with Google" option. Attempting to use `ia configure`, it will not accept any credentials that I give it. I've also tried resetting my Google account password with no luck.

Any suggestions would be appreciated.

**Comment by jjjake** [comment]
Thanks for the report! I'll look into this.

**Comment by jjjake** [comment]
Ok, the solution for this is creating a new archive.org password. To do this, use the https://archive.org/account/forgot-password link to generate a new password. Once you do this, `ia configure` should work with your google email address and the newly generated password. I'll update the documentation to note this. Thanks again for reporting this issue!

**Comment by twig123** [comment]
Confirmed. Both login to the site with user/pass and `ia configure` are now working after the "forgot password" reset.
