### ISSUE TITLE
Items are no longer associated with my account after changing email

### ISSUE THREAD

**Issue by soredake** [jjjake/internetarchive#431]
Hello, I've found a bug, when i changed my email in archive.org ALL my uploaded items are no longer associated with my account, I've seeing this behavior for an year, on main account and test account.

before changing email:
![изображение](https://user-images.githubusercontent.com/5204968/132701818-6e5b3332-242a-49ce-b018-34853195e539.png)

after:
![изображение](https://user-images.githubusercontent.com/5204968/132701853-610d5924-c66d-4bcf-8866-c2a2641a827d.png)

It's also reported here:
https://archive.org/post/1107183/problem-with-uploaded-items-no-longer-being-associated-with-account
https://archive.org/post/1114596/problem-with-uploaded-items-no-longer-being-associated-with-account

Sorry for offtopic, i tried emailing `info@archive.org` and they just moved items to my new email, bug is still not fixed.

**Comment by jjjake** [comment]
Unfortunately, this cannot be resolved within the command-line tool or Python library. `info@archive.org` is your best bet.
