### ISSUE TITLE
cant fix this

### ISSUE THREAD

**Issue by MesterPerfect** [jjjake/internetarchive#440]
C:\windows\system32>ia upload nacer "E:\GreyEveThemeV2.1.zip"
nacer:
 uploading GreyEveThemeV2.1.zip: 100%|██████████| 1/1 [00:00<00:00,  1.02MiB/s]
 error uploading GreyEveThemeV2.1.zip: Access Denied - This item has been taken
offline

C:\windows\system32>

**Comment by MesterPerfect** [comment]
code:
```
import internetarchive
item = internetarchive.Item('nvdasound')
file = internetarchive.File(item, 'exit.wav')
print(f.format, f.size)
# ('Cinepack', '3786730')
```
output
```
Traceback (most recent call last):
  File "C:\Users\MesterPerfect\Desktop\ia.py", line 2, in <module>
    item = internetarchive.Item('nvdasound')
TypeError: __init__() missing 1 required positional argument: 'identifier'
```

**Comment by maxz** [comment]
This is not a support forum for the Internet Archive or even for the usage of the library.

You are using `Item` completely wrong. The first argument to item is the current IA session.
If you use `get_item()` instead, you will reach your desired behaviour.

```
from internetarchive import get_item
item = get_item('nvdasound')
file = item.get_file('exit.wav')
print(f.format, f.size)
```

See the [documentation for the developer interface](https://archive.org/services/docs/api/internetarchive/api.html#item-objects).

Please read the documentation to avoid similar problems in the future.

**Comment by maxz** [comment]
As stated in `CONTRIBUTING.rst`: Please don't use the GitHub issue tracker for asking support questions. All support questions should be emailed to [info@archive.org](mailto:info@archive.org?subject=[IA-Wrapper]).

Alternatively you could try stackoverflow.com, which I personally would recommend.
Stackoverflow has the advantage that other people can later find your questions and their answers.
The GitHub issue tracker is not really built with such discoverability in mind and when using the email path, the answers won't help anyone but you.

**Comment by MesterPerfect** [comment]
ok, thanks
