### ISSUE TITLE
[Cygwin] Download file when using --glob

### ISSUE THREAD

**Issue by khaoniaomamuang** [jjjake/internetarchive#442]
Why does download also fail if I used --glob tag?

`Example_file (1/108):  - download failed`

Here is my command:

`ia download --itemlist itemlist.txt --glob='*.epub'` 
I tried to use `"*.epub"`, `\*.epub` and many others and it still fails. The file has .epub as a download option.

F.Y.I I used cygwin64.

Thanks.

**Comment by jjjake** [comment]
Can you send me a copy of your itemlist? I'm unable to reproduce this in Cygwin with the latest version of `ia`. Thanks for the report!

**Comment by SkillzGamingYT** [comment]
Hello, it seems that the item does have .epub listed on the website (I was able to download it manually) but ia won't download .epub file even when not restricting any file type.
`Color_and_Light_James_Gurney_English` is one that won't work.
