### ISSUE TITLE
v2.2.0 tag not pushed to master?

### ISSUE THREAD

**Issue by anarcat** [jjjake/internetarchive#448]
it looks like that tag was pushed but not on the master branch.

```
$ git clone --quiet https://github.com/jjjake/internetarchive.git
$ git log -1
commit af7d60983e0ce5d05ff6a0d1ba63faddf245423f (HEAD -> master, origin/master, origin/HEAD)
Author: jake <jake@archive.org>
Date:   Tue Nov 23 12:05:50 2021 -0800

    badge updates
$ git log --decorate --all  --oneline -2
8a08e75 (tag: v2.2.0) v2.2.0
af7d609 (HEAD -> master, origin/master, origin/HEAD) badge updates
```

i think the fix is:

```
git checkout master
git merge v2.2.0
git push
```

**Comment by anarcat** [comment]
i think this happened again.

**Comment by anarcat** [comment]
hum and i can't reopen this issue, and i can't find the 2.3.0 tag anywhere...

**Comment by JustAnotherArchivist** [comment]
Actually, the tag is there, as are the commits, but the master branch wasn't pushed.

https://github.com/jjjake/internetarchive/commit/e3130ac329e210689b9c81e85e41b3c13e36116d

@jjjake

**Comment by anarcat** [comment]
yeah, same as last time :)

**Comment by anarcat** [comment]
i hate to be that guy again, but you forgot to push the master branch in 3.3.0 again :p

**Comment by anarcat** [comment]
On 2022-03-21 08:54:24, JustAnotherArchivist wrote:
> Looks fine to me (well, v3.0.0, not 3.3.0). Or was it pushed in the past 25 minutes?

oh, i see it now, nevermind sorry.

-- 
Either you're with us or you're with the terrorist state.

**Comment by jjjake** [comment]
@anarcat Thanks again for keeping an eye on this. :)

Just to confirm, everything is good now? This is the current Makefile target I use to publish. Please let me know if anything should be changed:

```
publish:
        git tag -a v$(VERSION) -m 'version $(VERSION)'
        git push --tags
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://upload.pypi.org/legacy/ --repository testpypi dist/internetarchive-$(VERSION).tar.gz
```

**Comment by anarcat** [comment]
On 2022-03-21 10:50:38, jjjake wrote:
> @anarcat Thanks again for keeping an eye on this. :)
>
> Just to confirm, everything is good now? This is the current Makefile target I use to publish. Please let me know if anything should be changed:
>
> ```
> publish:
>         git tag -a v$(VERSION) -m 'version $(VERSION)'
>         git push --tags
>         python setup.py sdist bdist_wheel
>         twine upload --repository-url https://upload.pypi.org/legacy/ --repository testpypi dist/internetarchive-$(VERSION).tar.gz
> ```

lgtm.
-- 
They say that time changes things, but you actually have to change
them yourself.           - Andy Warhol

**Comment by JustAnotherArchivist** [comment]
`git push --tags`, per the man page:

> All refs under refs/tags are pushed, in addition to refspecs explicitly listed on the command line.

So that's why the `master` branch doesn't get pushed.

A plain `git push` implicitly adds the current branch at the end (normally, though it can be changed via config files), but that's disabled when `--tags` (or some similar option) is used. Listing the branch and remote explicitly, i.e. `git push --tags origin master`, should work from how I'm reading the docs. Alternatively, there's a `--follow-tags` option which sounds promising. I have no experience with either though. Other options are explicitly listing the branch and tag or just adding a separate `git push` command. The latter is the easiest of these fixes and guaranteed to work.

**Comment by jjjake** [comment]
Thank you @JustAnotherArchivist! This is helpful. I'll update the Makefile.
