### ISSUE TITLE
No 'upload' method on ArchiveSession

### ISSUE THREAD

**Issue by bnewbold** [jjjake/internetarchive#457]
`ArchiveSession` is very helpful when embedding `internetarchive` in larger projects, when it is desirable to pass configuration (eg, authentication secrets) explicitly, rather than relying on the library finding credentials itself (eg, in `~/.config/ia.ini` or elsewhere).

It seems like there is no `upload()` method on the session though, which seems like the best way to create new items. Would it be possible/easy to add that? Or is there some some pattern to use? For existing items it looks like `session.get_item()` and then `item.upload()` would work, but i'm not sure what the idiomatic way to create new items is using a session.

Thanks always for maintaining `internetarchive`!

**Comment by jjjake** [comment]
Yes, I would suggest the following:

```
>>> from internetarchive import get_session
>>> s = get_session()
>>> item = s.get_item('<id>')
>>> r = item.upload(...)
```
