### ISSUE TITLE
[Request] Add local directory download location arg to CLI

### ISSUE THREAD

**Issue by secretclean** [jjjake/internetarchive#461]
I think it'd be great to specify a local directory to download files to from the "ia download" CLI.

I looked over the CLI documentation and didn't see a way to specify a location, nor with the help args right in CLI.

A use case for this would be if you were using a Pi booting from SD card to download a collection. You would attach an external storage device and download the collection to the mnt instead.

Please close if already discussed. Also if this is really simple to do outside of this package, please lemme know. Thanks!

**Comment by jjjake** [comment]
I believe you are looking for `--destdir`:

```
    --destdir=<dir>                          The destination directory to download files
                                             and item directories to.
```
