### ISSUE TITLE
Specify 'Format' on upload with --spreadsheet?

### ISSUE THREAD

**Issue by DoubleACS** [jjjake/internetarchive#463]
I have an issue that when I upload 'h.264 HD' files to IA the 'scanner' reads the file as 'MPEG4'.  The file is an h.264 file so I am not sure why our files are being read that way.  I can edit the metadata and change the file's format to 'h.264 HD' but I can't do it via the IA CLI tool.  Once I do change the format everything derives as it should.

When I use this command:
ia metadata <identifier> --target 'files/<identifier>.HD.mp4' --modify 'format:h.264 HD'
I get the following:
<identifier> - error (400): Modification or addition of intrinsic property 'format' not allowed

So I am assuming you can't modify the file 'format' after the file has been uploaded using the IA CLI.

So, is it possible to specify the format using the upload action?

I always us the spreadsheet option so if you can specify the format during upload, what should the header be labeled and how should I specify 'h.264 HD' in that field?

Thank you.

**Comment by jjjake** [comment]
Unfortunately it's not possible to set format at time of upload via the IA S3-like API (you can set file-level metadata, but format will be overwritten by our system), and modifying the format via the Metadata API is only possible for very high-level admins.

I recommend contacting info@archive.org to figure out why your files aren't getting the correct format. My apologies for the trouble!
