### ISSUE TITLE
Download Progress Gets Deleted on Error

### ISSUE THREAD

**Issue by RocketRider101** [jjjake/internetarchive#468]
Hi, so I'm having trouble with files for items that are currently downloading when an error occurs completely disappearing after said error. Previous successfully downloaded items are unaffected. I am using the basic `ia download collection_name` command, not sure if I'm just doing something wrong or what. Here's an example of the most recent error I got while trying to download the `no-intro_romsets` collection. I'm on Arch Linux, using `ia` v2.3.0. This problem happened to me on 2.2.0 and 2.1.0 as well.

`error downloading file no-intro_romsets/no-intro romsets/Nintendo - Nintendo 64 (ByteSwapped) (20211218-085838).zip, exception raised: HTTPSConnectionPool(host='ia601409.us.archive.org', port=443): Read timed out.`

Then just like that, the entire download vanishes into the ether. I can't just resume it from where it cut off like I can if I download it on a browser. Nope, gotta start again from 0. This is especially frustrating because of the long download times, since if it fails at, say, 9.99GB on a 10GB download, it would take me hours to get to that same point again.

**Comment by jjjake** [comment]
Resuming downloads is not currently supported.

**Comment by RocketRider101** [comment]
Huh, well... oops a daisy on my end then. Any idea when it will become supported? It'd be an extremely nice thing to to have.

**Comment by JustAnotherArchivist** [comment]
You could run the actual downloads with wget instead. It supports resuming on errors with `--continue`. `ia download` has the `--dry-run` option which prints the URLs of all files to be downloaded on stdout, which you can then pipe to `xargs wget ...` with the appropriate options for error retries etc.

**Comment by klausmcm** [comment]
@JustAnotherArchivist Does that work for you? I tried this and it doesn't work for me. I tried something like this

`wget --user='<user>' --password='<pw>' "<url>"`

and I get this error

```
HTTP request sent, awaiting response... 403 Forbidden
2022-12-28 13:50:03 ERROR 403: Forbidden.
```

**Comment by JustAnotherArchivist** [comment]
@klausmcm It definitely works for items that don't require authentication. For ones that do, it's trickier. Your attempt uses HTTP Basic Auth, and I'm pretty sure IA does not support that. The easiest way would probably be to pass a cookie jar to wget.

**Comment by klausmcm** [comment]
@JustAnotherArchivist Your suggestion gave me enough to look up what I needed. I went with this suggestion since no installation of extra tools is required - using `curl` instead.

* https://askubuntu.com/a/1099876

Thank you.

**Comment by klausmcm** [comment]
Actually, did some reading and just used the `-H` portion containing the cookie information in the curl command and passed that with the `--header` flag in the wget command. All is working well.
