### ISSUE TITLE
Stop adding cookies to config file

### ISSUE THREAD

**Issue by jjjake** [jjjake/internetarchive#471]
Since [IAS3 authorization is now supported by advancedsearch.php](https://github.com/jjjake/internetarchive/commit/93e3237f1846a19fcd20af73c83838628b6f3457), I do not think any other endpoints called within the library rely on archive.org logged-in-* cookies for authorization. 

I'd like to support cookies in config files indefinitely (i.e. use them if they are in the config), but I think we should stop writing them to the config by default and have an option like `ia configure --save-cookies`.

Please let me know if anyone has any feedback on this! Thanks!

**Comment by JustAnotherArchivist** [comment]
If there is no need for these anymore, I don't see any reason to keep writing them. Some docs updates are definitely in order then though as they still mention that cookies are required for downloading access-restricted items and accessing tasks.

`Item.remove_from_simplelist` seems to rely on cookies currently though, or at least it isn't passing S3 auth headers. That's the only one I could find based on some brief searches.

**Comment by jjjake** [comment]
There are times when having a session object with archive.org logged-in-* cookies attached is helpful for IA admins, so I would like to support cookies in config files indefinitely (just not by default).

Thanks for the reminder about the docs, and `Item.remove_from_simplelists`! I'll see if `Item.remove_from_simplelists` supports IAS3 authorization yet.
