### ISSUE TITLE
Checksum skipping does not work when downloading `${IDENTIFIER}_files.xml` file

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#487]
This is really a bug in the backend, not `ia`, but I'm filing it here anyway because it's most apparent through `ia download` usage.

Each IA item contains an `${IDENTIFIER}_files.xml` file which lists all files in the item. Unfortunately, it also contains an MD5 hash of itself, which obviously can't ever be correct. This means that the hash comparison on `--checksum` always fails, so it gets redownloaded every time (output with WIP code for an upcoming PR, but the details aren't relevant):

```
$ ia download nasa --checksum
nasa:
 skipping nasa/__ia_thumb.jpg, file already exists based on checksum.
 skipping nasa/globe_west_540.jpg, file already exists based on checksum.
 skipping nasa/globe_west_540_thumb.jpg, file already exists based on checksum.
 skipping nasa/nasa_archive.torrent, file already exists based on checksum.
 downloading nasa_files.xml: 2.56kiB [00:00, 4.80MiB/s]
 skipping nasa/nasa_itemimage.jpg, file already exists based on checksum.
 skipping nasa/nasa_meta.sqlite, file already exists based on checksum.
 skipping nasa/nasa_meta.xml, file already exists based on checksum.
 skipping nasa/nasa_reviews.xml, file already exists based on checksum.
```

Ideally, the MD5 hash would be removed from the file, and then `File.download` could fall back to mtime comparison when it is missing. This is what the docs suggest should be happening (note the different message on the last line):

https://github.com/jjjake/internetarchive/blob/0cff0f0e5d4702690d61441e981611fb2df18a3d/docs/source/quickstart.rst#L166-L174

Another solution would be to hardcode this specific file to never get checksummed, but I'm not a big fan of that idea.

**Comment by JustAnotherArchivist** [comment]
Actually, the mtime and size comparison won't work either because there is no mtime or size recorded for that file (at least on the `nasa` item). So unless we want to use `HEAD` to get `Last-Modified` and `Content-Length`, which seems ridiculous complexity for such a minor issue, redownload every time it is...

And yeah, didn't expect that it'd get fixed on the backend. I assume preventing the checksum for that file from getting written would just be a couple lines of code at most, but it'd then require reprocessing every existing item, so yeah, obviously not going to happen. Oh well...

**Comment by jjjake** [comment]
Yeah, the processing every item on archive.org is the big hold up here.

Thanks for confirming that mtime and size won't work without getting `Last-Modified` and `Content-Length`. I agree that that's a bit much for this minor issue. Let's stick with re-downloading for now.
