### ISSUE TITLE
ia download --debug doesn't show any infos

### ISSUE THREAD

**Issue by MaxPeal** [jjjake/internetarchive#494]
user@box:/tmp$ curl -LOs https://archive.org/download/ia-pex/ia
user@box:/tmp$ chmod +x ia
user@box:/tmp$ ia -v
2.3.0
user@box:/tmp$ ia download --debug TripDown1905 "TripDown1905.mp3"
usage:
    ia download <identifier> [<file>]... [options]...
    ia download <identifier> <file> --stdout [options]...
    ia download --itemlist=<file> [options]...
    ia download --search=<query> [options]...
    ia download --help
user@box:/tmp$

**Comment by JustAnotherArchivist** [comment]
`--debug` is not an option for `ia download`. Did you mean the global option, i.e. `ia --debug download ...`, which writes a verbose log to `./internetarchive.log`?

**Comment by jjjake** [comment]
That's correct. `--debug` is a global option as mentioned. It should be used between `ia` and the subcommand (e.g. `ia --debug download nasa`). All of the options in `ia --help` are gloabl options. Any options after a subcommand are the options for that subcommand and should go after the subcommand (e.g. `ia upload --retries 10 <id> <file>`).

I'm closing, but happy to reopen or create another issue if anyone thinks this should behave differently. It is a little quirky, IMO.
