### ISSUE TITLE
ia download --verbose doesn't show any verbose infos

### ISSUE THREAD

**Issue by MaxPeal** [jjjake/internetarchive#495]
user@box:/tmp$ curl -LOs https://archive.org/download/ia-pex/ia
user@box:/tmp$ chmod +x ia
user@box:/tmp$ ia -v
2.3.0
user@box:/tmp$ ia download --verbose TripDown1905 "TripDown1905.mp3"
TripDown1905:
 downloaded TripDown1905/TripDown1905.mp3 to TripDown1905/TripDown1905.mp3
user@box:/tmp$

**Comment by JustAnotherArchivist** [comment]
That *is* the verbose output in version 2.3.0. The option has since been removed in master (#488), and the new verbose output is enabled by default.

**Comment by jjjake** [comment]
Closing as JustAnotherArchivist mentioned that is the verbose output, and also this will be changing a bit in v3.0.0.
