### ISSUE TITLE
ia download is not properly downloading files

### ISSUE THREAD

**Issue by julerobb1** [jjjake/internetarchive#496]
As the title says, it's not downloading files properly. its only downloading a torrent file, a thumbnail thats the the internet archive logo and the collection image, its also downloading an .sqlite, and two.xml files. It's not downloading any of the content in any collection i go to.  I haven't tried wget yet but I am about to. Can someone aid me with this or look into it and make sure it's not user error?

**Comment by JustAnotherArchivist** [comment]
Collections are actually items, and what you describe are the typical contents of a collection item, so it sounds like it behaves correctly.

I suspect you want to download the items contained in the collection instead, not the collection item itself. That would require a search, e.g. `ia download --search 'collection:collection_name'`.

**Comment by julerobb1** [comment]
> Collections are actually items, and what you describe are the typical contents of a collection item, so it sounds like it behaves correctly.
> 
> I suspect you want to download the items contained in the collection instead, not the collection item itself. That would require a search, e.g. `ia download --search 'collection:collection_name'`.

that is precisely what i want. 

additionally, how can I direct it download to an external drive, where the drive letter is D:?

**Comment by JustAnotherArchivist** [comment]
> additionally, how can I direct it download to an external drive, where the drive letter is D:?

`ia` always just downloads into the current directory. So switch to wherever you want to download to before executing `ia`. (I can't tell you how to do that as I haven't used Windows in a decade, but I'm sure a web search will help you with that.)

> Edit: Tried it, it said in response `"error: the query "'collection:bellsystempractices'" returned no results"`

Ah yes, Windows being Windows with different quoting rules from every other shell out there. Try double quotes instead of single quotes.

**Comment by julerobb1** [comment]
on another note, trying in a different manner returned this :

**Comment by julerobb1** [comment]
> > additionally, how can I direct it download to an external drive, where the drive letter is D:?
> 
> `ia` always just downloads into the current directory. So switch to wherever you want to download to before executing `ia`. (I can't tell you how to do that as I haven't used Windows in a decade, but I'm sure a web search will help you with that.)
> 
> > Edit: Tried it, it said in response `"error: the query "'collection:bellsystempractices'" returned no results"`
> 
> Ah yes, Windows being Windows with different quoting rules from every other shell out there. Try double quotes instead of single quotes.

As for changing directories, i know how to that, as its as simple as cd /d D:


but when i do that, it doesnt let me use python for whatever odd reason

**Comment by JustAnotherArchivist** [comment]
> `BSP_000-000-001` etc.

Those items are access-restricted. You will only be able to download a few metadata files from them.

**Comment by julerobb1** [comment]
thats a shame. it's exactly what i want to download, which are old documents from the bell system. Mainly because of the old AT&T Long Lines towers, but also because its a piece of history. Is there a way to obtain access to them? I figured since they were on the web and not current they would be open for all to access.

**Comment by jjjake** [comment]
Please contact info@archive.org about access questions, @julerobb1. You can reach out to me directly (my email is on my profile), if you have questions about the command-line tool. Thank you!
