### ISSUE TITLE
glob pattern is not working with format option in downloading

### ISSUE THREAD

**Issue by a1111198** [jjjake/internetarchive#539]
I want to download a directory that consists of files of (some_name.ia.mp4 and some_name.mp4) and I want to download only some_name.mp4 but using the glob pattern like (*mp4) will return both. And on the passing format as MPEG4 it is ignored.
How can I solve this problem?

**Comment by jjjake** [comment]
@a1111198 The glob option is unfortunately not the most flexible, and I'd like to make it more intelligent in the future. Right now it uses the Python `glob` library, but I think it might make more sense to support regular expressions or similar.

However, I believe this should work glob pattern should work for your example:

```*[!.ia].mp4```

I hope this helps!
