### ISSUE TITLE
Modify tags of files

### ISSUE THREAD

**Issue by ngeiswei** [jjjake/internetarchive#54]
Is it possible to use the bash or Python interface to change the tags of a file, as opposed to an item.

For instance, I can

ia metadata [--modify=key:value...] identifier

to modify the tag of item identifier, but can I do that for say the Title of a song within that item?

**Comment by darkivist** [comment]
Sorry to reopen such an old issue, but was file metadata editing via csv ever added to the CLI?

**Comment by jjjake** [comment]
@darkivist https://archive.org/services/docs/api/internetarchive/cli.html#modifying-metadata-in-bulk

**Comment by darkivist** [comment]
Thanks, I'm familiar. Does that process work for files inside items, though?

**Comment by jjjake** [comment]
@darkivist Editing file-level metadata is not currently supported in spreadsheet mode. You'll have to use a for-loop or something like [GNU Parallel](https://archive.org/services/docs/api/internetarchive/parallel.html) with a command like:

`ia metadata my_identifier --target="files/foo.txt" --modify="title:My File"`

file-level metadata can also be [set at upload](https://archive.org/services/docs/api/internetarchive/cli.html#setting-file-level-metadata-on-upload).
