### ISSUE TITLE
'ia search' not outputting results that match a search of my own items when in browser

### ISSUE THREAD

**Issue by vxbinaca** [jjjake/internetarchive#549]
I'd like to be able to whip out a search result of my uploads using my login creds for my account, not whats publicly indexed which is the default, so I can get an accurate accounting (or any accounting) of what a creator has on the site. If this is a me problem, please close and point out what I'm doing wrong.

thanks.

**Comment by maxz** [comment]
This is a limitation of the Search API, not a limitation of the `internetarchive` CLI.

Also see #426.

**Comment by jjjake** [comment]
Closing, and replying in #426. Thanks for the feedback/question, @vxbinaca!
