### ISSUE TITLE
bad interpreter: /usr/local/opt/python@3.9/bin/python3.9

### ISSUE THREAD

**Issue by gingerbeardman** [jjjake/internetarchive#553]
whenever I run `ia` I get this oddity:

> zsh: /usr/local/bin/ia: bad interpreter: /usr/local/opt/python@3.9/bin/python3.9: no such file or directory

any idea how to get rid of that?

any help appreciated

## some details

```
$ which ia
/usr/local/bin/ia
$ which pyenv
/opt/homebrew/bin/pyenv
$ which python
/Users/matt/.pyenv/shims/python
$ which python3
/opt/homebrew/bin/python3
$ python3 --version
Python 3.10.8
```

## my setup
- macOS/12.6.1

- internetarchive/3.0.2
- ia/2.3.0

**Comment by jjjake** [comment]
It looks like you might've installed `internetarchive` with Python 3.9, but that no longer exists on your system (or has moved)? I would suggest re-installing with your current version of Python, i.e. `python3 -m pip install --force internetarchive`.

**Comment by gingerbeardman** [comment]
Many thanks! I've done that and will keep an eye on it, looks good so far.
