### ISSUE TITLE
How to --glob multiple files

### ISSUE THREAD

**Issue by LostAccount** [jjjake/internetarchive#559]
Hello

What if I want to glob two file types? How would I modify the command line?
`ia download TripDown1905 --glob="*.mp4"`

Thanks!

**Comment by maxz** [comment]
`ia download TripDown1905 --glob="*.mp4|*.ogv"`, but this is an issue tracker and not a support forum.

That part is not covered in the documentation so looking there would no have been much help, but please try reaching out to `info@archive.org` next time.

**Comment by LostAccount** [comment]
Hi maxz, 

Thank you for the reply despite my misuse. I didn't know the Issues was strictly for tracking issues. Thanks again for your patience.

**Comment by JustAnotherArchivist** [comment]
I think there *is* an issue here, namely the lack of documentation.
