### ISSUE TITLE
Delete identifier

### ISSUE THREAD

**Issue by eubrunosilva** [jjjake/internetarchive#560]
Hi
its possible to delete identifiers?
I only find how to delete files inside identifiers
I need to mass delete identifiers and don't know how
Thanks

**Comment by JustAnotherArchivist** [comment]
No, you can't delete identifiers.

IA staff can, but as far as I know, they'll usually only do that in exceptional cases. An identifier, after all, is supposed to *identify* some content, and if it suddenly starts referring to something different (possibly by a different uploader etc.), that's ... not good.

**Comment by eubrunosilva** [comment]
You can delete identifiers via the website. I tough that maybe it was possible to do it thru command line.

**Comment by maxz** [comment]
You can't delete identifiers through the website if you are not staff.
The maximum of what you can do to "remove" something is to darken it, then only staff will be able to access it, but it will still be in the system and the identifier also won't be usable again.

**Comment by jjjake** [comment]
I suggest emailing info@archive.org if you need help recycling an identifier @eubrunosilva.
