### ISSUE TITLE
List identifiers of an account

### ISSUE THREAD

**Issue by eubrunosilva** [jjjake/internetarchive#561]
Hi
its possible to list identifiers inside an account?
Thanks

**Comment by maxz** [comment]
The `ia` issues are really not the kind of place for such enquiries.  But if you had searched the issues for "list identifiers" you would also have found various useful results.
Please use the [documentation](https://internetarchive.readthedocs.io/en/stable/cli.html) in the future and if you really can't find something there then email `info@archive.org`.
