### ISSUE TITLE
proxy issues

### ISSUE THREAD

**Issue by omnizien** [jjjake/internetarchive#566]
hi. I'm just trying to get  the example from the quickstart going :

```
  from internetarchive import get_item
  md = {'collection': 'test_collection', 'title': 'My New Item', 'mediatype': 'movies'}
  r = item.upload('<identifier>', files=['film.txt', 'film.mov'], metadata=md, access_key='YoUrAcCEssKey', secret_key='youRSECRETKEY')
  r[0].status_code

```

  I have to work from behind a VPN, I've tried setting the environment variable HTTP_PROXY, and digging around the ia library for places to enter the proxy variable in the requests.get(..., proxies = {'http':127.0.0.1:8118' })... I'm having no luck here. where / how should I configure the proxy to get this example going? Thanks

**Comment by JustAnotherArchivist** [comment]
`ia` uses HTTPS, so you need to set `HTTPS_PROXY`, not `HTTP_PROXY`.

**Comment by omnizien** [comment]
thanks.  where do we enter this?  I've tried the export HTTPS_PROXY='http://127.0.0.1:8118' with no luck

**Comment by JustAnotherArchivist** [comment]
Yep, like that. Works 'fine' for me with both the CLI and from Python.

(I put 'fine' in quotes because I'm not actually running a proxy, but I get an exception from `ia` being unable to connect to the proxy exactly as expected.)

**Comment by omnizien** [comment]
I've still had no progress with the export variable. as standalone, requests.get always works with passing proxies={'http':'127.0.0.1'} as a parameter, so I've tried going into all the files that have the requests.get (API.py, session.py, etc...)but it's just continuing to hang i'll post the solution when/if i figure it out.

**Comment by omnizien** [comment]
the issue has to do with socks5.  I switched to a different vpn and it worked...I'm still investigation why this is an issue on my other vpn.

**Comment by JustAnotherArchivist** [comment]
Just in case, if you get an error of 'Missing dependencies for SOCKS support' or similar, you'd have to `pip install requests[socks]`. `internetarchive` only depends on `requests`, which doesn't include those dependencies.
