### ISSUE TITLE
Downloading with IA throws "PermissionError: [Errno 13] Permission denied:"

### ISSUE THREAD

**Issue by ventolinmx** [jjjake/internetarchive#567]
Hi

Installed IA with snap and created my configuration file with my account user and password. Can get metadata but can't download any file. Tried with several unique identifiers but still get the same error.

Snap IA folder has all users read/write/execute permissions.

Sorry but I don't know if this is a problem with local permissions or with authentication permissions.

**Comment by ventolinmx** [comment]
Ok nevermind. I have to use sudo to download files.

**Comment by JustAnotherArchivist** [comment]
This sounds like the permissions in your file system are wrong. You definitely don't need sudo to run `ia` in general at least.
