### ISSUE TITLE
On-the-fly files are not skipped for audio files

### ISSUE THREAD

**Issue by e-ave** [jjjake/internetarchive#580]
Need to add support for skipping the auto-generated audio files. 
For every file.flac (and probably other lossless formats like .shn, .wav), archive.org will generate:
file_spectrogram.png
file.afpk
file.mp3
file.png

I'm guessing that most people only want to download either lossless or mp3 files but not both

**Comment by JustAnotherArchivist** [comment]
On-the-fly formats are already filtered by default on `ia download` (unless you use `--on-the-fly`), but these are not on-the-file files, they're derivatives. There's already an open issue about filtering those: #365

**Comment by e-ave** [comment]
Thanks! Your solutions on that issue are just what I needed!
