### ISSUE TITLE
Feature request: add an archive file for already validated (checksum) files

### ISSUE THREAD

**Issue by benbou8231** [jjjake/internetarchive#600]
The idea is to add a parameter (that can be used in pair with --checksum) to allow the software to skip files that were already validated.

This would create a "archive.txt" file that will contain the file_path (item\file) of the files that passed the checksum validation.

My use case is when downloading large item, that contain hundreds of large files.

Having an archive will allow the download to resume much faster since the software will not have to recalculate the hash of many already calculated files.
It will also allow the user to move the files that already passed the checksum validation to another location (let say a NAS or an external hard drive).

**Comment by jjjake** [comment]
This sounds like a really useful feature to me!

**Comment by benbou8231** [comment]
@jjjake I got a pull request that implement this feature: #645 

I look forward to your feedback and/or suggestions.

**Comment by jjjake** [comment]
Thanks @benbou8231! I'll take a look soon. Closing this issue now that we have that MR open. Thanks again!
