### ISSUE TITLE
Unrelated to the repo itself, but can someone develop this for me?

### ISSUE THREAD

**Issue by upintheairsheep** [jjjake/internetarchive#607]
I would like someone to program a small script that streams the contents of a CD, DVD, BD, etc to the Internet Archive as an .iso, .img, or .bin file without having to rip the entire disk onto the hard drive first. I don't have much storage on my computer, and the time required to manually rip, upload, and delete is not my cup of tea. Can someone make some shell script to automate this task, as that would be great. See https://www.thomas-krenn.com/en/wiki/Create_an_ISO_Image_from_a_source_CD_or_DVD_under_Linux for details on the /dev interface in Linux.

**Comment by jjjake** [comment]
I'm closing this as this is a bug tracker for the `internetarchive` Python library, but this would be a cool idea! Good luck!

**Comment by jjjake** [comment]
Perhaps the [archive.org forums](https://archive.org/iathreads/forums.php) would be a good place to post this?
