### ISSUE TITLE
Question: How to upload a new file to an existing item?

### ISSUE THREAD

**Issue by narFnarF** [jjjake/internetarchive#633]
Hi
I'd like to use either the command line or python to upload new files to an existing Item.
I've seen tutorials on how to upload new Items or how to create Collections, but couldn't find any guides on how to upload new files to existing Items.

For context, I want to add new mp3 files to this Item: https://archive.org/details/OnAJusteUneVie

Thank you!

**Comment by jjjake** [comment]
Documentation for uploading is available [here](https://archive.org/developers/internetarchive/cli.html#upload). For example:


    ia upload OnAJusteUneVie foo.mp3
