### ISSUE TITLE
Support changing local filestamps

### ISSUE THREAD

**Issue by Firehawke** [jjjake/internetarchive#635]
Checksum works great for determining if a file matches up and not redownloading it, but it'd be nice if there was an option to then have the script change the timestamp on the local file to match the archive version so it doesn't need to be run through the slow checksum process in the future.

**Comment by jjjake** [comment]
This is already the default behavior of download, unless I'm missing something. Relevant code starts [here](https://github.com/jjjake/internetarchive/blob/master/internetarchive/files.py#L240).

 That is, a local files mtime is set to the mtime in it's files.xml entry on archive.org. Download then skips over any files that already exist locally with a matching mtime, file size, and file name.

My apologies if I misunderstood your request, and thanks for taking the time to make it! I appreciate it.

**Comment by Firehawke** [comment]
Okay, I think I need to clarify slightly.

I'm working with a partial set that was downloaded with a browser, so the timestamps don't match. This necessitates the use of checksum to detect that these files are correct. What I'd like is a way to tell the script to, once these files are verified with checksums, change the timestamps to match so I don't need to use checksum for future passes.

The sets in working with are getting periodic updates and adjustments so I will be revisiting them at least once a year.
