### ISSUE TITLE
Download only mp4 if exists, otherwise mkv otherwise whatever other exists in video format in a listing? 

### ISSUE THREAD

**Issue by estatistics** [jjjake/internetarchive#636]
Download only mp4 if exists, otherwise mkv otherwise whatever other exists in video format in a listing? 
A listing can have mp4, ogv and mkv as video formats. 

I use the either "|" character to download "either of these" 
`for line in $(cat listings.txt); do ia download --glob="*.mp4|*.mkv|*.txt|*.vtt" "$line"; done`

However, i dont know how to make a priority to download either mp4 or mkv video format, depending which of ones exists in the internet archive listing.

How i can do that?

**Comment by jjjake** [comment]
I would suggest using a Python script for this. For example:

```
#!/usr/bin/env python3
import sys

from internetarchive import get_item


def get_video_files(item):
    extensions = ['mp4', 'mkv']

    video_files = []
    for ext in extensions:
        for file in item.get_files(glob_pattern=f"*.{ext}"):
            if file.source == 'original':  # Do not return derivatives
                video_files.append(file)

        if video_files:
            break

    return video_files


if __name__ == '__main__':
    identifier = sys.argv[-1]
    item = get_item(identifier)

    video_files = [f.name for f in get_video_files(item)]
    rsps = item.download(video_files, verbose=True)

    if all([r.status_code == 200 for r in rsps]):
        sys.exit(0)
    else:
        sys.exit(1)
```
