### ISSUE TITLE
 https://archive.org/download/ia-pex/ia is currently unreachable

### ISSUE THREAD

**Issue by antiphishfish** [jjjake/internetarchive#647]
Hello there,

This URL to download the ia cli program is currently unreachable:

```
$ wget https://archive.org/download/ia-pex/ia
--2024-05-04 14:38:26--  https://archive.org/download/ia-pex/ia
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response...
302 Found
Location: https://ia804606.us.archive.org/15/items/ia-pex/ia [following]
--2024-05-04 14:38:37--  https://ia804606.us.archive.org/15/items/ia-pex/ia
Resolving ia804606.us.archive.org (ia804606.us.archive.org)... 207.241.235.93
Connecting to ia804606.us.archive.org (ia804606.us.archive.org)|207.241.235.93|:443...
Connecting to ia804606.us.archive.org (ia804606.us.archive.org)|207.241.235.93|:443... failed: Connection refused.
```

Cheers!

**Comment by jjjake** [comment]
Thanks for the report @antiphishfish. We had some issues with our site, but they should now be resolved.

I'll go ahead and close this, but please let me know if you're still having issues.

**Comment by jjjake** [comment]
@antiphishfish There is not an official mirror of the `ia` binary specifically, no. You could always [install from pypi](https://pypi.org/project/internetarchive/) or github though.

I will look into this though, that's a great suggestion. Thank you!
