### ISSUE TITLE
Wayback Machine JavaScript:showImg not working

### ISSUE THREAD

**Issue by CoolDino1** [jjjake/internetarchive#648]
On https://web.archive.org/web/20240517221935/https://www.bricklink.com/messageThread.asp?ID=356023&nID=1463288 the button to enlarge the image is not working. It goes to https://web.archive.org/web/20240517221935/JavaScript:showImg(1463289,'/myImg/939549.png')

**Comment by maxz** [comment]
This is the repository for a command line tool and library to interact with the Internet Archive. Not for the Internet Archive or the Wayback Machine itself. Please contact [info@archive.org](mailto:info@archive.org) for your issue.
