### ISSUE TITLE
cant search using the cli

### ISSUE THREAD

**Issue by Wulgaren** [jjjake/internetarchive#655]
hello! heres what i got when i try to search for anything using the cli

command: ia search collection:BullOfHeaven
error: Expecting value: line 1 column 1 (char 0)

is this an error because of the recent attacks?

**Comment by jjjake** [comment]
Sorry for the confusing error message. `ia search` should be mostly working again. Note that our team is still working on brining parts of our search services back online at the moment though. For example, our full text search API is still offline.

Please let me know if `ia search collection:BullOfHeaven` is still now working for you though. Thanks!

**Comment by Wulgaren** [comment]
yup its working!! thank you very much - quick question, do IA torrents still work if IA is down?
