### ISSUE TITLE
s3.us.archive.org seems unreachable 

### ISSUE THREAD

**Issue by maaaaz** [jjjake/internetarchive#657]
Hello there,

First, a big round of applause to have fought this incident on Internet Archive !
Then, it might still be *normal* to date, but `s3.us.archive.org` is still unreachable while trying to upload files with an `ia upload <item> <file>` command.

Any ETA of the resolution ?

Cheers!

**Comment by jjjake** [comment]
s3.us.archive.org is not currently accepting public submissions. Please email info@archive.org for more information and details on when it will be back up. Thanks!
