### ISSUE TITLE
v5.0.0: cli broken on Windows

### ISSUE THREAD

**Issue by neodyne** [jjjake/internetarchive#658]
Python v3.13.0, Windows 10 x64, `internetarchive==5.0.0` installed via pip.

```
C:\>python.exe --version
Python 3.13.0

C:\>ia.exe
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\xxxxxx\Python\Scripts\ia.exe\__main__.py", line 4, in <module>
    from internetarchive.cli.ia import main
  File "C:\xxxxxx\Python\Lib\site-packages\internetarchive\cli\__init__.py", line 26, in <module>
    from internetarchive.cli import (
    ...<13 lines>...
    )
  File "C:\xxxxxx\Python\Lib\site-packages\internetarchive\cli\ia.py", line 44, in <module>
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGPIPE'. Did you mean: 'SIGFPE'?

```

It seems that [signal.SIGPIPE is not available on Windows](https://docs.python.org/3/library/signal.html#signal.SIGPIPE).

**Comment by jjjake** [comment]
Thanks for the report @neodyne, and sorry for the trouble! 

I think https://github.com/jjjake/internetarchive/pull/659/files should fix it. Are you able to test it out using this branch?

**Comment by neodyne** [comment]
The fix works, however afaik <ctrl+c> handling could have been kept, `signal.SIGINT` should work crossplatform.
So maybe something like?

```
# Handle broken pipe
try:
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
except AttributeError:
    # Non-unix support
    pass

# Handle <Ctrl-C>
signal.signal(signal.SIGINT, exit_on_signal)

```

**Comment by jjjake** [comment]
@neodyne Awesome, thanks for testing and providing feedback. I just pushed [109c996](https://github.com/jjjake/internetarchive/pull/659/commits/109c996ce21b8010cdba4f0b94ff12c132265fc5). I'll go ahead and merge this once the tests finish running and ship a new release.

Thanks again!
