### ISSUE TITLE
slow uploads

### ISSUE THREAD

**Issue by 111100001** [jjjake/internetarchive#664]
![image](https://github.com/user-attachments/assets/80ae46dd-a356-4cdc-9099-d3bb2ebf58c7)

i know this is probably caused by Internet Archive throttling me maybe, but it doesn't hurt to ask if this happens to anyone else. 

the uploads are very slow.

**Comment by jjjake** [comment]
Sorry for the trouble! Yes, our S3-like API is pretty saturated at the moment. Thanks for your patience.
