### ISSUE TITLE
Broken pipe uploading

### ISSUE THREAD

**Issue by viric** [jjjake/internetarchive#80]
Using "ia upload" I get a Broken Pipe error at the 2nd megabyte transferred. With tcpdump I see that the remote S3 host actually sends a TCP reset; ia retries with a 2nd connection, but it's also reset, and then the python exception is dumped to stderr. The "-R" (max num of retries) seems to have little effect

I've tried regenerating the AWS keys, I ensured that the process has the env vars set with the key/secret, and --status-check reports all fine. Nevertheless, my uploads always get Broken Pipe.

This may be a transient error from S3, but it happened to me several times also in the past; anyone has an idea on how to solve this? My solution until now has always been to use the web upload.

I'm susrprised because the connection is dropped after almost 2MB tranferred.

**Comment by saper** [comment]
Which version of `requests` do you have? Are you using `cython` ? It might be shazow/urllib3#535 which breaks HTTP pipelining on a compressed stream.

**Comment by johtso** [comment]
I'm having this same issue. I tend to only get the broken pipe with a specific file/item, and it then repeatedly gives me the broken pipe at roughly the same stage of the upload.

versions:

```
Python 2.7.9 (default, Feb 10 2015, 03:28:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin

requests==2.3.0
internetarchive==0.8.1
```

**Comment by johtso** [comment]
Tried upgrading to latest requests (`2.7.0`) and still experience the same problem.

**Comment by saper** [comment]
What does the tcpdump say? Are you having `Connection: keep-alive` set in the headers? I have had the same issue you have and `requests` upgrade fixed it for me. You might need to apply https://github.com/jjjake/ia-wrapper/pull/82
