### ISSUE TITLE
503s when downloading are unexpectly persistent

### ISSUE THREAD

**Issue by wumpus** [jjjake/internetarchive#87]
This client doesn't throttle when it gets a 503 from the server. I see problems when I'm doing

cat big-list-of-ids | parallel ia download {1} {1}_abbyy.gz

Once it starts getting 503s, it gets a lot. Notice that each client execution is a separate process.

I added a time.sleep(2.0) call to item.py right before "raise HTTPError". Now I only see a couple of 503s before it returns to normal downloading.

**Comment by jjjake** [comment]
Thanks for the report @wumpus, I appreciate it. I added this functionality in 4c6dba07b618adf96c7844a1d5d224fa458c98cf using `urllib3.Retry()`.

In v0.9.7, in the CLI, you can now do:

```
$ cat big-list-of-ids | parallel ia download {1} {1}_abbyy.gz --retries 5
```

**Comment by wumpus** [comment]
Jake mentioned that --retries has a default of 2 or 3 or so, which is probably enough for most purposes.
